/* js/data-shared.js — vocabulary and cross-module data
   Load order: data-shared → data-mplus → data-raid → render → app.
   All five load with `defer`, which preserves this order. */

/* ═══════════════════════════════════════════════════════════════════════
   DATA · SOURCE LEDGER
   tier 1 = Blizzard directly — patch notes, hotfixes, the Encounter Journal
   tier 2 = Wowhead / Icy Veins
   tier 3 = established creators · 4 = SEO and boosting sites
   ═══════════════════════════════════════════════════════════════════════ */
const SOURCES={
 bz_game:{l:"BLIZZARD",t:1,k:"blizzard",a:"Blizzard",b:"Patch 12.1 notes and in-game data",d:"2026-08-16",u:"https://worldofwarcraft.blizzard.com/en-us/news",note:"Season structure, affix bands, reward tracks and drop sources as published by Blizzard or read directly from the live client."},
 wh_ej  :{l:"JOURNAL",t:1,k:"journal",a:"Blizzard Encounter Journal",b:"In-game dungeon journal, mirrored by Wowhead (PTR 12.1.0)",d:"2026-08-16",u:"https://www.wowhead.com/",note:"The text is Blizzard's own. The delivery is a third-party mirror, so transcription error is possible and PTR values can still move — but on names, numbers and mechanics this outranks every guide."},
 bz0813 :{l:"BLIZZARD",t:1,k:"blizzard", a:"Blizzard",b:"Hotfixes: 13 August 2026",d:"2026-08-13",u:"https://news.blizzard.com/en-us/article/24296142/hotfixes-august-14-2026"},
 bz0814 :{l:"BLIZZARD",t:1,k:"blizzard", a:"Blizzard",b:"Hotfixes: 14 August 2026",d:"2026-08-14",u:"https://news.blizzard.com/en-us/article/24296142/hotfixes-august-14-2026"},
 wh_dt  :{l:"WOWHEAD",t:2,k:"wowhead",  a:"Wowhead",b:"Midnight Season 2 Dungeon Tuning for Patch 12.1",d:"2026-07-25",u:"https://www.wowhead.com/news/midnight-season-2-dungeon-tuning-for-patch-12-1-382238"},
 wh_va  :{l:"WOWHEAD",t:2,k:"wowhead",  a:"Wowhead",b:"The Venomous Abyss Raid Overview",d:"2026-08-17",u:"https://www.wowhead.com/guide/midnight/raids/the-venomous-abyss-overview-location-rewards-bosses"},
 wh_vr  :{l:"WOWHEAD",t:2,k:"wowhead",  a:"Wowhead",b:"The Venomous Abyss Rewards Guide",d:"2026-08-17",u:"https://www.wowhead.com/guide/midnight/raids/the-venomous-abyss-rewards-gear-loot"},
 iv_va  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Neryssa)",b:"The Venomous Abyss Raid Guide",d:"2026-07-27",u:"https://www.icy-veins.com/wow/venomous-abyss-raid-guide"},
 iv_nek :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Nek'zali the Soulcoiler Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/nekzali-raid-guide"},
 iv_sen :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Entombed Sentinels Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/entombed-sentinels-raid-guide"},
 iv_exp :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Lost Explorers Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/lost-explorers-raid-guide"},
 iv_ssz :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Sszorak Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/sszorak-raid-guide"},
 iv_vas :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Vashnik Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/vashnik-raid-guide"},
 iv_twf :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Twin Fangs Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/twin-fangs-raid-guide"},
 iv_alt :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Coiled Altar Raid Guide",d:"2026-08-13",u:"https://www.icy-veins.com/wow/coiled-altar-raid-guide"},
 iv_ula :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Panthea)",b:"Ula'tek Raid Guide — no PTR testing, strategy pending live",d:"2026-08-13",u:"https://www.icy-veins.com/wow/ulatek-raid-guide"},
 me_nek :{l:"METHOD",t:3,k:"method",   a:"Method",b:"Heroic Nek'zali the Soulcoiler Boss Guide",d:"2026-08-17",u:"https://www.method.gg/guides/the-venomous-abyss/nekzali-the-soulcoiler-heroic"},
 me_sen :{l:"METHOD",t:3,k:"method",   a:"Method",b:"Heroic Entombed Sentinels Boss Guide",d:"2026-08-17",u:"https://www.method.gg/guides/the-venomous-abyss/entombed-sentinels-heroic"},
 wg_va  :{l:"WOW.GG",t:4,k:"wowgg",    a:"wow.gg (Fouren)",b:"Venomous Abyss Raid Guide — fight descriptions are Mythic-based by its own note; cited for structure, loot and Ula'tek",d:"2026-08-13",u:"https://wow.gg/guides/venomous-abyss"},
 iv_ov  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Gogogadgetkat)",b:"Midnight Mythic+ Season 2 Guide",d:"2026-08-05",u:"https://www.icy-veins.com/wow/midnight-mythic-plus-season-2-guide"},
 iv_aof :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Altar of Fangs Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/altar-of-fangs-dungeon-guide"},
 iv_bv  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"The Blinding Vale Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/the-blinding-vale-dungeon-guide"},
 iv_mr  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Murder Row Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/murder-row-dungeon-guide"},
 iv_don :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Den of Nalorakk Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/den-of-nalorakk-dungeon-guide"},
 iv_vsa :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Voidscar Arena Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/voidscar-arena-dungeon-guide"},
 iv_rlp :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Ruby Life Pools Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/ruby-life-pools-dungeon-guide"},
 iv_kr  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"King's Rest Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/kings-rest-dungeon-guide"},
 ig     :{l:"IN-GAME",t:1,k:"capture",a:"In-game observation",b:"Walked in the client",d:"2026-08-17",u:null,note:"Direct observation of the content by this compendium's author. Tier 1 because the game itself is the primary source \u2014 but unlike the Encounter Journal it is one person recalling one run, so it is cited for structure and sequence rather than for numbers."},
 img    :{l:"CAPTURE",t:1,k:"capture",a:"In-game capture",b:"Boss and entrance imagery, patch 12.1 PTR",d:"2026-08-16",u:null,note:"Screenshots of the encounters with in-game nameplates legible. Useful as a check on spelling, since the nameplate is the game's own rendering of the name."},
 wh_dg  :{l:"WOWHEAD",t:2,k:"wowhead",a:"Wowhead (iMX3)",b:"Season 2 Mythic+ dungeon overviews, all eight",d:"2026-08-12",u:"https://www.wowhead.com/guide/mythic-plus-dungeons/midnight-season-2"},
 tk_aof :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Altar of Fangs Mythic+ Dungeon Guide",d:"2026-08-01",u:"https://www.youtube.com/watch?v=cgM-EioPF0g"},
 tk_bv  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Blinding Vale Mythic+ Dungeon Guide",d:"2026-08-02",u:"https://www.youtube.com/watch?v=HcvkIzRTdtY"},
 tk_mr  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Murder Row Mythic+ Dungeon Guide",d:"2026-08-03",u:"https://www.youtube.com/watch?v=jE7g21vi290"},
 tk_don :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Den of Nalorakk Mythic+ Dungeon Guide",d:"2026-08-04",u:"https://www.youtube.com/watch?v=gNJ-3-6k75A"},
 tk_vsa :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Voidscar Arena Mythic+ Dungeon Guide",d:"2026-08-05",u:"https://www.youtube.com/watch?v=Da9hWBW_6JE"},
 tk_rlp :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Ruby Life Pools Mythic+ Dungeon Guide",d:"2026-08-06",u:"https://www.youtube.com/watch?v=u-TVxNPFMZs"},
 tk_tank:{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"EVERYTHING that will KILL TANKS in Midnight Season 2 Mythic+",d:"2026-08-16",u:"https://www.youtube.com/watch?v=ZS1GMWVLegs"},
 tk_tech:{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Tips, Tricks, and Tech for ALL 8 Midnight Season 2 Mythic+ Dungeons",d:"2026-08-17",u:"https://www.youtube.com/watch?v=Bg29hU3BBz4"},
 tk_kr  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"King's Rest Mythic+ Dungeon Guide",d:"2026-08-07",u:"https://www.youtube.com/watch?v=pT8A8RW9QTc"},
 tk_tos :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Temple of Sethraliss Mythic+ Dungeon Guide",d:"2026-08-08",u:"https://www.youtube.com/watch?v=qBM_N6qBcEc"},
 tk_pool:{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Thoughts on the Season 2 Dungeon Pool, Rewards and Resilient Keystones",d:"2026-07-25",u:"https://www.youtube.com/watch?v=IcBeTr3VTbo"},
 me_ssz :{l:"METHOD",t:3,k:"creator",  a:"Method",b:"Sszorak Boss Guide video (presented by Purke of <Honolulu>)",d:"2026-08-13",u:"https://www.youtube.com/watch?v=SfPXUQ8melM"},
 me_exp :{l:"METHOD",t:3,k:"creator",  a:"Method",b:"The Lost Explorers Boss Guide video (presented by Purke of <Honolulu>)",d:"2026-08-14",u:"https://www.youtube.com/watch?v=dRmU77JQ_Yg"},
 me_vas :{l:"METHOD",t:3,k:"creator",  a:"Method",b:"Vashnik the Malignant Boss Guide video (presented by Purke of <Honolulu>)",d:"2026-08-13",u:"https://www.youtube.com/watch?v=gTdNoxqAHOQ"},
 me_twf :{l:"METHOD",t:3,k:"creator",  a:"Method",b:"The Twin Fangs Boss Guide video (presented by Purke of <Honolulu>)",d:"2026-08-14",u:"https://www.youtube.com/watch?v=SoOCwJT2qYI"},
 bs_alt :{l:"BRETTSTEFANI",t:3,k:"creator",  a:"BrettStefani",b:"TLDR Coiled Altar Boss Guide",d:"2026-08-12",u:"https://www.youtube.com/watch?v=818k4yfy8D4"},
 jf_va  :{l:"JFUNKGAMING",t:3,k:"creator",  a:"JFunkGaming",b:"Venomous Abyss Heroic-Mythic Boss Guides",d:"2026-08-12",u:"https://www.youtube.com/watch?v=o7lua5gr850"},
 rcp_nek:{l:"READY CHECK ",t:3,k:"creator",  a:"Ready Check Pull",b:"Nek'zali Guide",d:"2026-08-10",u:"https://www.youtube.com/watch?v=YBn4-mMBLs4"},
 rcp_pre:{l:"READY CHECK ",t:3,k:"creator",  a:"Ready Check Pull",b:"The Venomous Abyss All-Boss Preview",d:"2026-07-20",u:"https://www.youtube.com/watch?v=W2zNL31Ly-A"},
 wz_va  :{l:"WOW SO ZESTY",t:3,k:"creator",  a:"WoW So Zesty",b:"Venomous Abyss Heroic Raid Guide",d:"2026-08-12",u:"https://www.youtube.com/watch?v=Wpf2oTR2EOg"},
 iv_ts  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Neryssa)",b:"Midnight Season 2 Tier Sets Guide",d:"2026-08-06",u:"https://www.icy-veins.com/wow/midnight-season-2-tier-sets-guide"},
 tk_va  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Normal/Heroic Venomous Abyss Raid Guide (video)",d:"2026-08-13",u:"https://www.youtube.com/watch?v=L__7PvkXaoc"},
 tk_vtk :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Venomous Abyss Tank Tips for Normal and Heroic (video)",d:"2026-08-14",u:"https://www.youtube.com/watch?v=P-V2_kWBmP8"},
 tk_rt  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Pug-Friendly Mythic+ Routes for All Season 2 Dungeons",d:"2026-08-15",u:"https://www.youtube.com/watch?v=nZJi0Fdgl5Q"},
 tk_trk :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Season 2 Tank Trinket and Cantrip Gear Preview",d:"2026-06-27",u:"https://www.youtube.com/watch?v=2d3ebU0MuE8"},
 /* The first POST-LAUNCH source in the ledger. Everything else here was
    recorded before the season opened; this is a guild describing what week
    one actually did, which is why it outranks pre-launch theory wherever the
    two disagree — and it says so in the rows it touches. */
 tk_hero:{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Venomous Abyss Tips and Tricks for the Hardest Heroic Bosses (video, post-launch)",d:"2026-08-21",u:"https://www.youtube.com/watch?v=zL6NayUYepg"},
 /* New to this ledger, and treated accordingly: a tank-only walkthrough of
    all 28 encounters with its own footage. Where it is the ONLY source for a
    claim the text says so, and its two disagreements with Tactyks are filed
    as open questions rather than quietly resolved. */
 sha_tnk:{l:"SHA",t:3,k:"creator",  a:"Sha",b:"Tank Tips and Tricks for Dungeon Bosses, Mythic+ Season 2 (video)",d:"2026-08-18",u:"https://www.youtube.com/watch?v=pBrG9id-5OM"}
};

/* ═══ TAG VOCABULARIES ═══ icon + label. Colour is never the only cue. ═══ */
const TAGS={
 frontal:{l:"Frontal",i:"i-frontal"}, line:{l:"Line",i:"i-line"},
 tankbuster:{l:"Tank buster",i:"i-tank"}, soak:{l:"Soak",i:"i-soak"},
 spread:{l:"Spread",i:"i-spread"}, stack:{l:"Stack up",i:"i-stack"},
 dot:{l:"DoT",i:"i-drop"}, groupdmg:{l:"Group damage",i:"i-warn"},
 channel:{l:"Channel",i:"i-channel"}, knockback:{l:"Knockback",i:"i-knock"},
 knockup:{l:"Knock-up",i:"i-knock"}, fixate:{l:"Fixate",i:"i-dps"},
 adds:{l:"Adds",i:"i-add"}, totem:{l:"Totem",i:"i-add"},
 shield:{l:"Shield",i:"i-shield"}, enrage:{l:"Enrage",i:"i-enrage"},
 absorb:{l:"Heal absorb",i:"i-heal"}, healred:{l:"Healing reduced",i:"i-heal"},
 amp:{l:"Damage amp",i:"i-warn"}, debuff:{l:"Party debuff",i:"i-warn"},
 root:{l:"Root",i:"i-move"}, stun:{l:"Stun",i:"i-warn"}, fear:{l:"Fear",i:"i-warn"},
 silence:{l:"Silence",i:"i-kick"}, pacify:{l:"Pacify",i:"i-kick"},
 denial:{l:"Area denial",i:"i-drop"}, env:{l:"Environmental",i:"i-warn"},
 death:{l:"On death",i:"i-warn"}, heal:{l:"Enemy healing",i:"i-heal"},
 stacking:{l:"Stacking",i:"i-stack"}, mobility:{l:"Movement",i:"i-move"},
 myth:{l:"Mythic only",i:"i-warn"}, noarmor:{l:"Ignores armour",i:"i-tank"},
 oneshot:{l:"One-shot",i:"i-skull"}, wipe:{l:"Wipe",i:"i-skull"}
};
/* ═══ HOW BAD IS IT ═══════════════════════════════════════════════════════
   Two different questions, and the site used to answer half of one of them.

   SEVERITY grades COST: how much a single failure takes off you. It is now
   printed as a word and never as a bare number — "Severity 3" told a reader
   nothing they could act on, and because 1s and 2s were never rendered the
   scale looked like an in-joke with one member. Unmarked rows are level 1.

   LETHALITY is binary, orthogonal, and answers DOES IT KILL. Given a high
   enough key or a bad enough pull almost anything one-shots somebody, so the
   bar here is deliberately high and deliberately checkable: the ability's own
   sourced text has to say it kills a player outright, or ends the group. No
   inference from shape, no "this looks scary". A badge that quietly means
   "probably quite bad" is a badge nobody reads twice. ══════════════════════ */
const SEVS={
 1:["Chip","Costs health or uptime. Eating one is survivable."],
 2:["Punishing","Kills a careless player, or spends a cooldown. Repeated failures lose the run."],
 3:["Run-ender","One failure routinely ends the pull. Treat it as non-negotiable."]};
const LETHAL={
 oneshot:["One-shot","Kills the player outright when it lands. A bigger health bar is not the answer; the counter is."],
 wipe:["Wipe","Ends the whole group if it resolves. This is the cast runs are lost to."]};
const CTRS={
 interrupt:{l:"Interrupt",i:"i-kick"}, cc:{l:"CC the channel",i:"i-kick"},
 drop:{l:"Combat drop",i:"i-kick"}, purge:{l:"Purge",i:"i-dispel"},
 soothe:{l:"Soothe",i:"i-dispel"}, magic:{l:"Magic dispel",i:"i-dispel"},
 poison:{l:"Poison dispel",i:"i-dispel"}, curse:{l:"Curse dispel",i:"i-dispel"},
 disease:{l:"Disease dispel",i:"i-dispel"}, bleedcl:{l:"Bleed cleanse",i:"i-dispel"},
 freedom:{l:"Freedom",i:"i-move"}, immune:{l:"Immunity",i:"i-shield"},
 topoff:{l:"Heal to full",i:"i-heal"}, defensive:{l:"Defensive",i:"i-tank"},
 kite:{l:"Kite",i:"i-move"}, position:{l:"Positioning",i:"i-move"},
 stagger:{l:"Stagger kills",i:"i-dps"}, focus:{l:"Focus target",i:"i-dps"},
 preposition:{l:"Pre-position",i:"i-move"}, dodge:{l:"Dodge",i:"i-move"},
 unavoidable:{l:"Unavoidable",i:"i-warn"}, los:{l:"Line of sight",i:"i-shield"},
 spread:{l:"Spread out",i:"i-spread"}, stack:{l:"Stack up",i:"i-stack"},
 soak:{l:"Soak it",i:"i-soak"}, mobility:{l:"Movement ability",i:"i-move"}
};
const KINDS={boss:"Boss",mini:"Mini-boss",lt:"Lieutenant",trash:"Trash",caster:"Caster",fodder:"Fodder"};

/* ═══ SEASON FACTS ═══ Blizzard-sourced: patch notes and live client ═══ */
const SEASON={
 opens:"2026-08-18", opensLocal:"Tue 18 Aug, 08:00 PDT in the Americas · Wed 19 Aug in Europe · Wed 19 Aug, ~01:00 AEST on Oceanic realms, which run the Americas reset",
 patch:'12.1 "The Curse of Ula\'tek"', patchLive:"2026-08-11",
 affixes:[
  {k:"+2 to +4",  a:"Lindormi's Guidance",  d:"New onboarding affix. Softens deaths, teaches routes and enemy-forces counts.",s:["bz_game","iv_ov"]},
  {k:"+5 to +11", a:"Xal'atath's Bargain",  d:"One of four, rotating weekly: Ascendant, Voidbound, Pulsar, Devour. Only one Bargain is live per week.",s:["bz_game","iv_ov"]},
  {k:"+7 to +10", a:"Fortified / Tyrannical",d:"The two rotate weekly in this band.",s:["bz_game","iv_ov"]},
  {k:"+10 and up",a:"Fortified and Tyrannical",d:"Both, every week.",s:["bz_game","iv_ov"]},
  {k:"+12 and up",a:"Xal'atath's Guile",     d:"Replaces all Bargains. Deaths substantially more punishing, rewarding safer play and coordinated defensives.",s:["bz_game","iv_ov"]}
 ],
 rewards:[
  {k:"+2 / +3",   e:"295",v:"305"},{k:"+4",e:"298",v:"308"},{k:"+5",e:"302",v:"308"},
  {k:"+6",        e:"305",v:"311"},{k:"+7",e:"305",v:"315"},{k:"+8 / +9",e:"308",v:"315"},
  {k:"+10 and up",e:"311",v:"318"}
 ],
 rewardVerified:true,
 rewardNote:"Rewards flatten at +10 — a +10 and a +20 award identical gear. Breath of Blight at 2,000 rating (Keystone Master); Breath of Ruin at 3,000 (Keystone Legend). Dungeon teleports at a timed +10 each. Keystone Master also grants Serpent Scion, which unlocks additional tier-set visual effects and is otherwise obtainable from Heroic or Mythic Ula'tek.",
 mounts:"The Writhing Brood drops from Zul'jan in Altar of Fangs on Mythic or Mythic+.",
 where:[{n:"Mythic+ portal room",d:"Through the golden Timeways portal at 53.3, 66.1 in Silvermoon City. Lindormi and Agmera stand beside it. Holds portals to the Season 2 dungeons that are not current Midnight content.",s:["iv_ov"]},
        {n:"Gear upgrades",d:"Cuzolth, the item upgrade vendor, at 48.3, 61.7 in Silvermoon City, with Vaskarn the crest exchange alongside.",s:["iv_ov"]},
        {n:"Season length",d:"Runs to the end of the 12.1 patch cycle, expected to be roughly six months.",s:["iv_ov"]}]
};

/* ═══ CONTESTED — rendered wherever the claim appears ═══ */
const DISPUTES=[
 {id:"kr-count",q:"Does King's Rest still require 100% trash count?",
  a:{p:"Yes — every mob in the instance, believed to be a first for the format.",s:["bz_game"]},
  b:{p:"Relaxed late in the PTR. A 15 Aug routing video says the requirement changed and demonstrates a route leaving two packs unpulled that still makes count; Wowhead separately reported PTR dungeon tuning that removed some King's Rest trash. Note these are not the same claim — removing trash does not by itself relax a 100% requirement.",s:["tk_rt","wh_dt"]},
  extra:"A written dungeon overview dated 11-12 Aug states flatly that you must pull every mob. That is a steadier kind of source than a video and it strengthens Position A — but it PREDATES the routing video by three or four days, so it cannot rebut a claim about a later change. Date order matters more than pedigree here.",
  r:"Open the key and check whether count completes with a pack skipped. This is now the oldest open question in the compendium and the cheapest to answer.",dg:"kings-rest"},
 {id:"don-piles",q:"Which Hoardmonger pile do you feed him first — meat or bone?",
  a:{p:"Meat first, then bone. The meat empowerment adds a knockback to his bellow, which is annoying rather than dangerous, so it is the cheapest thing to carry for the longest time.",s:["tk_don"]},
  b:{p:"Bone first, then meat. The bone empowerment only adds spikes to a frontal you are already dodging, while the meat knockback keeps launching the group away from the soaks it needs to reach.",s:["sha_tnk"]},
  extra:"Both agree completely on the third: mushrooms LAST, because that pile also multiplies how many mushrooms he throws and the soak volume is what actually overwhelms a group. The argument is only about which of the other two is cheaper to carry, and each side reasons from the mechanic it finds more disruptive rather than from measurement. A tank holding him against terrain refuses the meat knockback outright, which may dissolve the question entirely for some groups.",
  r:"Run it both ways at the same key level and compare damage taken across the two long stretches.",dg:"den-of-nalorakk"},
 {id:"vsa-cascade",q:"Is Void Cascade a tank soak?",
  a:{p:"No, emphatically — it is not a soak at all. The targeted player runs out and strafes. It prefers ranged DPS and falls to healers only if no ranged are alive, and a tank standing in it is spending health nobody asked for.",s:["sha_tnk"]},
  b:{p:"Some groups have the tank soak it, and it works.",s:["tk_tech"]},
  extra:"Both describe the same projectile, so this is not a disagreement about the mechanic — it is about whether spending tank health to save a ranged player some movement is a trade worth making. Worth recording because both sources report groups getting angry at tanks, in opposite directions. Everyone agrees it can be dropped with a combat drop, which costs neither.",
  r:"Compare a soaking tank's damage taken against the uptime a kiting ranged player actually loses. Until someone measures it this is a preference dressed as a rule.",dg:"voidscar-arena"},
 {id:"vsa-buff",q:"How much Versatility does the Voidscar left path grant?",
  a:{p:"5% Versatility, from Proof of Endurance.",s:["tk_vsa"]},
  b:{p:"3% Versatility.",s:["tk_rt"]},
  r:"Read the buff tooltip after killing the left mini-boss. Same author, two weeks apart, unexplained.",dg:"voidscar-arena"},
 {id:"bv-freedom",q:"Is the Blinding Vale tank dot removable by Freedom effects?",
  a:{p:"Yes — the Four-Spined magic dot can be cleared by magic dispel or by freedom effects.",s:["tk_bv"]},
  b:{p:"No — a magic dot and slow on the tank in Blinding Vale is not removed by freedoms, possibly a missing ability flag.",s:["tk_pool"]},
  r:"May be two different abilities rather than a contradiction. Test on the lasher packs.",dg:"blinding-vale"},
 {id:"bv-pulverize",q:"Can you dodge Lightwarden Ruia's Pulverizing Strikes?",
  a:{p:"Yes — move the moment you are marked, and leave room for untargeted players to get out.",s:["tk_bv"]},
  b:{p:"No — the cones lock onto the player, so there is no dodging them. Stand still when it is on you and rely on being spread.",s:["wh_dg"]},
  r:"The Encounter Journal says he marks targets and launches a wave toward each, which reads closer to a lock-on. If the written guide's reading is right, the creator advice actively hurts you — running drags the cone across allies. Watch one cast before deciding.",dg:"blinding-vale"},
 {id:"vsa-path",q:"Which Voidscar Arena path should you take?",
  a:{p:"Left, for Proof of Endurance. The Versatility buff is generally more beneficial, and the harder left-side mini-boss is worth it for most groups.",s:["tk_vsa"]},
  b:{p:"Right, for Proof of Mastery — described as a powerful dungeon buff that speeds the run up, against Proof of Endurance being called not-so-great. Explicitly framed as a call about current tuning.",s:["iv_vsa"]},
  r:"The written guide's position is six days later and post-patch, which usually settles it. But the two are arguing about buff value, not a fact, and Proof of Mastery scales with your spec's mastery modifier — so the right answer may genuinely differ by group composition. Read the tooltips and decide for your comp.",dg:"voidscar-arena"},
 {id:"bv-side",q:"Which side of Blinding Vale should a pug take?",
  a:{p:"Left. The Light-Starved Blossom buff is the better of the two and the trash composition looks slightly easier.",s:["tk_bv"]},
  b:{p:"Right. The left side has considerably more interrupts and an extra Sporeblight Belcher; the right side's bolt-casters can be safely ignored once packs are grouped.",s:["tk_rt"]},
  r:"Same author reversed between 2 Aug and 15 Aug. The later position is the routing-specific one.",dg:"blinding-vale"},
 {id:"va-helical",q:"How does Helical Toxins actually count to four?",
  a:{p:"Colliding with other players merges your linked-orb counts, and the merged total must equal exactly four; on Heroic an overfilled merge kills outright.",s:["iv_sen"]},
  b:{p:"Every player carries four orbs, some red and some green, and you touch exactly one partner so the combined GREEN orbs equal four; failures take Cultivated Burst, which an immunity survives.",s:["me_sen"]},
  extra:"A third description — stacking venom potency by touch until it reads exactly four — comes from a guide whose fight descriptions are Mythic-based by its own note, so it may simply be the Mythic variant. Tactyks' PTR footage shows position A's arithmetic: one-two-three stacks colliding to a merged four, with ample time. A fourth creator describes the same stacks model, with overfill granting a marked debuff that drops a massive pool when it expires.",
  r:"One combat log of the intermission on Normal or Heroic settles the counting rule.",dg:"raid"},
 {id:"va-ignition",q:"What shape is Soulcoil Ignition — five stacks at once, or four Rites in sequence?",
  a:{p:"The cast applies five stacks of Soulcoil Rite to every player, with Ritual Burn arriving alongside on Heroic.",s:["iv_nek"]},
  b:{p:"The cast is effectively four Soulcoil Rites in a row — sequential raid hits — with the echoes raining out of the Well during the channel.",s:["me_nek"]},
  r:"Materially different healing assignments; the first live log answers it.",dg:"raid"},
 {id:"va-livingvenom",q:"Where does Living Venom on the Sentinels come from?",
  a:{p:"A Heroic effect of destroyed Toxic Droplets: the freed venom travels back toward Breath of Ula'tek and damages everyone on the path.",s:["iv_sen"]},
  b:{p:"A mini frontal from the boss that fires green lines outward which then return — dodged on the way out and again on the way back.",s:["me_sen"]},
  extra:"Tactyks' footage supports A's geometry: the venom travels from wherever the droplet was soaked back to the green golem, even from across the room. Another source splits the difference — venom lands around the room, then fires toward the boss — which is still A's family, not B's.",
  r:"Watch one pull of the green golem. The answer changes where the melee stand.",dg:"raid"},
 {id:"va-amani-cc",q:"Can the Restless Amani be controlled while their shield holds?",
  a:{p:"No — while the shield is up they cannot be stopped, only stripped: break it with magic damage first.",s:["iv_sen","iv_nek"]},
  b:{p:"Yes — grips, taunts and slows all land through the shield; the shield only gates damage, not control. A second creator agrees, calling grips, slows and stuns necessary, and notes the shield covers only a fraction of their health.",s:["tk_va","tk_vtk","rcp_nek","jf_va"]},
  r:"One Death Grip on a shielded add answers it. If B is right, kiting is a whole extra tool on this boss.",dg:"raid"},
 {id:"va-barrage-count",q:"How many spirits does Possession Barrage fire?",
  a:{p:"Four spirits, each detonating on its first body.",s:["me_nek"]},
  b:{p:"Five — stated twice, and five stacks of Hollowing Strikes land on the victim to match.",s:["tk_va","tk_vtk"]},
  r:"Count them on the first pull. It changes the healing plan by exactly one spirit.",dg:"raid"},
 {id:"va-clot-cc",q:"Are the Splitting Clot's later generations controllable?",
  a:{p:"The first blob is immune but the split generations can be slowed and controlled.",s:["iv_vas","wg_va"]},
  b:{p:"Every generation is CC-immune — the PTR bugs made it look otherwise, but immunity is the intent. Method's video agrees: crowd-control immune, splits when killed, keep killing until every piece is gone.",s:["tk_va","me_vas"]},
  r:"First live pull of the Blood fountain settles it, and the add-handling plan hangs on the answer.",dg:"raid"},
 {id:"va-feed-order",q:"Which Explorer do you feed the fish first?",
  a:{p:"Gebbo, then Nama, then Iku — clear the easiest ultimate early and bank the hard one for a practiced raid.",s:["iv_exp","tk_va"]},
  b:{p:"Iku, then Nama, then Gebbo — Frostfire Volley is the ultimate that wipes raids, so detonate it while everything else is calm.",s:["me_exp"]},
  r:"Not a fact dispute — a strategy fork. Both clear; pick by which ultimate your raid fumbles. Early logs will crown a consensus.",dg:"raid"},
 {id:"va-entrance",q:"Where exactly is the raid entrance inside the Vaults?",
  a:{p:"In the centre of the area — /way #2509 47.11 28.30.",s:["iv_va"]},
  b:{p:"Head north once inside — /way #2509 47.2 21.7.",s:["wg_va"]},
  r:"Someone walks in on day one. The waypoints differ by seven points of map, which is a real walk.",dg:"raid"}
];

/* ═══ RESOLVED — kept for the record, never left in the live list above ═══ */
const RESOLVED=[
 {id:"rlp-phase",q:"At what health does Kyrakka join Erkhart Stormvein?",
  won:"40%",by:["wh_ej"],
  p:"The creator guide said 40%, the written guide said 50%. The Encounter Journal says Kyrakka lands when EITHER of them reaches 40% — so the creator was right, and both guides missed that the threshold applies to whichever boss hits it first.",d:"2026-08-16"},
 {id:"aof-axes",q:"Can Axegrinder be used to clear Ritual Venom stacks?",
  won:"Yes",by:["wh_ej"],
  p:"The creator guide treated the axes purely as something to dodge; the written guide offered them as a second way to clear stacks. The journal settles it: Bloodletting triggers on Zul'jan's Physical abilities, and Axegrinder is Physical. It is a real second option — and useful, because Boneslicer only targets one player at a time.",d:"2026-08-16"}
];
/* ═══ IMAGERY ═══ optimised WebP, embedded so the file stays self-contained.
   Boss portraits carry the in-game nameplate, which makes them evidence as well as decoration. */
const IMG={
/* Keyed by banner/capture name; values are paths under assets/img/.
   These were inline base64 until 2026-08-17 — 703 KB, 68% of the payload,
   all blocking first paint. Loose files are cached per-file, fetched in
   parallel, and lazy-loaded, so a page pulls only what it shows — the same
   reasoning assets/icons already documents. The bytes are the originals,
   decoded not recompressed. */
"altar-of-fangs":"assets/img/altar-of-fangs.webp",
"aof-ravi":"assets/img/aof-ravi.webp",
"aof-the-writhing-coil":"assets/img/aof-the-writhing-coil.webp",
"aof-zuljan":"assets/img/aof-zuljan.webp",
"den-of-nalorakk":"assets/img/den-of-nalorakk.webp",
"don-nalorakk":"assets/img/don-nalorakk.webp",
"don-sentinel-of-winter":"assets/img/don-sentinel-of-winter.webp",
"don-the-hoardmonger":"assets/img/don-the-hoardmonger.webp",
"kings-rest":"assets/img/kings-rest.webp",
"kr-king-dazar":"assets/img/kr-king-dazar.webp",
"kr-mchimba-the-embalmer":"assets/img/kr-mchimba-the-embalmer.webp",
"kr-the-council-of-tribes":"assets/img/kr-the-council-of-tribes.webp",
"kr-the-golden-serpent":"assets/img/kr-the-golden-serpent.webp",
"mr-kystia-manaheart":"assets/img/mr-kystia-manaheart.webp",
"mr-lithiel-cinderfury":"assets/img/mr-lithiel-cinderfury.webp",
"mr-xathuux-the-annihilator":"assets/img/mr-xathuux-the-annihilator.webp",
"mr-zaen-bladesorrow":"assets/img/mr-zaen-bladesorrow.webp",
"murder-row":"assets/img/murder-row.webp",
"rlp-kokia-blazehoof":"assets/img/rlp-kokia-blazehoof.webp",
"rlp-kyrakka-and-erkhart":"assets/img/rlp-kyrakka-and-erkhart.webp",
"rlp-melidrussa":"assets/img/rlp-melidrussa.webp",
"ruby-life-pools":"assets/img/ruby-life-pools.webp",
"tbv-ikuzz":"assets/img/tbv-ikuzz.webp",
"tbv-lightblossom-trinity":"assets/img/tbv-lightblossom-trinity.webp",
"tbv-lightwarden-ruia":"assets/img/tbv-lightwarden-ruia.webp",
"tbv-ziekket":"assets/img/tbv-ziekket.webp",
"temple-of-sethraliss":"assets/img/temple-of-sethraliss.webp",
"the-blinding-vale":"assets/img/the-blinding-vale.webp",
"va-atroxus":"assets/img/va-atroxus.webp",
"va-charonus":"assets/img/va-charonus.webp",
"va-tazrah":"assets/img/va-tazrah.webp",
"voidscar-arena":"assets/img/voidscar-arena.webp",
/* Dungeon-journal model portraits, owner-captured 2026-08-18. Cropped to the
   parchment panel; the in-image nameplate is trimmed because the site prints
   the name beside the figure. */
"j-adderis":"assets/img/j-adderis.jpg",
"j-aspix":"assets/img/j-aspix.jpg",
"j-avatar-of-sethraliss":"assets/img/j-avatar-of-sethraliss.jpg",
"j-first-mate-nama":"assets/img/j-first-mate-nama.jpg",
"j-galvazzt":"assets/img/j-galvazzt.jpg",
"j-hex-lord-malacrass":"assets/img/j-hex-lord-malacrass.jpg",
"j-ithraz":"assets/img/j-ithraz.jpg",
"j-merektha":"assets/img/j-merektha.jpg",
"j-morzahi":"assets/img/j-morzahi.jpg",
"j-nekzali":"assets/img/j-nekzali.jpg",
"j-scrollsage-iku":"assets/img/j-scrollsage-iku.jpg",
"j-sszorak":"assets/img/j-sszorak.jpg",
"j-trader-gebbo":"assets/img/j-trader-gebbo.jpg",
"j-ulatek":"assets/img/j-ulatek.jpg",
"j-vashnik":"assets/img/j-vashnik.jpg",
"j-vexhul":"assets/img/j-vexhul.jpg",
"j-zuljan-raid":"assets/img/j-zuljan-raid.jpg",
/* Mythic Dungeon Tools maps, owner-captured 2026-08-18 — every pack and boss
   chip marked. Cropped to the map panel; served at 1800px, click-through
   opens the file itself for native zoom. */
"mdt-altar-of-fangs":"assets/img/mdt-altar-of-fangs.webp",
"mdt-blinding-vale":"assets/img/mdt-blinding-vale.webp",
"mdt-den-of-nalorakk":"assets/img/mdt-den-of-nalorakk.webp",
"mdt-kings-rest":"assets/img/mdt-kings-rest.webp",
"mdt-murder-row":"assets/img/mdt-murder-row.webp",
"mdt-ruby-life-pools":"assets/img/mdt-ruby-life-pools.webp",
"mdt-temple-of-sethraliss":"assets/img/mdt-temple-of-sethraliss.webp",
"mdt-voidscar-arena":"assets/img/mdt-voidscar-arena.webp",
/* The full M+ plate set, 2026-08-18 — the journal look is the house style
   for boss media now; the owner's captures remain on disk and in IMG. */
"j-akaali":"assets/img/j-akaali.jpg",
"j-atroxus":"assets/img/j-atroxus.jpg",
"j-charonus":"assets/img/j-charonus.jpg",
"j-erkhart-stormvein":"assets/img/j-erkhart-stormvein.jpg",
"j-golden-serpent":"assets/img/j-golden-serpent.jpg",
"j-hoardmonger":"assets/img/j-hoardmonger.jpg",
"j-kezkitt":"assets/img/j-kezkitt.jpg",
"j-king-dazar":"assets/img/j-king-dazar.jpg",
"j-kokia-blazehoof":"assets/img/j-kokia-blazehoof.jpg",
"j-kula":"assets/img/j-kula.jpg",
"j-kyrakka":"assets/img/j-kyrakka.jpg",
"j-kystia-manaheart":"assets/img/j-kystia-manaheart.jpg",
"j-lekshi":"assets/img/j-lekshi.jpg",
"j-lightwarden-ruia":"assets/img/j-lightwarden-ruia.jpg",
"j-lithiel-cinderfury":"assets/img/j-lithiel-cinderfury.jpg",
"j-mchimba":"assets/img/j-mchimba.jpg",
"j-meittik":"assets/img/j-meittik.jpg",
"j-melidrussa":"assets/img/j-melidrussa.jpg",
"j-nalorakk":"assets/img/j-nalorakk.jpg",
"j-ravi":"assets/img/j-ravi.jpg",
"j-sentinel-of-winter":"assets/img/j-sentinel-of-winter.jpg",
"j-tazrah":"assets/img/j-tazrah.jpg",
"j-writhing-coil":"assets/img/j-writhing-coil.jpg",
"j-xathuux":"assets/img/j-xathuux.jpg",
"j-zaen-bladesorrow":"assets/img/j-zaen-bladesorrow.jpg",
"j-zanazal":"assets/img/j-zanazal.jpg",
"j-ziekket":"assets/img/j-ziekket.jpg",
"j-zuljan":"assets/img/j-zuljan.jpg"
};

/* ═══════════════════════════════════════════════════════════════════════
   DATA · DUNGEONS
   Ability shape: n name · t tags · c counters · r roles · sev 1–3
                  e effect (FACT) · h handling (READ, opinion) · s sources
   ═══════════════════════════════════════════════════════════════════════ */

/* ═══ CLASS AND SPEC ICONS ══════════════════════════════════════
   Blizzard's own class and specialisation icons, keyed the same way ICONS is
   and served from assets/icons/ so the page makes no third-party request.
   Every slug was verified against the CDN — a wrong one 404s.

   One stand-in, marked because it is one: Demon Hunter's Devourer is new in
   Midnight and Wowhead publishes no spec icon for it, so it borrows the icon
   of Devourer Bite, its own signature ability. Replace it the day a real spec
   icon exists.
   ═════════════════════════════════════════════════════════════════════ */
const CLASSICON={
"Warrior":"classicon_warrior","Paladin":"classicon_paladin","Hunter":"classicon_hunter",
"Rogue":"classicon_rogue","Priest":"classicon_priest","Death Knight":"classicon_deathknight",
"Shaman":"classicon_shaman","Mage":"classicon_mage","Warlock":"classicon_warlock",
"Monk":"classicon_monk","Druid":"classicon_druid","Demon Hunter":"classicon_demonhunter",
"Evoker":"classicon_evoker"
};
const SPECICON={
"Warrior/Arms":"ability_warrior_savageblow",
"Warrior/Fury":"ability_warrior_innerrage",
"Warrior/Protection":"ability_warrior_defensivestance",
"Paladin/Holy":"spell_holy_holybolt",
"Paladin/Protection":"ability_paladin_shieldofthetemplar",
"Paladin/Retribution":"spell_holy_auraoflight",
"Hunter/Beast Mastery":"ability_hunter_bestialdiscipline",
"Hunter/Marksmanship":"ability_hunter_focusedaim",
"Hunter/Survival":"ability_hunter_camouflage",
"Rogue/Assassination":"ability_rogue_eviscerate",
"Rogue/Outlaw":"inv_sword_30",
"Rogue/Subtlety":"ability_stealth",
"Priest/Discipline":"spell_holy_powerwordshield",
"Priest/Holy":"spell_holy_guardianspirit",
"Priest/Shadow":"spell_shadow_shadowwordpain",
"Death Knight/Blood":"spell_deathknight_bloodpresence",
"Death Knight/Frost":"spell_deathknight_frostpresence",
"Death Knight/Unholy":"spell_deathknight_unholypresence",
"Shaman/Elemental":"spell_nature_lightning",
"Shaman/Enhancement":"spell_shaman_improvedstormstrike",
"Shaman/Restoration":"spell_nature_magicimmunity",
"Mage/Arcane":"spell_holy_magicalsentry",
"Mage/Fire":"spell_fire_firebolt02",
"Mage/Frost":"spell_frost_frostbolt02",
"Warlock/Affliction":"spell_shadow_deathcoil",
"Warlock/Demonology":"spell_shadow_metamorphosis",
"Warlock/Destruction":"spell_shadow_rainoffire",
"Monk/Brewmaster":"spell_monk_brewmaster_spec",
"Monk/Mistweaver":"spell_monk_mistweaver_spec",
"Monk/Windwalker":"spell_monk_windwalker_spec",
"Druid/Balance":"spell_nature_starfall",
"Druid/Feral":"ability_druid_catform",
"Druid/Guardian":"ability_racial_bearform",
"Druid/Restoration":"spell_nature_healingtouch",
"Demon Hunter/Havoc":"ability_demonhunter_specdps",
"Demon Hunter/Vengeance":"ability_demonhunter_spectank",
"Demon Hunter/Devourer":"inv_12_dh_void_ability_devourerbite",
"Evoker/Devastation":"classicon_evoker_devastation",
"Evoker/Preservation":"classicon_evoker_preservation",
"Evoker/Augmentation":"classicon_evoker_augmentation"
};

/* ═══ ABILITY ICONS ══════════════════════════════════════════════════════
   Ability name → Blizzard icon slug, resolved against Wowhead's spell
   database. Files live in assets/icons/<slug>.jpg. 287 of the 329 ability
   names in DUNGEONS resolved to a spell of exactly that name; the other 42
   were each queried and none is a spell — three are adds filed into ability
   arrays, the rest structural notes or content Wowhead has no entry for. A name that
   is absent here simply renders without an icon — never a broken image.
   ═══════════════════════════════════════════════════════════════════════ */
const ICONS={
"Accumulate Charge":"spell_chargepositive",
"Addle Mind":"spell_shadow_mindflay",
"Ancestral Fury":"spell_totem_wardofdraining",
"Apex Predator":"ability_hunter_aspectoftheviper",
"Arc Lightning":"spell_nature_chainlightning",
"Arrow Barrage":"inv_misc_ammo_arrow_05",
"Awaken the Lightbloom":"inv_desertlasherorchid_yellow",
"Awakening Slam":"spell_necro_deathsdoor",
"Axe Toss":"ability_warrior_titansgrip",
"Axegrinder":"ability_warrior_bladestorm",
"Back to Work":"inv_hammer_09",
"Barrel Through":"ability_monk_clashingoxcharge",
"Bedrock Slam":"spell_nature_earthquake",
"Belch Spores":"spell_nature_corrosivebreath",
"Bestial Wrath":"ability_druid_ferociousbite",
"Blade Combo":"ability_ironmaidens_bladerush",
"Blade Dance":"ability_demonhunter_bladedance",
"Blaze of Glory":"inv_ember",
"Blazing Rush":"spell_deathknight_butcher2",
"Blighted Blood":"spell_shadow_lifedrain",
"Blink Nova":"spell_arcane_blink",
"Blood Sacrifice":"ability_warrior_bloodfrenzy",
"Bloodletting":"ability_skeer_bloodletting",
"Bloodthirsty Axe":"spell_druid_bloodythrash",
"Bloodthirsty Gaze":"ability_fixated_state_red",
"Bloodthorn Roots":"inv_-misc_herb_marrowroot_leaf",
"Bloodvenom Injection":"ability_warrior_bloodbath",
"Boneslicer":"ability_hunter_swiftstrike",
"Bound by Shadow":"spell_shadow_summonvoidwalker",
"Brutal Slams":"ability_warrior_decisivestrike",
"Brutalize":"ability_warrior_devastate",
"Bullet Seeds":"spell_shaman_convection",
"Burning Corruption":"spell_fire_blueflamebreath",
"Burnout":"spell_fire_soulburn",
"Call of the Elements":"ability_shaman_echooftheelements",
"Call of the Serpent":"8125100",
"Catalytic Bile":"inv_ability_poison_missile",
"Caustic Deluge":"inv_ability_poison_beam",
"Caustic Stomp":"inv_ability_poison_nova",
"Caustic Waves":"inv_ability_poison_wave",
"Champion Spear":"inv_ability_warrior_championsspear",
"Chaos Barrage":"spell_fire_felrainoffire",
"Chaos Bolt":"ability_warlock_chaosbolt",
"Chillstorm":"spell_shadow_soulleech_2",
"Chop Down":"ability_criticalstrike",
"Circling Prey":"inv_offhand_1h_ulatek_d_01",
"Coiling Ichor":"ability_ironmaidens_whirlofblood",
"Cold Claws":"ability_mage_wintersgrasp",
"Concussive Slam":"ability_warrior_decisivestrike",
"Corroding Spittle":"inv_fabric_felcloth_ebon",
"Corroding Venom":"ability_druid_infectedwound",
"Corrosive Essence":"inv_ability_poison_orb",
"Corrosive Fangs":"spell_nature_nullifypoison",
"Cosmic Crash":"inv_cosmicvoid_groundsate",
"Crushing Smash":"spell_shaman_earthquake",
"Curse of Doom":"spell_shadow_auraofdarkness",
"Cytotoxin":"ability_hunter_cobrastrikes",
"Dark Bloom":"inv_ability_voidweaverpriest_entropicrift",
"Dark Pact":"spell_shadow_deathpact",
"Dark Revelation":"ability_priest_clarityofpower",
"Dark Waves":"inv_cosmicvoid_wave",
"Death Rattle":"inv_sonic_debuff",
"Deathly Roar":"ability_hunter_beastmastery",
"Debilitating Backhand":"inv_relics_totemofrage",
"Deep Corruption":"priest_icon_chakra_red",
"Defiled Slam":"spell_fire_felimmolation",
"Defiling Taint":"ability_creature_disease_05",
"Demonic Frenzy":"spell_fel_incinerate",
"Demonic Rage":"ability_warlock_demonicempowerment",
"Demoralizing Shout":"ability_warrior_warcry",
"Devour":"inv_12_dh_void_ability_devourerbite",
"Dig In":"ability_ghoulfrenzy",
"Dimensional Shred":"ability_rogue_masterofsubtlety",
"Dismember":"ability_criticalstrike",
"Disorienting Screech":"inv_111_hunter_ability_harrierscall",
"Drain Fluids":"inv_misc_volatilewater",
"Drain Life":"spell_shadow_lifedrain02",
"Dreadmarch":"spell_nzinsanity_fearofdeath",
"Dripping Fangs":"ability_creature_poison_01",
"Earthbound's Imprint":"inv_ore_blackrock_ore",
"Earthquake":"spell_shaman_earthquake",
"Earthshatter Slam":"spell_shaman_earthquake",
"Echoing Maul":"inv_ability_druidoftheclawdruid_ravage",
"Empowering Slam":"inv_mace_1h_pvppandarias3_c_01",
"Empowerment":"spell_nature_elementalprecision_1",
"Entomb":"achievement_bg_xkills_avgraveyard",
"Envenom":"ability_rogue_disembowel",
"Essence Disruption":"inv_elemental_mote_shadow01",
"Essence Rend":"spell_necro_deathall",
"Eternal Nightfall":"spell_shadow_twilight",
"Eternal Venom":"spell_nature_nullifypoison",
"Evolve":"inv_121_trinket_raid_ulatek_heart",
"Excavating Blast":"spell_nature_earthquake",
"Exploding Infection":"spell_fire_incinerate",
"Explosive Surprise":"inv_misc_bomb_01",
"Eye Beam":"ability_demonhunter_eyebeam",
"Fangs of the Coiled Altar":"spell_nature_poisoncleansingtotem",
"Feast of Misery":"spell_shadow_lifedrain02_purple",
"Fel Beam":"spell_fire_felflamestrike",
"Fel Missiles":"spell_fire_felrainoffire",
"Fel Nova":"spell_fire_felflamering",
"Fel Rage":"ability_creature_felfrenzy",
"Felshield":"spell_fire_felfireward",
"Fel Spray":"spell_fire_felflamebreath",
"Fel Steps":"ability_bossfellord_felfissure",
"Felfire Burst":"spell_fire_felflamebolt",
"Feral Rage":"artifactability_feraldruid_ashamanesbite",
"Ferocious Leap":"ability_heroicleap",
"Fingers of Gul'dan":"ability_warlock_handofguldan",
"Fire Bomb":"inv_eng_bombfire",
"Fire Maw":"ability_warrior_dragonroar",
"Fixate":"ability_fixated_state_blue",
/* Flame Dance is a real spell (354318) that Blizzard shipped without art —
   trade_engineering is Wowhead's own icon for it, so this entry is accurate
   rather than a placeholder, even though it renders like one. */
"Flame Dance":"trade_engineering",
"Flame Shock":"spell_fire_flameshock",
"Flay":"inv_archaeology_70_demon_flayedskinchronicle",
"Forceful Slam":"inv_misc_bearpaw_red",
"Forked Lightning":"spell_lightning_lightningbolt01",
"Frantic Blooming":"inv_desertlasherorchid_yellow",
"Frigid Roar":"inv_amanibearmount_witherbark",
"Frigid Shard":"spell_frost_iceshard",
"Frost Bite":"ability_mage_coldasice",
"Frost Overload":"spell_fire_blueflamering",
"Frost Shock":"spell_frost_frostshock",
"Frostfire Volley":"spell_fire_firebolt02",
"Frozen Tempest":"spell_frost_ring-of-frost",
"Fury of the War God":"spell_nature_shamanrage",
"Gale Force":"ability_skyreach_four_wind",
"Galvanized":"spell_shaman_staticshock",
"Gilded Destruction":"inv_sword_2h_zandalarquest_b_01",
"Glacial Tomb":"ability_mage_coldasice",
"Glacial Torment":"inv12_apextalent_mage_handoffrost",
"Glaive Toss":"ability_upgrademoonglaive",
"Gloombomb":"spell_shadow_shadowfury",
"Gravitic Orbs":"inv_enchant_voidsphere",
"Grievous Gash":"inv_ability_druidoftheclawdruid_ravage",
"Grievous Thrash":"spell_druid_bloodythrash",
"Ground Pound":"ability_smash",
"Guillotine":"inv_121_trinket_raid_ulatek_trolltablet",
"Hailburst":"spell_frost_frostshock",
"Harsh Winds":"spell_nature_earthbind",
"Head Bash":"inv_fellessergronnmount",
"Healing Breeze":"spell_frost_windwalkon",
"Healing Tide Totem":"ability_shaman_healingtide",
"Health Funnel":"spell_shadow_lifedrain",
"Heartstop Poison":"ability_boss_kilrogg_heartseeker",
"Heavy Slams":"inv_11_arenaboss_conductionslam",
"Helical Toxins":"inv_112_warlock_bloodstone",
"Hex":"spell_shaman_hex",
"Hex Volley":"warlock_curse_shadow",
"Hollowing Strikes":"warlock_spelldrain",
"Howling Maelstrom":"spell_nature_cyclone",
"Hulking Claw":"ability_creature_poison_03",
"Hungering Pyre":"ability_mage_livingbomb",
"Hunting Leap":"ability_druid_ravage",
"Ice Shield":"ability_mage_coldasice",
"Icebolt":"spell_frost_frostbolt02",
"Icebound Flames":"ability_mage_frostfirebolt",
"Imbibe":"spell_nature_poisoncleansingtotem",
"Imbued Conduction":"spell_nature_stormreach",
"Induction":"ability_thunderking_overcharge",
"Infernal Crash":"spell_shadow_summoninfernal",
"Inferno":"ability_warlock_inferno",
"Inferno Spit":"spell_fire_firebolt",
"Infest":"ability_hunter_snaketrap",
"Insidious Aura":"ability_warlock_burningembersgreen",
"Invoke":"warrior_disruptingshout",
"Killing Spree":"inv_112_rogue_betweentheeyes",
"Laced Edge":"inv_sword_2h_ulatek_d_01",
"Latent Hex":"inv_shoulder_armor_hextroll_d_01",
"Legion Strike":"inv_axe_09",
"Light Bolt":"spell_holy_holybolt",
"Light Bolt Volley":"ability_priest_flashoflight",
"Lightfire":"inv_ability_holyfire_buff",
"Lightbloom Pollination":"spell_holy_surgeoflight",
"Lightbloom's Essence":"inv_ability_holyfire_orb",
"Lightblossom Beam":"ability_paladin_infusionoflight",
"Lightfall":"inv_ability_holyfire_missile",
"Lightning Bite":"ability_thunderking_balllightning",
"Lightning Bolt":"spell_nature_lightning",
"Lightning Rod":"inv_rod_enchantedcobalt",
"Lightning Torrent":"spell_shaman_thunderstorm",
"Living Bomb":"ability_mage_livingbomb",
"Lucre's Call":"spell_holy_purifyingpower",
"Mad Shriek":"spell_shadow_psychicscream",
"Maelstrom":"spell_nature_unrelentingstorm",
"Magma Totem":"spell_fire_selfdestruct",
"Malefic Wave":"ability_felarakkoa_feldetonation_green",
"Malignant Burst":"ability_rogue_deviouspoisons",
"Mark of Acid":"inv_arcanegolem2mount_green",
"Mass Envenom":"inv_ability_poison_missile",
"Melt Armor":"spell_fire_firebolt02",
"Mending Void":"inv_cosmicvoid_buff",
"Mighty Thud":"sha_ability_rogue_bloodyeye_nightmare",
"Mirror Images":"spell_magic_lesserinvisibilty",
"Molten Blood":"spell_shaman_spewlava",
"Molten Boulder":"spell_mage_flameorb",
"Monstrous Roar":"ability_racial_darkflight",
"Mother's Wrath":"inv_misc_monsterfang_02",
"Nether Dash":"ability_mount_voidelfstridermount",
"Noxious Breath":"ability_creature_poison_05",
"Noxious Spray":"inv_ability_poison_beam",
"Null Eruption":"inv_cosmicvoid_orb",
"Oozing Xylem":"inv_ability_holyfire_nova",
"Over-infused":"inv_ore_feliron",
"Overload":"spell_nature_callstorm",
"Overwhelming Onslaught":"spell_druid_thrash",
"Paralyzing Shot":"ability_poisonsting",
"Piercing Hiss":"inv_sonic_wave",
"Plague Froth":"inv_ability_poison_debuff",
"Poison Nova":"ability_creature_disease_02",
"Poison Spear Volley":"inv_spear_02",
"Poison Splash":"spell_nature_corrosivebreath",
"Poisoned Cheap Shot":"ability_cheapshot",
"Pool of Darkness":"inv_misc_food_legion_gooamberpink_pool",
"Possession Barrage":"spell_shadow_possession",
"Primal Echo":"spell_druid_stamedingroar",
"Pulverize":"ability_smash",
"Pulverizing Strikes":"ability_druid_swipe",
"Punishing Might":"inv_sword_1h_artifactfelomelorn_d_03dual",
"Purification Strike":"spell_shaman_lavasurge",
"Quaking Leap":"ability_heroicleap",
"Rage of the Shackled":"inv_121_raid_achievement_ulatek",
"Raging Crosswinds":"ability_skyreach_wind",
"Raging Squall":"ability_deathknight_frozencenter",
"Rattle":"inv_sonic_wave",
"Ravenous":"ability_evoker_dragonrage2",
"Ravenous Bellow":"ability_druid_challangingroar",
"Ravenous Feast":"ability_warrior_bloodnova",
"Ravenous Stomp":"ability_earthen_pillar",
"Ravenous Swarm":"inv_ability_druid_adaptiveswarm",
"Razor Dive":"inv_10_specialreagentfoozles_tuskclaw_fire",
"Regurgitate":"inv_ability_poison_wave",
"Release Charge":"spell_chargenegative",
"Restless Amani":"inv_12_nonmasculinecharacter_troll",
"Rip and Slice":"inv_10_specialreagentfoozles_tuskclaw-black",
"Ritual Venom":"inv_ability_poison_beam",
"Ritual of Blazebinding":"spell_fire_totemofwrath",
"Ritual of the Fang":"inv_achievement_dungeon_altaroffangs",
"Roaring Flame Breath":"inv_summerfest_firespirit",
"Rolling Thunder":"spell_nature_lightningoverload",
"Rotten Supplies":"inv_misc_food_91",
"Same-Day Delivery":"achievement_brewery_2",
"Sanguine Storm":"inv_artifact_bloodoftheassassinated",
"Savage Leap":"ability_druid_tigersroar",
"Scavenge":"inv_vulturemount_black",
"Scavenging":"inv_misc_potionbag_special",
"Searing Blows":"ability_shaman_lavalash",
"Searing Fel Flame":"spell_fire_felfirenova",
"Seduction":"spell_shadow_seduction",
"Seismic Upheaval":"ability_rogue_kidneyshot",
"Septic Spatter":"ability_deathknight_roilingblood",
"Serpentine Gust":"ability_skyreach_four_wind",
"Serrated Charge":"inv_artifact_bloodoftheassassinated",
"Sever":"ability_criticalstrike",
"Shadow Barrage":"spell_priest_mindspike",
"Shadow Bite":"spell_shadow_soulleech_3",
"Shadow Bolt Volley":"spell_shadow_shadowbolt",
"Shadow Lash":"inv_misc_volatileshadow",
"Shadow Whirlwind":"spell_necro_deathsknell",
"Shattering Frostspike":"ability_deathknight_pillaroffrost",
"Shell Guard":"inv_cape_special_turtleshell_c_01",
"Shell Spin":"inv_cape_special_turtleshell_c_02",
"Shield Bash":"ability_warrior_shieldbash",
"Shred Armor":"ability_druid_rake",
"Shred Defense":"ability_druid_ravage",
"Shredding Claws":"inv_misc_monsterclaw_03",
"Shredding Shards":"spell_frost_iceshard",
"Sickening Bite":"ability_creature_poison_01",
"Siphon the Weak":"spell_holy_consumemagic",
"Siphoning Infection":"ability_ironmaidens_whirlofblood",
"Sky Strike":"ability_racial_wingbuffet",
"Slithering Flame":"spell_nature_guardianward",
"Smashing Charge":"inv_fellessergronnmount",
"Solar Breath":"ability_skyreach_solar_burst",
"Soul Crush":"inv_ability_warlock_soulrot",
"Soul Sever":"ability_demonhunter_soulcleave2",
"Soul Transfer":"ability_necrolord_fleshcraft",
"Soulbinding":"spell_necro_deathall",
"Soulcoil Ignition":"spell_shadow_soulleech_2",
"Spark Step":"spell_shaman_crashlightning",
"Spectral Coils":"spell_animamaldraxxus_nova",
"Spectral Slash":"ability_druid_supriseattack",
"Spiritcackle":"spell_shadow_deathsembrace",
"Spit Gold":"ability_creature_amber_01",
"Spoiled Supplies":"ability_creature_disease_01",
"Spouting Floret":"inv_enchant_essenceastrallarge",
"Starvation Effigy":"inv_archaeology_80_zandalari_sanguinetotem",
"Static Shock":"spell_nature_chainlightning",
"Steel Barrage":"inv_axe_1h_deathwingraiddw_d_01",
"Stir the Depths":"inv_ability_poison_wave",
"Stone Breaker":"ability_smash",
"Storm Blessed":"spell_nature_lightningshield",
"Stormslam":"ability_shaman_stormstrike",
"Stygian Infection":"ability_rogue_envelopingshadows",
"Sunder Slam":"ability_warrior_shieldbreak",
"Suppression Slam":"ability_golemthunderclap",
"Synchronized Venom":"inv_ability_poison_missile",
"Tail Scythe":"inv_knife_1h_felfireraid_d_04",
"Tail Thrash":"ability_hunter_pet_windserpent",
"Tectonic Strike":"inv_axe_2h_earthendungeon_c_01",
"Tempest Barrier":"inv_shield_1h_artifactstormfist_d_04",
"Tempest Winds":"achievement_raidprimalist_windelemental",
"Thicket's Trinity":"inv_herbalism_70_dreamleaf",
"Thornblade":"spell_nature_thorns",
"Thorncaller Roar":"inv_misc_herb_nightmarevine",
"Throw Junk":"inv_crate_01",
"Thunder Blast":"warrior_talent_icon_bloodandthunder",
"Thunder Jaw":"inv_misc_stormdragonpale",
"Thunder Stomper":"ability_thunderclap",
"Thunder and Lightning":"warrior_talent_icon_thunderstruck",
"Thundering Storm":"spell_shaman_thunderstorm",
"Thunderstorm":"spell_shaman_thunderstorm",
"Toadspawn":"inv_egg_08",
"Tongue Toss":"ability_vehicle_launchplayer",
"Toxic Atrophy":"spell_shadow_requiem",
"Toxic Breath":"spell_fire_felflamebreath",
"Toxic Deluge":"spell_shadow_plaguecloud",
"Toxic Droplets":"inv_ability_poison_orb",
"Toxic Spew":"spell_nature_corrosivebreath",
"Toxic Surge":"inv_ability_poison_wave",
"Triple Shot":"spell_nature_corrosivebreath",
"Ula'tek's Dominance":"inv_skinning_80_snakescales",
"Umbral Rupture":"inv_cosmicvoid_groundstate",
"Uncoil":"ability_hunter_snaketrap",
"Uncoiled Rage":"ability_deathknight_necroticaura",
"Undermining":"spell_shaman_earthquake",
"United Defense":"spell_winston_bubble",
"Unnerving Fixation":"ability_fixated_state_purple",
"Unstable Corruption":"spell_mage_supernova_nightborne",
"Unstable Miasma":"ability_deathwing_bloodcorruption_death",
"Unstable Singularity":"inv_ability_voidweaverpriest_entropicrift",
"Unstable Totem":"ability_shaman_stoneskintotem",
"Uproot":"inv_herb_earthroot",
"Venom Burst":"inv_ability_poison_groundstate",
"Venom Coagulation":"inv_ability_poison_nova",
"Venom Spit":"ability_creature_poison_02",
"Venomfang":"inv_121_trinket_raid_ulatek_fang_green",
"Venomous Emergence":"spell_nature_poisoncleansingtotem",
"Venomous Slash":"ability_rogue_disembowel",
"Venomous Spit":"spell_nature_corrosivebreath",
"Venomous Surge":"ability_creature_poison_06",
"Verdant Stomp":"inv_raptortravelform",
"Vigilant Defense":"creatureportrait_blackrockv2_shieldgong_02",
"Vile Fiend":"inv_argusfelstalkermount",
"Vile Flood":"ability_rogue_deviouspoisons",
"Vindictive Onslaught":"spell_nature_earthquake",
"Virulent Whirl":"inv_ability_poison_groundstate",
"Vitriolic Stasis":"inv_10_enchanting2_magicswirl_red",
"Void Beam":"inv_cosmicvoid_beam",
"Void Blast":"inv_cosmicvoid_missile",
"Void Cascade":"inv_cosmicvoid_missile",
"Volatile Totem":"spell_fire_totemofwrath",
"Warden's Wrath":"spell_nature_wispsplodegreen",
"Whirling Axes":"ability_butcher_whirl",
"Winds of Change":"spell_shaman_unleashweapon_wind",
"Wretched Discharge":"spell_festergutgas",
/* 2026-08-17 icon audit: 22 renamed against Wowhead spells whose descriptions
   match our effect text, plus 2 already-exact names whose spells surfaced. */
"A Knot of Snakes":"ability_hunter_snaketrap",
"Awaken Whelps":"inv_dragonwhelp3_gemmed_red",
"Consume Charge":"spell_nature_unrelentingstorm",
"Corrupted Lifeforce":"inv_nullstone_shadow",
"Cryo Surge":"spell_mage_frostbomb",
"Cutpurse":"ability_warrior_deepcuts",
"Earthsplitter":"spell_nature_earthquake",
"Hydrastrike":"trade_archaeology_whitehydrafigurine",
"Impaling Spear":"inv_spear_08",
"Interrupting Cloudburst":"spell_nature_cyclone",
"Lightcrazed Frenzy":"ability_monk_explodingjadeblossom",
"Lightning Spire":"ability_thunderking_rockfalllow",
"Lightsower Dash":"rogue_burstofspeed",
"Malevolent Presence":"ability_revendreth_priest",
"Orb of Disruption":"ability_monk_forcesphere",
"Rumbling Ward":"ability_gift_of_earth",
"Scouring Sand":"spell_sandexplosion",
"Serpent's Stormcall":"spell_nature_unrelentingstorm",
"Sharp Nail":"ability_hunter_quickshot",
"Summon Primal Thunderclouds":"ability_vehicle_electrocharge",
"Swarming Krolusks":"achievement_dungeon_thesandqueen",
"Thornspike":"inv_misc_herb_goldthorn_bramble",
"Ula'tek's Presence":"achievement_dungeon_templeofsethraliss",
"Violent Sand":"spell_sandexplosion",
/* 2026-08-18 second pass: the first sweep's endpoint capped at ten mixed
   results, so a spell whose name also matches a Zone or Quest never
   surfaced. Murder in a Row was there the whole time. */
"Murder in a Row":"inv_legendary_gun",
"Unkillable Infernal":"spell_shadow_summoninfernal",
/* Winter Squall, 2026-08-18: the mob carried one editorial row where it has
   three named spells. Owner supplied the spell links. */
"Harsh Winter":"spell_frost_arcticwinds",
"Cloudpiercer":"ability_skyreach_wind_wall",
"Static Discharge":"spell_shaman_staticshock",
"Spore Spines":"inv_misc_herb_04"
};

/* ═══ ROWS THAT ARE NOT SPELLS ═══════════════════════════════════════════
   Two kinds of iconless row exist and they mean opposite things, so they must
   not look alike. These fifteen are iconless BY DESIGN: nine are structural —
   a phase marker, a fight-structure note, our own coinage for a group of
   mobs' shared behaviour — and six name an NPC or an add that stands as an
   ability row because that is where the tactics live. Nothing was missed
   researching them; there is no spell to find. They render with WoW's own
   no-art cog (`trade_engineering`, which is what Wowhead itself shows for a
   spell with no assigned icon).

   Anything NOT listed here and missing from ICONS keeps the red question
   mark, because that mark means "this should have an icon and we have not
   found it" — the Vashnik add trio and Uncoiled Union are the live examples,
   and they are worth re-querying as raid data lands. Adding a name here is a
   claim that no spell exists, so make it deliberately.
   ═══════════════════════════════════════════════════════════════════════ */
const NOSPELL=[
"Add Phase",
"Fixate and Fear",
"Fragment of Malacrass",
"King Akul",
"King Rahu'ai",
"King T'Maji",
"Light Mob Beams",
"Orb Gauntlet",
"Queen Phat'ta",
"Released Inhibitors",
"Spirits of the Veil",
"T'zala",
"Two-phase structure"
];

/* Display names for the journal portraits above — captions read from here,
   so a key without a name simply gets no caption rather than a broken one. */
const JNAMES={
"j-adderis":"Adderis",
"j-aspix":"Aspix",
"j-avatar-of-sethraliss":"Avatar of Sethraliss",
"j-first-mate-nama":"First Mate Nama",
"j-galvazzt":"Galvazzt",
"j-hex-lord-malacrass":"Hex Lord Malacrass",
"j-ithraz":"Ithraz",
"j-merektha":"Merektha",
"j-morzahi":"Mor'zahi",
"j-nekzali":"Nek'zali",
"j-scrollsage-iku":"Scrollsage Iku",
"j-sszorak":"Sszorak",
"j-trader-gebbo":"Trader Gebbo",
"j-ulatek":"Ula'tek",
"j-vashnik":"Vashnik the Malignant",
"j-vexhul":"Vexhul",
"j-zuljan-raid":"Zul'jan",
"j-akaali":"Aka'ali the Conqueror",
"j-atroxus":"Atroxus",
"j-charonus":"Charonus",
"j-erkhart-stormvein":"Erkhart Stormvein",
"j-golden-serpent":"The Golden Serpent",
"j-hoardmonger":"The Hoardmonger",
"j-kezkitt":"Kezkitt",
"j-king-dazar":"King Dazar",
"j-kokia-blazehoof":"Ko'kia Blazehoof",
"j-kula":"Kula the Butcher",
"j-kyrakka":"Kyrakka",
"j-kystia-manaheart":"Kystia Manaheart",
"j-lekshi":"Lekshi",
"j-lightwarden-ruia":"Lightwarden Ruia",
"j-lithiel-cinderfury":"Lithiel Cinderfury",
"j-mchimba":"Mchimba the Embalmer",
"j-meittik":"Meittik",
"j-melidrussa":"Melidrussa Chillworn",
"j-nalorakk":"Nalorakk",
"j-ravi":"Rav'i",
"j-sentinel-of-winter":"Sentinel of Winter",
"j-tazrah":"Taz'Rah",
"j-writhing-coil":"The Writhing Coil",
"j-xathuux":"Xathuux the Annihilator",
"j-zaen-bladesorrow":"Zaen Bladesorrow",
"j-zanazal":"Zanazal the Wise",
"j-ziekket":"Ziekket",
"j-zuljan":"Zul'jan"
};

/* ═══ SEASON 2 TIER SET BONUSES ═══ 79 spec bonuses across 13 classes.
   Bonus text is Blizzard's own (via Icy Veins' set guide); percentages and
   durations are exact because they do not scale. Grouped by armour type to
   mirror how the tokens are shared. ═════════════════════════════════════ */
const SETBONUS=[
 {"c":"Mage","a":"Cloth","set":"Primal Leywarden's Attire","specs":[{"s":"Arcane","p2":"Arcane Missiles fires 1 additional Missile and deals 20% increased damage.","p4":"Each wave of Arcane Missiles increases the damage of your next Arcane Blast, Arcane Pulse, or Prismatic Bolt by 5%, up to 40%. Fire"},{"s":"Fire","p2":"Pyroclasm causes Flamestrike and Pyroblast to always critically strike.","p4":"Pyroclasm reduces the cast time of Flamestrike and Pyroblast by 20% and its damage bonus is increased by 25%. Frost"},{"s":"Frost","p2":"Each stack of Freezing Shattered has a 4% chance to generate an Icicle. Glacial Spike damage increased by 20%.","p4":"Casting Glacial Spike has a chance to rapidly generate 5 Icicles over 1 sec. Shatter damage increased by 5%. 1.2. Priest Midnight Season 2 Tier: Cosmic Penitent's Raiment Discipline"}]},
 {"c":"Priest","a":"Cloth","set":"Cosmic Penitent's Raiment","specs":[{"s":"Discipline","p2":"Penance damage and healing increased by 20%. Casting Penance reduces the cooldown of Mind Blast by 2.0 sec.","p4":"After casting Mind Blast, your next Power Word: Shield or Void Shield absorbs 25% more damage. Holy"},{"s":"Holy","p2":"Each target affected by your Renew increases the critical strike chance of your spells and abilities by 2%, up to 6%.","p4":"Renew healing increased by 10%. Light's Resurgence now has a 100% chance to leave a Renew on the first target Prayer of Mending heals. Shadow"},{"s":"Shadow","p2":"Tentacle Slam's cooldown is reduced by 3 sec and its damage is increased by 100%.","p4":"Tentacle Slam has a 100% chance to grant a free use of Void Volley at 100% effectiveness. 1.3. Warlock Midnight Season 2 Tier: Damned Necrolyte's Shattered Restraints Affliction"}]},
 {"c":"Warlock","a":"Cloth","set":"Damned Necrolyte's Shattered Restraints","specs":[{"s":"Affliction","p2":"Wither / Corruption damage increased by 25%. Agony damage increased by 15%","p4":"Each active Unstable Affliction increases your damage dealt by your spells and abilities by 2%, up to 6%. Seed of Corruption applies Unstable Affliction at 20% effectiveness to your target. Demonology"},{"s":"Demonology","p2":"Wild Imp damage increased by 10%. Implosion damage increased by 20%.","p4":"When their energy depletes, Wild Imps have a 20% chance to fling themselves at their target and Implode at 250% effectiveness to their main target and 225% effectiveness to other targets. Destruction"},{"s":"Destruction","p2":"Incinerate damage increased by 25% and Incinerate has a 10% increased chance to evoke an Echo of Sargeras.","p4":"Targets damaged by Echo of Sargeras take 6% increased damage from your spells and abilities for 6 sec. 1.4. Demon Hunter Midnight Season 2 Tier: Abyssal Doomhound's Pursuit Devourer"}]},
 {"c":"Demon Hunter","a":"Leather","set":"Abyssal Doomhound's Pursuit","specs":[{"s":"Devourer","p2":"Harvesting 4 or more Soul Fragments with Reap has a 20% chance to cause your next Consume to be instant cast and explode in a Soulburst, dealing (600% of Spell Power) Cosmic damage to nearby enemies.","p4":"Soulburst generates 8 Soul Fragments and grants Moment of Craving. Reap deals 20% increased damage. Havoc"},{"s":"Havoc","p2":"Blade Dance, Chaos Strike, and Essence Break have 12% increased damage.","p4":"Essence Break now applies and benefits from the effects of Cycle of Hatred, has 35% increased initial strike damage, and has 2.0 sec increased duration. Vengeance"},{"s":"Vengeance","p2":"Sigil of Flame's damage over time is increased by 50%. Soul Cleave increases the duration of Sigil of Flame on your primary target by 2.0 sec.","p4":"Immolation Aura and Sigil of Spite have 100% increased damage against targets affected by your Sigil of Flame. 1.5. Druid Midnight Season 2 Tier: Bark of the Enigmatic Dreamwatcher Balance"}]},
 {"c":"Druid","a":"Leather","set":"Bark of the Enigmatic Dreamwatcher","specs":[{"s":"Balance","p2":"Starsurge damage increased by 20%. Starfall also deals (30.4% of Spell Power) Astral damage instantly to all valid enemies in range when cast.","p4":"Your damage is increased by 10% while in any Eclipse. This bonus wanes to 2% at the midpoint of the Eclipse, then waxes back to 10% at the end. Feral"},{"s":"Feral","p2":"When Incarnation: Avatar of Ashamane / Berserk ends, you deal 10% increased damage for (Incarnation: Avatar of Ashamane: 0.75) sec for each combo point spent during Incarnation: Avatar of Ashamane / Berserk.","p4":"Incarnation: Avatar of Ashamane / Berserk lasts 10 sec longer. Guardian"},{"s":"Guardian","p2":"Thrash has a 20% chance to make your next Mangle deal 100% increased damage.","p4":"Thrash calls up 3 thorns, each impaling a target for (54% of Attack Power) Nature damage and dealing (27% of Attack Power) additional Nature damage to up to 5 nearby enemies, and extends the duration of Incarnation: Guardian of Ursoc / Berserk by 0.5 sec, up to 5.0 sec. Restoration"},{"s":"Restoration","p2":"Rejuvenation has a 15% chance to grant Genesis, causing all your heal over time effects to heal for 15% more for 8 sec. Multiple applications may overlap.","p4":"Nature's Swiftness, Tranquility, and Incarnation: Tree of Life / Convoke the Spirits have a 100% chance to grant Genesis, and Genesis duration is increased by 4 sec. 1.6. Monk Midnight Season 2 Tier: Guile of the Monkey King Brewmaster"}]},
 {"c":"Monk","a":"Leather","set":"Guile of the Monkey King","specs":[{"s":"Brewmaster","p2":"Breath of Fire ignites your next Keg Smash, causing it to explode on contact, dealing (50% of Attack Power) additional Flamestrike damage to its primary target and reduced damage to additional targets.","p4":"Ignited Keg Smashes cause enemies struck to take 8% increased damage from your Physical abilities, and leave a patch of flames on the ground, dealing (25% of Attack Power) Fire damage each second for 5 sec. Mistweaver"},{"s":"Mistweaver","p2":"Rising Sun Kick deals 30% increased damage and Rushing Wind Kick's healing is increased by 100%.","p4":"Rising Sun Kick and Rushing Wind Kick have a chance to cause their next cast to ignore their cooldown and reduce their mana cost by 100%. Windwalker"},{"s":"Windwalker","p2":"Fists of Fury strikes an additional time at the start of its channel at 50% effectiveness.","p4":"Fists of Fury increases the damage of your next Rising Sun Kick by 10% or Spinning Crane Kick by 20% each time it strikes, stacking up to 6 times."}]},
 {"c":"Rogue","a":"Leather","set":"Chosen Bloodslayer's Hexweave","specs":[{"s":"Assassination","p2":"Envenom damage increased by 10% and it increases your damage dealt by 3%.","p4":"Deadly Poison increases your bleed damage on the target by 10%. Auto-attacks to targets with your Amplifying Poison deal 3% increased damage per stack. Wound Poison hits a second time. Outlaw"},{"s":"Outlaw","p2":"Dispatch damage increased by 15%.","p4":"Sinister Strike and Ambush have a 20% chance to cause your next Dispatch to be free and deal damage as if you spent the maximum combo points. Subtlety"},{"s":"Subtlety","p2":"Backstab costs 10 less Energy and has 100% increased damage. Shuriken Storm costs 5 less Energy and has 60% increased damage.","p4":"Lingering Shadow now also benefits Eviscerate and Black Powder at 100% effectiveness. 1.8. Evoker Midnight Season 2 Tier: Echo of Calamity Augmentation"}]},
 {"c":"Hunter","a":"Mail","set":"Skulking Viper's Ambush","specs":[{"s":"Beast Mastery","p2":"Barbed Shot causes your pets to Stomp one additional time at 50% effectiveness.","p4":"Stomp causes your next Cobra Shot to either benefit from Beast Cleave at 20% effectiveness, or strike your primary target for 15% additional damage, stacking up to 4 times. Marksmanship"},{"s":"Marksmanship","p2":"Explosive Shot lasts 1.0 sec longer and deals 5% increased damage.","p4":"Aimed Shot and Rapid Fire damage increased by 5%. Each time Explosive Shot causes a burst of damage, the cooldown of Aimed Shot and Rapid Fire is reduced by 0.5 sec. Survival"},{"s":"Survival","p2":"Mongoose Fury also increases the damage of Wildfire Bomb by 10%.","p4":"Each blast of Boomstick extends the duration of Mongoose Fury by 1.0 sec. Mongoose Fury effects are increased by 10%. 1.10. Shaman Midnight Season 2 Tier: Ophidian Oracle's Prophecy Elemental"}]},
 {"c":"Shaman","a":"Mail","set":"Ophidian Oracle's Prophecy","specs":[{"s":"Elemental","p2":"Earth Shock, Earthquake, and Elemental Blast damage increased by 25%.","p4":"When Stormkeeper or Ascendance fade, your next 2 Lightning Bolts, Chain Lightnings, or Lava Bursts deal 25% increased damage and cause your next Earthquake, Earth Shock, or Elemental Blast to cost 100% less Maelstrom. Enhancement"},{"s":"Enhancement","p2":"Voltaic Blaze causes your primary target to erupt in a Fire Nova every 2 sec for 6 sec. Fire Nova deals 200% increased damage to the primary target of your Voltaic Blaze.","p4":"Fire Nova reduces the cooldown of Crash Lightning by 2.0 sec and increases the damage of your next Crash Lightning by 8%, stacking up to 5 times. Restoration"},{"s":"Restoration","p2":"Healing Wave and Chain Heal have a chance to create a Healing Rain at the target's location for 8.0 sec.","p4":"Every 1 sec, 1 ally inside of Healing Rain gains a watery shield that absorbs 0 damage for 10 sec. 1.11. Death Knight Midnight Season 2 Tier: Baleful Grave-Knight's Crucible Blood"}]},
 {"c":"Evoker","a":"Mail","set":"Echo of Calamity","specs":[{"s":"Augmentation","p2":"Upheaval's cooldown is reduced by 10 sec.","p4":"Upheaval magnifies your Fate Mirror effects for 8 sec, increasing the amount of damage echoed to 45%. Devastation"},{"s":"Devastation","p2":"Shattering Star's damage is increased by 50%, and it always casts as if you had reached maximum empower level.","p4":"Causality reduces the remaining cooldown of your empower spells by an additional 0.1 sec each time the effect occurs. Eternity Surge deals 10% increased damage. Preservation"},{"s":"Preservation","p2":"Consuming Essence Burst sends forth a Living Flame at your target at 100% effectiveness, or a nearby injured target if they are full health.","p4":"Green spells restore 5% more health, and Verdant Embrace has a 100% chance to grant Essence Burst. 1.9. Hunter Midnight Season 2 Tier: Skulking Viper's Ambush Beast Mastery"}]},
 {"c":"Death Knight","a":"Plate","set":"Baleful Grave-Knight's Crucible","specs":[{"s":"Blood","p2":"When you Death Strike, gain a stack of Blood Debt, increasing Strength by 0.5%, up to 5.0%. When Blood Debt reaches 10 stacks, your next Marrowrend consumes it granting 10% Strength for 10 sec.","p4":"When consuming Blood Debt, your next Marrowrend generates 3 additional Boneshield and deals (900% of Attack Power) Shadow damage to your target and (600% of Attack Power) to nearby enemies. Frost"},{"s":"Frost","p2":"Each time Remorseless Winter damages at least 1 enemy, gain Freezing Tempest which grants 2% attack speed and 4% increased Icy Death Torrent damage for 5 sec, stacking.","p4":"Remorseless Winter deals damage 25% more frequently, and Freezing Tempest lasts 5 sec longer. Unholy"},{"s":"Unholy","p2":"Your Magus of the Dead and Lord of the Dead cast a more powerful Necrotic Bolt instead of Frostbolt, and Withering Grasp instead of Shadow Bolt.","p4":"Necrotic Bolt's damage is increased by 130%, and Withering Grasp's damage is increased by 130%, against enemies below 35% health. 1.12. Paladin Midnight Season 2 Tier: Radiance of the Consecrated Flame Holy"}]},
 {"c":"Paladin","a":"Plate","set":"Radiance of the Consecrated Flame","specs":[{"s":"Holy","p2":"Infusion of Light increases the healing of Flash of Light by an additional 100% and the absorb from Greater Judgment by an additional 100%.","p4":"Judgment now has a 20% chance to grant Infusion of Light. Holy Light now has a 100% chance to grant Infusion of Light, but its mana cost is increased by 50%. Protection"},{"s":"Protection","p2":"Consecration is 30% larger and enemies within your Consecration are illuminated, increasing the chance for your abilities to critically strike them by 5%.","p4":"Enemies struck by Judgment or Blessed Hammer / Hammer of the Righteous / Crusader Strike take 20% additional Holy damage. If they are struck by a critical strike the additional damage is increased by 100%. Retribution"},{"s":"Retribution","p2":"Divine Purpose has an additional 10% chance to activate, and consuming it grants Divine Power, increasing Holy damage done by 10% for 12 sec.","p4":"Consuming Divine Purpose grants Divine Arbiter, empowering your other Holy Power spenders to unleash an arbiter of light at their primary target, dealing (405% of Attack Power) Holy damage and (270% of Attack Power) Holy damage to enemies within 8 yds. Cannot occur while Divine Arbiter is active. 1.13. Warrior Midnight Season 2 Tier: Jade Warrior's Dominion Arms"}]},
 {"c":"Warrior","a":"Plate","set":"Jade Warrior's Dominion","specs":[{"s":"Arms","p2":"Mortal Strike and Execute damage increased by 10% and when you Slam a target, Slam also deals (100% of Attack Power) damage to enemies within 8 yds of it. Deals reduced damage beyond 5 targets.","p4":"Overpower damage increased by 15%. Mortal Strike and Overpower increase the damage of your next Slam by 20%, stacking up to 5 times. Fury"},{"s":"Fury","p2":"Raging Blow damage increased by 15%. During Recklessness Raging Blow extends the duration of Recklessness by 2 sec, up to 6 sec.","p4":"Bloodthirst damage increased by 10%. During Recklessness Bloodthirst increases the critical strike bonus of Recklessness by 5%, up to 10%. Protection"},{"s":"Protection","p2":"Your free Revenges deal 15% additional damage and cause your next Shield Slam to deal 20% additional damage.","p4":"Ravager and your free Revenges cause all targets to bleed for (304.745% of Attack Power) damage over 12 sec. Ravager's cooldown is reduced by 30 sec. 2."}]}
];

const CORRECTIONS=[
 ["Axegrinder","Axe Grinder","Altar of Fangs","ability",0],
 ["Boneslicer","Bone Slicer","Altar of Fangs","ability",0],
 ["Twinfang Harrower","Twin Fang Harrower","Altar of Fangs","lt",0],
 ["Uncoil","Uncoiled Writhe","Altar of Fangs","ability",0],
 ["Undermining","Undermining Shockwave","Altar of Fangs","ability",0],
 ["Bonded Beasttamer","Bonded Beast Tamer","Den of Nalorakk","trash",0],
 ["Earthshatter Slam","Earth Shatter Slam","Den of Nalorakk","ability",0],
 ["Earthwhisper Tender","Earth Whisper Tender","Den of Nalorakk","caster",0],
 ["Echoing Maul","Echoing Maw","Den of Nalorakk","ability",0],
 ["Loa Speaker Nanea","Loa Speaker Nanaea","Den of Nalorakk","mini",0],
 ["Ruthless Totemcaller","Ruthless Totem Caller","Den of Nalorakk","trash",0],
 ["Shattering Frostspike","Shattering Frost Spikes","Den of Nalorakk","ability",0],
 ["Shredding Claws","Shredding Claw","Den of Nalorakk","ability",0],
 ["Stormbound Mystic","Storm-Bound Mystic","Den of Nalorakk","caster",0],
 ["Thornclaw Gatherer","Thorn Claw Gatherer","Den of Nalorakk","trash",0],
 ["Deathly Roar","Rabond","King's Rest","ability",0],
 ["Shadow of Zul","Shade of Zul","King's Rest","mini",0],
 ["Shadow-Borne Champion","Shadowborne Champion","King's Rest","lt",0],
 ["Felmaster Lucsei","Fel Master Luxay","Murder Row","mini",0],
 ["Heartstop Poison","Heart Stop Poison","Murder Row","ability",0],
 ["Massive Felwyrm","Massive Fel Worm","Murder Row","mini",0],
 ["Same-Day Delivery","Fel Freight","Murder Row","ability",0],
 ["Seductive Sayaad","Seductive Succubus","Murder Row","trash",0],
 ["Blazebound Destroyer","Blaze-Bound Destroyer","Ruby Life Pools","lt",0],
 ["Chillstorm","Chill Storm","Ruby Life Pools","ability",0],
 ["Defier Draghar","Defiler Draghar","Ruby Life Pools","mini",0],
 ["Flame Dance","Flame Dancer","Ruby Life Pools","ability",0],
 ["Flamegullet","Flame Gullet","Ruby Life Pools","mini",0],
 ["High Channeler Ryvati","High Channeler Riveti","Ruby Life Pools","mini",0],
 ["Primalist Flamedancer","Ash Seer Flame Dancer","Ruby Life Pools","trash",0],
 ["Ritual of Blazebinding","Ritual of Blaze Binding","Ruby Life Pools","ability",0],
 ["Stormslam","Storm Slam","Ruby Life Pools","ability",0],
 ["Tempest Barrier","Storm Cloud Detonation","Ruby Life Pools","ability",0],
 ["Adderis and Aspix","Adarrah and Aspix","Temple of Sethraliss","boss",1],
 ["Defiling Taint","Essence Defiler","Temple of Sethraliss","ability",0],
 ["Galvanized","Charged Vulnerability","Temple of Sethraliss","ability",0],
 ["Siphon the Weak","Faceless Tormentor waves","Temple of Sethraliss","ability",0],
 ["Unstable Corruption","Corrupted Guardian","Temple of Sethraliss","ability",0],
 ["Awaken the Lightbloom","Awaken the Light Bloom","The Blinding Vale","ability",0],
 ["Frantic Blooming","Rouse","The Blinding Vale","ability",0],
 ["Lightbloom's Essence","Light Bloom's Essence","The Blinding Vale","ability",0],
 ["Lightblossom Beam","Light Blossom Beam","The Blinding Vale","ability",0],
 ["Lightblossom Trinity","The Light Blossom Trinity","The Blinding Vale","boss",1],
 ["Lightgorged Lasher","Light Gorged Lasher","The Blinding Vale","trash",0],
 ["Potatoad Matriarch","Toad Matriarch","The Blinding Vale","mini",0],
 ["Radiant Spellsower","Radiant Spell Sower","The Blinding Vale","caster",0],
 ["Spouting Floret","Spouting Florid","The Blinding Vale","ability",0],
 ["Thornblade","Thorn Blade","The Blinding Vale","ability",0],
 ["Thorny Saptor","Thorny Scepter","The Blinding Vale","trash",0],
 ["Toadspawn","Toad Spawn","The Blinding Vale","ability",0],
 ["Virid Grovekeeper","Virid Grove Keeper","The Blinding Vale","lt",0],
 ["Agitated Voidscythe","Agitated Void Side","Voidscar Arena","lt",0],
 ["Chitigoth","Chiltara","Voidscar Arena","mini",0],
 ["Kilivore Screamer","Kil'vore Screamer","Voidscar Arena","trash",0],
 ["Mad Shriek","Mass Shriek","Voidscar Arena","ability",0],
 ["Raj'kess the Spellstorm","Rajh'Cath the Spellstorm","Voidscar Arena","mini",0],
 ["Savage Shredclaw","Savage Shred Claw","Voidscar Arena","trash",0],
 ["Unstable Singularity","Unstable Singularities","Voidscar Arena","ability",0],
 ["Voidtouched Magi","Void-Touched Magus","Voidscar Arena","lt",0],
 ["Entombed Sentinels","Entombed Wardens","Venomous Abyss","boss",0],
 ["The Lost Explorers","The Lost Expedition","Venomous Abyss","boss",0],
 ["Nek'zali the Soulcoiler","Nek'zali the Soulcaller","Venomous Abyss","boss",0],
 ["Breath of Ula'tek","Ula'tek's Breath","Venomous Abyss","boss",0],
 ["Blood of Ula'tek","Ula'tek's Blood","Venomous Abyss","boss",0],
 ["Hex Lord Malacrass","Malacras","Venomous Abyss","boss",0],
 ["Echo of Jawae","Javaeh","Venomous Abyss","mini",0],
 ["Latent Cultist","Slumbering Sectant","Venomous Abyss","trash",0],
 ["Grab Fish","Revolting Fish","Venomous Abyss","ability",0],
 ["Final Ascension","Empowered Ascension","Venomous Abyss","ability",0],
 ["Veil of Twilight","Twilight Veil","Venomous Abyss","ability",0],
 ["Coalesced Venom","Coagulated Poison","Venomous Abyss","ability",0],
 ["Clinging Murk","Sticky Filth","Venomous Abyss","ability",0],
 /* 2026-08-17 icon audit renames — every guide wrote these; Wowhead disagrees */
 ["Hydrastrike","Hydro Strike","Altar of Fangs","ability",0],
 ["Cutpurse","Cut Purse","Murder Row","ability",0],
 ["Sharp Nail","Sharp Nails","Murder Row","ability",0],
 ["Rumbling Ward","Rumbling War Shield","Den of Nalorakk","ability",0],
 ["Cryo Surge","Cryosurge","Den of Nalorakk","ability",0],
 ["Earthsplitter","Earth Splitter","Voidscar Arena","ability",0],
 ["Orb of Disruption","Orbs of Disruption","Voidscar Arena","ability",0],
 ["Violent Sand","Violent Sands","Voidscar Arena","ability",0],
 ["Lightsower Dash","Light Sower's Dash","The Blinding Vale","ability",0],
 ["Lightcrazed Frenzy","Light Crazed Frenzy","The Blinding Vale","ability",0],
 ["Thornspike","Thorn Spike","The Blinding Vale","ability",0],
 ["Impaling Spear","Impaling Spears","King's Rest","ability",0],
 ["Summon Primal Thunderclouds","Summon Thunderclouds","Ruby Life Pools","ability",0],
 ["Awaken Whelps","Awaken Welps","Ruby Life Pools","ability",0],
 ["Interrupting Cloudburst","Interrupting Cloud Burst","Ruby Life Pools","ability",0],
 ["Swarming Krolusks","Swarming Krolusk","Temple of Sethraliss","ability",0],
 ["Scouring Sand","Scouring Sands","Temple of Sethraliss","ability",0],
 ["Serpent's Stormcall","Serpent Storm Called","Temple of Sethraliss","ability",0],
 ["A Knot of Snakes","Knot of Snakes","Temple of Sethraliss","ability",0],
 ["Lightning Spire","Lightning Spires","Temple of Sethraliss","ability",0],
 ["Consume Charge","Consumed Charge","Temple of Sethraliss","ability",0],
 ["Corrupted Lifeforce","Corrupted Life Force","Temple of Sethraliss","ability",0],
 /* 2026-08-18: compound names Blizzard writes as one word. The Manaheart
    trinket tooltip still says "Fel Shield" in two — that quote is left as is. */
 ["Felshield","Fel Shield","Murder Row","ability",0],
 ["Lightfire","Light Fire","The Blinding Vale","ability",0],
 ["Harsh Winter","Master of the Winds","Den of Nalorakk","ability",0],
 ["Spore Spines","Four-Spined","The Blinding Vale","ability",0],
 /* 2026-08-18: the dungeon journal itself spells these with the apostrophes */
 ["Ko'kia Blazehoof","Kokia Blazehoof","Ruby Life Pools","boss",0],
 ["T'zala","Tazala","King's Rest","ability",0]
];
