/* js/data-raid.js — the Raid module: The Venomous Abyss
   Load order: data-shared → data-mplus → data-raid → render → app.
   All five load with `defer`, which preserves this order. */

/* ═══ RAID · THE VENOMOUS ABYSS ═════════════════════════════════════════════
   Eight bosses inside the Vaults of Atal'Utek, patch 12.1. Scope: Normal
   and Heroic. Mythic and LFR are deliberately out of scope for now — the
   difficulty model already accommodates them (df takes a third value), so
   adding either later is data, not structure.

   THE FORK. The raid is not linear: after Nek'zali it splits into two wings
   — Entombed Sentinels → Vashnik, and The Lost Explorers → Sszorak — which
   converge at the Twin Fangs. Sources list the middle four in different
   orders because each is describing one walk of the same graph; that is not
   a naming dispute and must not be filed as one. `o` is the canonical
   listing index used by the switcher; never render it as a kill-order claim
   for a fork boss — use `pos` instead.

   Ability shape mirrors DUNGEONS: {n,t,c,r,sev,e,h,s} plus:
     df : difficulties the ability exists on — ["h"] for Heroic-only.
          Absent means both. Never write ["n","h"] explicitly; absence is
          the both-difficulties spelling and the checker enforces it.
     hh : Heroic-only addendum to the tactic, rendered only on Heroic.
   Bosses carry phases:[{n,trigger,a:[...]}] — flat a:[] stays legal for a
   phaseless boss.

   Names are Wowhead's where Wowhead has them; the raid is new enough that
   many entities have no entry yet, so IV/Method agreement stands in until
   the database moves. wow.gg reads like a translation and disagrees on
   several names — those variants live in CORRECTIONS, not here. wow.gg also
   describes the MYTHIC versions of fights by its own admission, so it is
   cited for structure, loot and Ula'tek, not for Normal/Heroic specifics.
   ═══════════════════════════════════════════════════════════════════════ */
const RAID={id:"venomous-abyss",name:"The Venomous Abyss",short:"Abyss",
 patch:"12.1",loc:"The Coiled Isle — inside the Vaults of Atal'Utek",
 difficulties:["n","h"],
 opens:"2026-08-18",
 minIlvl:273,
 schedule:[
  ["Week of 18 Aug","Normal, Heroic and Mythic open; Raid Finder Wing 1"],
  ["Week of 25 Aug","Story Mode; Raid Finder Wing 2"],
  ["Week of 1 Sep","Raid Finder Wing 3"],
  ["Week of 8 Sep","Raid Finder Wing 4"]],
 /* Item level by boss bracket, Normal and Heroic only. The bracket is a
    property of the boss, not of when you kill it — the wing bosses all pay
    at the 2-3 / 4-6 tiers regardless of route. */
 ilvl:{
  brackets:["Nek'zali","Wing openers (Sentinels, Explorers)","Wing enders + Twin Fangs","Coiled Altar, Ula'tek"],
  n:[292,295,298,302], h:[305,308,311,315],
  crests:{n:"Champion Mistcrests — the last two bosses also drop Hero",
          h:"Hero Mistcrests — the last two bosses also drop Myth"}},
 entrance:{way:"/way #2509 47.11 28.30",s:["iv_va"]},
 fork:{after:"nekzali",converge:"twin-fangs",
  wings:[{n:"Sentinel wing",ids:["entombed-sentinels","vashnik"]},
         {n:"Explorer wing",ids:["lost-explorers","sszorak"]}]},
 bosses:[

 /* ── 1 · NEK'ZALI THE SOULCOILER ─────────────────────────────────────── */
 {id:"nekzali",o:1,n:"Nek'zali the Soulcoiler",short:"Nek'zali",
  pos:"Opens the raid",lv:1,sub:"Tower defence, and the tower is a hole in the ground",
  brief:"Everything orbits the Soulcoil Well in the centre: adds feed it energy, energy feeds her, and 100 energy is the enrage. Add control first, boss damage second — a first boss that teaches the rule the rest of the raid is built on.",
  reads:[{by:"Method",t:"Simple core loop with real texture underneath: puddle placement in Phase 1 decides how annoying Phase 2 gets, and the corpse-burning intermission is genuinely clever. Rated 3/5.",s:["me_nek"]},
   {by:"Tactyks",t:"A much more complicated first boss than we're used to — expect it to land slightly undertuned to compensate, but who actually knows.",s:["tk_va"]}],
  phases:[
   {n:"Phase 1",trigger:"Pull to 50% health",a:[
    {n:"Restless Amani",t:["adds","shield"],c:["magic","focus","kite"],r:["dps"],sev:3,
     e:"Undead Amani rise from the coffins and march for the Well behind a shield that only magic damage breaks. Every add that arrives feeds her 5 energy and triggers a Soulcoil Rite.",
     h:"Drag the boss to the biggest glowing coffin cluster for cleave, break shields with casters — hunter damage is Physical and does nothing — and kill them before they arrive. One slip is survivable; several in a row is a wipe. Whether they can be gripped and slowed through the shield is contested; see the open questions.",
     hh:"Corpses leave a Vessel of Awakening behind and blight players within 15 yards — and the intermission will raise unburned Vessels as empowered adds, so Phase 1 kills become Phase 2 problems.",
     s:["iv_nek","me_nek"]},
    {n:"Soulcoil Ignition",t:["groupdmg","dot","stacking","channel"],c:["topoff","defensive"],r:["healer"],sev:3,
     e:"She agitates the Well herself for repeated Rites while Anguished Echoes spill out of it, and each cast feeds her energy.",
     h:"A healing check on a clean raid and a graveyard on a dirty one — go in with zero Ritual Burn stacks, hold a healing cooldown for it, and dodge the echoes. The sources disagree on its exact shape; see the open questions.",
     s:["iv_nek","me_nek"]},
    {n:"Essence Rend",t:["debuff","dot","denial"],c:["magic","position"],r:["healer"],sev:2,
     e:"Pulls its targets toward the centre, then leaves a dispellable DoT — and the dispel drops a permanent Latent Cultist puddle wherever it lands.",
     h:"The rare dispel you deliberately sit on: let the target walk to the edge first, then cleanse — the parked images patrol the room from the moment they exist, and one source believes the debuff also carries a healing absorb, so overhealing it early wastes the placement too. Phase 2 sends every image wandering on each Invoke, so a tidy Phase 1 is the whole trick.",
     s:["iv_nek","me_nek"]},
    {n:"Possession Barrage",t:["line","groupdmg"],c:["position","preposition"],r:["tank"],sev:3,
     e:"Spirits fly at the active tank and detonate on the first body they touch, hitting the raid harder the shorter the trip — and stacking five more Hollowing Strikes on whoever they find. How many spirits is contested; see the open questions.",
     h:"Tank sprints 30+ yards out before it fires and calls the direction; everyone else clears the line — a body-block detonates them early at full spite. Taunting mid-cast does nothing: it homed the moment it began. Detonations spawn more Amani, so the tank gathers on the way back.",
     hh:"Each spirit that hits also applies Hollowing Strikes to its victim.",
     s:["iv_nek","me_nek"]},
    {n:"Hollowing Strikes",t:["tankbuster","stacking","healred"],c:["defensive"],r:["tank"],sev:2,
     e:"Her melee stacks a healing-received cut on the tank.",
     h:"Each stack is a healing cut and Barrage adds five at once, so the tank plan is built around it: taunt at three-to-four stacks on the pull, then swap on cooldown as stacks drop — which lands naturally right after a Barrage.",
     s:["iv_nek","me_nek"]}]},
   {n:"Intermission — Ritual of Awakening",trigger:"At 50% she retreats to the Well, immune",a:[
    {n:"Soul Transfer",t:["adds","channel"],c:["focus","dodge"],r:["dps"],sev:2,
     e:"A channel raises an Echo of Jawae — the first on one side of the room, the second on the opposite side once the first dies. Amani keep spawning throughout.",
     h:"Don't stand in the beam when it completes — and a tank picks the Echo up the moment it lands, because it comes out with an aggro table. Kill both Echoes to end the intermission; cleave the Amani into them.",
     s:["iv_nek","me_nek"]},
    {n:"Hungering Pyre",t:["soak","groupdmg"],c:["soak","topoff"],r:["healer","mdps"],sev:2,
     e:"A group soak centred on the active tank that burns away any corpses it covers.",
     h:"Melee soak it on top of a corpse pile — the tank drags the Echo there first, and the soak is roomy enough for half the raid. Everyone outside it takes a DoT instead, so the choice is soak or bleed. Corpse cleanup now is what stops the empowered-add problem later.",
     s:["iv_nek","me_nek"]},
    {n:"Slithering Flame",t:["soak","denial"],c:["position"],r:["rdps"],sev:1,df:["h"],
     e:"Everyone who skips the Pyre soak gets a small burn circle of their own.",
     h:"Aim it at leftover corpses the main soak missed — ranged deliberately sit out the Pyre to sweep the strays.",
     s:["iv_nek","me_nek"]}]},
   {n:"Phase 2",trigger:"Both Echoes dead; her energy resets",a:[
    {n:"Invoke",t:["groupdmg","dot","stacking"],c:["unavoidable","topoff"],r:["healer"],sev:3,
     e:"Soulcoil Rite for the whole raid that no longer falls off, ramping with every cast — and each Invoke sends your Phase 1 puddles wandering around the Well.",
     h:"This is the timer: lust on phase start and kill her before 100 energy brings Uncoiled Rage. There is no plan B.",
     s:["iv_nek","me_nek"]},
    {n:"Uncoiled Rage",t:["enrage"],c:["unavoidable"],r:["dps"],sev:3,
     e:"At full energy she unleashes — a soft enrage the raid does not outlive.",
     h:"Everything before this point was about delaying it: clean add control buys the Phase 2 you need.",
     s:["iv_nek","wg_va"]}]}],
  loot:[
   {n:"Initiate's Sacrificial Tights",sl:"Legs",ty:"Cloth",b:"Nek'zali the Soulcoiler",ic:"inv_pant_cloth_raidpriestulatek_d_01",id:268236,p:["Int"],x:[["Mastery", 72], ["Vers", 34]]},
   {n:"Nek'zali's Spiritwalkers",sl:"Feet",ty:"Cloth",b:"Nek'zali the Soulcoiler",ic:"inv_boot_cloth_raidpriestulatek_d_01",id:268218,p:["Int"],x:[["Crit", 56], ["Mastery", 24]]},
   {n:"Vestment of the Awakening",sl:"Chest",ty:"Leather",b:"Nek'zali the Soulcoiler",ic:"inv_robe_leather_raiddruidulatek_d_01",id:268235,p:["Agi", "Int"],x:[["Haste", 74], ["Mastery", 32]]},
   {n:"Restless Spirit Shackles",sl:"Wrist",ty:"Leather",b:"Nek'zali the Soulcoiler",ic:"8095063",id:268240,p:["Agi", "Int"],x:[["Crit", 39], ["Haste", 21]]},
   {n:"Crown of the Eternal Fang",sl:"Head",ty:"Mail",b:"Nek'zali the Soulcoiler",ic:"inv_helm_mail_raidshamanulatek_d_01",id:268230,p:["Agi", "Int"],x:[["Crit", 72], ["Mastery", 34]]},
   {n:"Soulslither Spaulders",sl:"Shoulder",ty:"Mail",b:"Nek'zali the Soulcoiler",ic:"inv_shoulder_mail_raidshamanulatek_d_01",id:268231,p:["Agi", "Int"],x:[["Mastery", 56], ["Crit", 24]]},
   {n:"Cursed Reliquary Cincture",sl:"Waist",ty:"Mail",b:"Nek'zali the Soulcoiler",ic:"inv_belt_mail_raidevokerulatek_d_01",id:268216,p:["Agi", "Int"],x:[["Crit", 56], ["Vers", 24]]},
   {n:"Skullguard of the Risen Sacrifice",sl:"Head",ty:"Plate",b:"Nek'zali the Soulcoiler",ic:"inv_helm_plate_raiddeathknightulatek_d_01",id:268229,p:["Str", "Int"],x:[["Haste", 74], ["Crit", 32]]},
   {n:"Entombed Cultist's Sabatons",sl:"Feet",ty:"Plate",b:"Nek'zali the Soulcoiler",ic:"inv_boot_plate_raidwarriorulatek_d_01",id:268245,p:["Str", "Int"],x:[["Crit", 56], ["Haste", 23]]},
   {n:"Strongblood's Ceremonial Cleaver",sl:"One-hand",ty:"Axe",b:"Nek'zali the Soulcoiler",ic:"inv_axe_1h_ulatek_d_01",id:268208,p:["Str"],x:[["Mastery", 34], ["Crit", 18]]},
   {n:"Hexing Spiritrender",sl:"One-hand",ty:"Dagger",b:"Nek'zali the Soulcoiler",ic:"inv_knife_1h_ulatek_d_02",id:268203,p:["Int"],x:[["Mastery", 37], ["Crit", 16]]},
   {n:"Tomb-Creeper's Claw",sl:"One-hand",ty:"Fist",b:"Nek'zali the Soulcoiler",ic:"inv_hand_1h_ulatek_d_01",id:270930,p:["Agi"],x:[["Haste", 37], ["Crit", 16]]},
   {n:"Bubblefin Splash Guard",sl:"Off-hand",ty:"Shield",b:"Nek'zali the Soulcoiler",ic:"inv_shield_1h_ulatek_d_01",id:268262,p:["Str", "Int"],x:[["Mastery", 39], ["Haste", 19]]},
   {n:"Frostscale's Mystic Frond",sl:"Off-hand",ty:"Off-hand",b:"Nek'zali the Soulcoiler",ic:"inv_offhand_1h_ulatek_d_01",id:268263,p:["Int"],x:[["Crit", 41], ["Mastery", 19]]},
   {n:"Amani Summoning Shawl",sl:"Back",ty:"Cloak",b:"Nek'zali the Soulcoiler",ic:"inv_cape_leather_raidmonkulatek_d_01",id:268248,p:["Agi", "Str", "Int"],x:[["Crit", 42], ["Vers", 18]]},
   {n:"Alluring Bubbleband",sl:"Ring",ty:"Ring",b:"Nek'zali the Soulcoiler",ic:"inv_70_raid_ring8c",id:268266,x:[["Haste", 123], ["Vers", 35]]},
   {n:"Soulcoiler Ritual Vessel",sl:"Trinket",ty:"Trinket",b:"Nek'zali the Soulcoiler",ic:"inv_121_trinket_raid_ulatek_ritualvessel",id:270162,p:["Int"],ro:["healer"],u:"Call forth 5 Soulcoiler Cultist spirits over 2 sec and sacrifice their essence, each granting an ally a barrier reducing damage taken by 50% for 20 sec or until a large amount of damage has been prevented."}]},

 /* ── 2 · ENTOMBED SENTINELS · Sentinel wing ──────────────────────────── */
 {id:"entombed-sentinels",o:2,n:"Entombed Sentinels",short:"Sentinels",
  pos:"Sentinel wing · after Nek'zali, either wing first",lv:2,
  sub:"Two golems, two raids, and a maths exam",
  brief:"Breath of Ula'tek and Blood of Ula'tek, fought by two half-raids at once. Two rules run the whole fight — keep them 40 yards apart, keep their health even — and then the intermission asks twenty people to add to four without panicking. The famous puddle economy is entirely a Heroic problem: on Normal nothing leaves a stain and both groups reuse the same corners all night.",
  reads:[{by:"Method",t:"A standard council fight until the intermission, which will produce more clips than the rest of the tier combined. The first fight in the raid where coordination beats raw damage. Rated 4/5.",s:["me_sen"]}],
  phases:[
   {n:"Both golems",trigger:"The whole fight, split raid",a:[
    {n:"Ula'tek's Dominance",t:["shield"],c:["position"],r:["tank"],sev:3,
     e:"Within 40 yards of each other the golems take 99% less damage.",
     h:"Tank them on opposite sides, split the raid evenly, and keep the damage even too — Vitriolic Stasis refunds any lead by healing the weaker golem up to the stronger.",
     s:["iv_sen","me_sen","wg_va"]},
    {n:"Mark of Acid",t:["dot","stacking"],c:["unavoidable","topoff"],r:["healer"],sev:2,
     e:"Each golem stacks its own 40-second DoT on everyone in range; the end of every sequence is the loudest part.",
     h:"Both groups and both tanks swap sides at every intermission so the old side's stacks fall off. Multi-dotters greeding both bosses collect both marks — keep it short.",
     s:["iv_sen","me_sen"]}]},
   {n:"Breath of Ula'tek",trigger:"The green golem's side",a:[
    {n:"Toxic Droplets",t:["soak","denial"],c:["soak","spread"],r:["dps"],sev:2,
     e:"Venom droplets litter the ground and detonate raid-wide if left; stepping on one destroys it for a hit and a small DoT.",
     h:"One or two per player, spread the work — nobody hero-soaks three, though tanks make the cheapest soakers in the room.",
     hh:"Destroyed droplets release Living Venom that travels back toward the boss, damaging the path — clear droplets, then stand somewhere the return trip isn't through the raid. The sources describe its origin differently; see the open questions.",
     s:["iv_sen","me_sen"]},
    {n:"Venom Coagulation",t:["adds","groupdmg"],c:["focus"],r:["dps"],sev:3,
     e:"A venom blob that pulses raid damage for as long as it lives.",
     h:"The instant priority target for the green group, every time.",
     s:["iv_sen","me_sen"]},
    {n:"Empowering Slam",t:["tankbuster","stacking","amp"],c:["defensive"],r:["tank"],sev:2,
     e:"Heavy Physical hits that ramp on the same target and only reset on a new one.",
     h:"There is no second tank on your side — which is exactly why tanks trade golems at the intermission. He casts it three or four times a phase, so the end of a long phase is where the defensives belong.",
     s:["iv_sen","me_sen"]}]},
   {n:"Blood of Ula'tek",trigger:"The red golem's side — the harder half",a:[
    {n:"Unstable Miasma",t:["soak","groupdmg"],c:["soak","position"],r:["healer","dps"],sev:3,
     e:"A marked player detonates after a few seconds for damage split among everyone nearby, smearing every soaker with Clinging Murk.",
     h:"Five players can split it; more is fine but on Heroic every extra soaker is an extra puddle. Soak, then walk the group to a designated corner before the drops land — the red side starts in a corner precisely so the walls can hold its mess.",
     hh:"Clinging Murk drops a Blood Venom pool as it expires — the space budget is the real boss on this side.",
     s:["iv_sen","me_sen","wg_va"]},
    {n:"Blighted Blood",t:["debuff","dot"],c:["magic"],r:["healer"],sev:2,
     e:"A dispellable Shadow DoT.",
     h:"Dispel on sight — the opposite of Nek'zali's rule — so a second dispel fits before it expires. Watch both halves: the debuff can land on either side of the split.",
     hh:"A natural expiry leaves a pool: if you weren't dispelled, walk it next to existing pools and waste no floor.",
     s:["iv_sen"]},
    {n:"Bloodvenom Injection",t:["tankbuster","stacking","dot"],c:["defensive","position"],r:["tank"],sev:2,
     e:"A ramping tank hit whose debuff drops a massive pool when it runs out.",
     h:"Roughly four injections a phase, and the expiry lands after the swap, while you're tanking the other golem — walk to a wall in advance. Physics matter: dropped on clean floor the puddle stays put; dropped onto an existing one it slides somewhere you didn't choose.",
     s:["iv_sen","me_sen"]}]},
   {n:"Intermission — Vitriolic Stasis",trigger:"At 100 energy both charge the middle",a:[
    {n:"Vitriolic Stasis",t:["heal","channel"],c:["unavoidable"],r:["dps"],sev:2,
     e:"For 30 seconds the golems are near-immune and the weaker heals up to match the stronger.",
     h:"The refund mechanism that makes balance mandatory. Use the downtime to solve the toxins; swap sides when it ends.",
     s:["iv_sen","me_sen","wg_va"]},
    {n:"Helical Toxins",t:["debuff","spread"],c:["position","immune"],r:["dps","healer","tank"],sev:3,
     e:"Everyone is infected and must pair off so their counts total exactly four.",
     h:"Pre-spread before the intermission begins, then walk, read, pair — the bosses are immune throughout, so the only enemy is panic. Mistakes go to a designated punishment corner; a full immunity survives the failure. The three sources describe the counting differently; see the open questions.",
     hh:"Overfilling kills outright instead of knocking back.",
     s:["iv_sen","me_sen","wg_va"]}]}],
  loot:[
   {n:"Venom-Singed Cuffs",sl:"Wrist",ty:"Cloth",b:"Entombed Sentinels",ic:"inv_bracer_cloth_raidmageulatek_d_01",id:268228,p:["Int"],x:[["Mastery", 39], ["Crit", 21]]},
   {n:"Shadow Hunter's Warmask",sl:"Head",ty:"Leather",b:"Entombed Sentinels",ic:"inv_helm_leather_raidrogueulatek_d_01",id:268219,p:["Agi", "Int"],x:[["Mastery", 70], ["Vers", 36]]},
   {n:"Venom Warden's Greaves",sl:"Legs",ty:"Plate",b:"Entombed Sentinels",ic:"inv_pant_plate_raidwarriorulatek_d_01",id:268224,p:["Str", "Int"],x:[["Haste", 72], ["Mastery", 34]]},
   {n:"Ancient Construct's Venomshiv",sl:"One-hand",ty:"Dagger",b:"Entombed Sentinels",ic:"inv_knife_1h_ulatek_d_01",id:268204,p:["Agi"],x:[["Haste", 37], ["Vers", 16]]},
   {n:"Caustic Keeper-Crusher",sl:"Two-hand",ty:"Mace",b:"Entombed Sentinels",ic:"inv_mace_2h_ulatek_d_01",id:268198,p:["Str"],x:[["Crit", 73], ["Haste", 33]]},
   {n:"Spine of the Hissing Abyss",sl:"Off-hand",ty:"Off-hand",b:"Entombed Sentinels",ic:"inv_offhand_1h_ulatek_d_01",id:268197,p:["Int"],x:[["Mastery", 41], ["Haste", 18]]},
   {n:"Sentinel's Vitriolic Chain",sl:"Neck",ty:"Neck",b:"Entombed Sentinels",ic:"inv_121_jewelry_neck02_green",id:268250,x:[["Haste", 121], ["Crit", 36]]},
   {n:"Keeper's Seething Core",sl:"Trinket",ty:"Trinket",b:"Entombed Sentinels",ic:"inv_121_trinket_raid_ulatek_golemhearts_green",id:270165,p:["Agi", "Str"],ro:["tank","mdps"],e:"Your attacks have a high chance to grant you Focus of Ula'tek, increasing your Haste by a moderate amount for 12 sec. Multiple applications may overlap."},
   {n:"Venomwoven Idol",sl:"Hands",ty:"Token",tc:"Cloth",b:"Entombed Sentinels",ic:"inv_jewelcrafting_azureserpent",id:270910},
   {n:"Venomcured Idol",sl:"Hands",ty:"Token",tc:"Leather",b:"Entombed Sentinels",ic:"inv_jewelcrafting_purpleserpent",id:270911},
   {n:"Venomcast Idol",sl:"Hands",ty:"Token",tc:"Mail",b:"Entombed Sentinels",ic:"inv_jewelcrafting_goldenserpent",id:270912},
   {n:"Venomforged Idol",sl:"Hands",ty:"Token",tc:"Plate",b:"Entombed Sentinels",ic:"inv_jewelcrafting_rubyserpent",id:270913}]},

 /* ── 3 · VASHNIK THE MALIGNANT · Sentinel wing ───────────────────────── */
 {id:"vashnik",o:3,n:"Vashnik the Malignant",short:"Vashnik",
  pos:"Sentinel wing · follows the Sentinels",lv:2,
  sub:"The alchemist drinks from two fountains, and you pick which",
  brief:"Three venom fountains ring the room — Flame, Blood, Shadow — and every Imbibe empowers the two nearest, spawning that flavour of add. Boss position IS the mechanic: you are choosing your poison, literally, roughly every 90 seconds.",
  phases:[
   {n:"The rotation",trigger:"Continuous — Imbibe about every 90 seconds",a:[
    {n:"Imbibe",t:["groupdmg","stacking","adds"],c:["position","preposition"],r:["tank","healer"],sev:3,
     e:"He drinks from the two fountains nearest him, gaining a stacking infusion — his damage of that venom type doubles and the matching adds gain half again as much health per stack.",
     h:"Park him between the two fountains you want and rotate — never the same fountain more than twice running. The Blood fountain sits further out than it looks: crossing the floor line is not enough, actually get there. Tactyks opens at Flame+Blood with Death Grips pulling the burning adds in, then walks clockwise — it delays the double-Flame window until the fourth drink.",
     s:["iv_vas"]},
    {n:"Malignant Burst",t:["groupdmg","adds"],c:["focus","kite"],r:["dps"],sev:3,
     e:"Every summoned add crawls for the Malignant Cavity in the centre; any that arrives detonates against the whole raid.",
     h:"Kill order: Burning Venoms, then Clotting Venom, then Shrouded Venoms. Nothing reaches the middle.",
     s:["iv_vas","wg_va"]},
    {n:"Plague Froth",t:["line","spread"],c:["position","dodge"],r:["dps"],sev:1,
     e:"Marked players — fewer of them on Normal and Heroic than above — grow four cardinal wave-lines that fire when the debuff expires.",
     h:"Point the cross away from the raid and never through the boss — a diagonal stance costs nothing.",
     s:["iv_vas","tk_va"]},
    {n:"Dripping Fangs",t:["tankbuster","stacking","amp"],c:["defensive"],r:["tank"],sev:2,
     e:"Less a hit than a damage amp — a second stack is the thing that kills tanks here.",
     h:"Defensive through the cast, then wait the few seconds for your co-tank's stack to drop before taunting — a swap onto live stacks defeats the point. Positioning him is the rest of the tank job.",
     s:["iv_vas","tk_vtk"]},
    {n:"Catalytic Bile",t:["soak"],c:["soak","spread"],r:["rdps"],sev:2,df:["h"],
     e:"Soak circles scatter the floor, each wanting exactly one body.",
     h:"Ranged spread around him rather than trailing him — coverage beats reaction — and the active tank can cheaply eat any that land at the boss's feet.",
     s:["iv_vas","tk_vtk"]}]},
   {n:"Fountain of Flame",trigger:"When Flame is drunk — Conflagrating Expulsion",a:[
    {n:"Burning Venoms",t:["adds","groupdmg","death"],c:["focus","stack"],r:["dps","healer"],sev:3,
     e:"Two fire elementals pulse raid damage while alive and detonate a Caustic Surge on death.",
     h:"Highest priority in the room — grip them in one at a time and kill them staggered; a lust-and-AMZ start eats the first set whole, but that trick only works once.",
     hh:"The death surge is a DoT: kill them staggered, because two at once can be lethal.",
     s:["iv_vas"]},
    {n:"Exploding Infection",t:["debuff","spread"],c:["position","magic","topoff"],r:["healer","dps"],sev:2,
     e:"A fire circle and an arrow: the carrier runs out and detonates, hitting softer the further they get.",
     h:"Heal the runner on the way out; the dispel itself is the detonation, so cleanse one at a time, at distance — never all of them in a panic.",
     s:["iv_vas"]}]},
   {n:"Fountain of Blood",trigger:"When Blood is drunk — Hemo Expulsion",a:[
    {n:"Clotting Venom",t:["adds"],c:["focus","cc"],r:["dps"],sev:2,
     e:"One blob that splits in two on death, and those split again — three generations of walkers, one to two to four.",
     h:"Finish it deliberately: every split is a fresh set heading for the middle. Whether anything after the first generation can be controlled is contested — see the open questions — so plan as if none of it can.",
     s:["iv_vas","wg_va","tk_va"]},
    {n:"Siphoning Infection",t:["absorb","debuff"],c:["stack","position"],r:["healer","dps"],sev:2,
     e:"A huge healing absorb that healing cannot touch — the carrier drains health from anyone standing in their circle instead.",
     h:"Stand on your infected friend — it is the one mechanic in the wing where body-blocking is the cure, and a tank parked in the overlap of two circles heals both carriers at once.",
     s:["iv_vas"]}]},
   {n:"Fountain of Shadow",trigger:"When Shadow is drunk — Gloom Expulsion",a:[
    {n:"Shrouded Venoms",t:["adds","shield","death","denial"],c:["kite","cc"],r:["dps"],sev:1,
     e:"Five shielded shades, the lowest kill priority, that each leave an Umbral Ejection zone on death.",
     h:"Slow them and let cleave handle it — grip fire adds on top of them when Flame is also up.",
     s:["iv_vas"]},
    {n:"Stygian Infection",t:["absorb","debuff","denial"],c:["mobility","topoff"],r:["healer","dps"],sev:2,
     e:"The carrier trails Stygian Burst wherever they stand and wears a healing absorb.",
     h:"Keep moving, near the raid but not through it — outrunning healer range is how this kills.",
     s:["iv_vas"]}]}],
  loot:[
   {n:"Frothing Venom Spaulders",sl:"Shoulder",ty:"Leather",b:"Vashnik the Malignant",ic:"inv_shoulder_leather_raiddemonhunterulatek_d_01",id:268246,p:["Agi", "Int"],x:[["Crit", 52], ["Mastery", 27]]},
   {n:"Serpentine Mixing Belt",sl:"Waist",ty:"Mail",b:"Vashnik the Malignant",ic:"inv_belt_mail_raidshamanulatek_d_01",id:268254,p:["Agi", "Int"],x:[["Mastery", 54], ["Haste", 24]]},
   {n:"Scaled Fiend's Warboots",sl:"Feet",ty:"Plate",b:"Vashnik the Malignant",ic:"inv_boot_plate_raidpaladinulatek_d_01",id:268260,p:["Str", "Int"],x:[["Mastery", 54], ["Haste", 24]]},
   {n:"Venomancer's Winged Channeler",sl:"Two-hand",ty:"Staff",b:"Vashnik the Malignant",ic:"inv_staff_2h_ulatek_d_02",id:268205,p:["Int"],x:[["Mastery", 73], ["Haste", 33]]},
   {n:"Malignant Toothed Edge",sl:"Two-hand",ty:"Sword",b:"Vashnik the Malignant",ic:"inv_sword_2h_ulatek_d_01",id:268214,p:["Str"],x:[["Haste", 70], ["Mastery", 36]]},
   {n:"Vile Alchemist's Band",sl:"Ring",ty:"Ring",b:"Vashnik the Malignant",ic:"inv_121_jewelry_ring01_purple",id:268249,x:[["Mastery", 129], ["Crit", 28]]},
   {n:"Vashnik's Sanguine Rancor",sl:"Trinket",ty:"Trinket",b:"Vashnik the Malignant",ic:"inv_11_0_raid_gruesomesyringe_blue",id:270166,p:["Agi"],ro:["tank","mdps"],e:"Your attacks have a very high chance to build sanguine rancor within you. After 15 times, the rancor erupts to scourge your target and all nearby enemies with crimson bile, dealing heavy Shadow damage split between them. Damage increased by 30% per additional enemy, up to 150%."},
   {n:"Fang of Umbral Malignance",sl:"Trinket",ty:"Trinket",b:"Vashnik the Malignant",ic:"inv_121_trinket_raid_ulatek_fang_purple",id:270161,p:["Int"],ro:["rdps"],e:"Your harmful spells have a very high chance to befoul your target with Umbral Malignance, dealing Shadow damage every 3 sec for 1 min, stacking up to 30 times."},
   {n:"Venomwoven Icon",sl:"Chest",ty:"Token",tc:"Cloth",b:"Vashnik the Malignant",ic:"inv_jewelcrafting_azureserpent",id:270926},
   {n:"Venomcured Icon",sl:"Chest",ty:"Token",tc:"Leather",b:"Vashnik the Malignant",ic:"inv_jewelcrafting_purpleserpent",id:270927},
   {n:"Venomcast Icon",sl:"Chest",ty:"Token",tc:"Mail",b:"Vashnik the Malignant",ic:"inv_jewelcrafting_goldenserpent",id:270928},
   {n:"Venomforged Icon",sl:"Chest",ty:"Token",tc:"Plate",b:"Vashnik the Malignant",ic:"inv_jewelcrafting_rubyserpent",id:270929}]},

 /* ── 4 · THE LOST EXPLORERS · Explorer wing ──────────────────────────── */
 {id:"lost-explorers",o:4,n:"The Lost Explorers",short:"Explorers",
  pos:"Explorer wing · after Nek'zali, either wing first",lv:2,
  sub:"Three tortollans, one puppeteer, and a fish",
  brief:"A three-target council — Trader Gebbo, First Mate Nama, Scrollsage Iku — enslaved by the sorcerer Mor'zahi, who builds toward a raid-ending Empower. Feeding a boss the Grab Fish detonates its ultimate on your schedule instead of his.",
  phases:[
   {n:"The council",trigger:"All three at once; lust on pull",a:[
    {n:"United Defense",t:["shield"],c:["position"],r:["tank"],sev:3,df:["h"],
     e:"On Heroic, all three within 30 yards of each other take 99% less damage. On Normal the aura does not exist.",
     h:"Lust on the pull either way. On Normal, stack everything on Gebbo — he can't be tanked and just patrols, so bring the other two to him and cleave. On Heroic keep Iku and Nama paired away from Gebbo's route and rotate the pairing — all three must die together.",
     s:["iv_exp","tk_va","tk_vtk"]},
    {n:"Throw Junk",t:["soak","dot"],c:["soak","position"],r:["dps"],sev:3,
     e:"Gebbo scatters crates that break underfoot for stacking Splinters bleeds — a crate left standing twenty-five seconds detonates against the raid, and one of them holds the Grab Fish.",
     h:"Find the fish, carry it to the chosen boss, and feed at 90–95 of Mor'zahi's energy: the feed resets his bar and fires that boss's ultimate, and each boss can only be picked once — three fish, three resets, and then Final Ascension completes and the raid is over. Order: Gebbo, then Nama, then Iku. Tanks are cheap crate-poppers: a bleed cleanse, even the dwarf racial, wipes the Splinters.",
     s:["iv_exp","wg_va"]},
    {n:"Shell Spin",t:["frontal","stun"],c:["position","dodge"],r:["tank","mdps"],sev:2,
     e:"Nama fires three turtle shells in a cone at a random melee — tanks included; a hit is a four-second stun.",
     h:"Melee and tanks hold the outside of the room so every bait fires away from the ranged playing inside, then step out. It never overlaps Mighty Thud.",
     s:["iv_exp","tk_vtk"]},
    {n:"Icebound Flames",t:["channel"],c:["interrupt"],r:["dps"],sev:2,
     e:"Iku's cast, and it must never finish.",
     h:"A two-to-three player kick rotation owns this for the whole fight; the tank helps when position allows.",
     s:["iv_exp"]},
    {n:"Blink Nova",t:["groupdmg"],c:["spread","position"],r:["healer","dps"],sev:2,
     e:"Iku teleports to a marked player and detonates, hitting softer with distance.",
     h:"The mark walks away from the raid; everyone else keeps their spacing — without wandering so far the cleave dies. One source says the mark is always ranged, another saw it land on anyone; either way the job is the same.",
     s:["iv_exp","wg_va","tk_va"]},
    {n:"Shredding Shards",t:["tankbuster","stacking"],c:["defensive"],r:["tank"],sev:2,
     e:"Iku's roughly seven-hit channel, each tick harder than the last — while Nama's Steady Strikes stack a Physical amp on whoever holds him.",
     h:"Defensive through the channel and swap AFTER it ends — never before Nama's stacks have dropped off, because taunting early refreshes them onto the wrong tank and that is how tanks die here.",
     s:["iv_exp","tk_vtk"]}]},
   {n:"The ultimates",trigger:"One per fed boss, on your schedule",a:[
    {n:"Explosive Surprise",t:["soak","knockback"],c:["position","mobility"],r:["dps"],sev:3,
     e:"Gebbo's bombs mark players while Bouncy Mushrooms sprout near the raid — about five on Normal, two or three on Heroic; each detonation sends a Blast Wave across the whole platform.",
     h:"Park bombs at the edge away from the mushrooms, then time your bounce — wait for the wave, jump it, and share the mushroom; it dies a few seconds after first touch. Going early strands everyone behind you.",
     hh:"The detonation also leaves a giant puddle that Normal never sees.",
     s:["iv_exp","tk_va"]},
    {n:"Mighty Thud",t:["soak","knockback"],c:["soak","preposition"],r:["healer","dps"],sev:3,
     e:"Nama marks three players and leaps to each in turn, splitting each landing among everyone within six yards — an empty landing hits the entire raid.",
     h:"Two schools both work: three assigned soak groups on markers, or line the three marks up and walk the whole raid through them in order, eating each split together. Pick one before the pull, not during.",
     s:["iv_exp","wg_va"]},
    {n:"Frostfire Volley",t:["groupdmg","denial","dot"],c:["position","topoff"],r:["healer","mdps","rdps","tank"],sev:3,
     e:"Frost marks the melee — tanks included — and fire marks the ranged; every expiry drops a nasty DoT on its carrier and a patch on the floor.",
     h:"Carry them to the edges, then clear in pairs: a frost carrier touches a fire patch and vice versa, each clear costing a raid hit — so stagger them, don't race. The hardest of the three ultimates, and the whole volley is a healing-cooldown window.",
     s:["iv_exp","wg_va","tk_va","tk_vtk"]}]}],
  loot:[
   {n:"Errant Scrollsage's Hood",sl:"Head",ty:"Cloth",b:"The Lost Explorers",ic:"inv_helm_cloth_raidpriestulatek_d_01",id:268242,p:["Int"],x:[["Haste", 75], ["Crit", 31]]},
   {n:"Unpossessed Skullsash",sl:"Waist",ty:"Leather",b:"The Lost Explorers",ic:"inv_belt_leather_raidrogueulatek_d_01",id:268227,p:["Agi", "Int"],x:[["Crit", 57], ["Mastery", 23]]},
   {n:"Boots of the Reckless Wayfarer",sl:"Feet",ty:"Mail",b:"The Lost Explorers",ic:"inv_boot_mail_raidevokerulatek_d_01",id:268258,p:["Agi", "Int"],x:[["Crit", 53], ["Mastery", 26]]},
   {n:"Shellbound Bracers",sl:"Wrist",ty:"Plate",b:"The Lost Explorers",ic:"inv_bracer_plate_raiddeathknightulatek_d_01",id:268239,p:["Str", "Int"],x:[["Mastery", 42], ["Crit", 18]]},
   {n:"Malevolent Spiritcudgel",sl:"One-hand",ty:"Mace",b:"The Lost Explorers",ic:"inv_mace_1h_ulatek_d_01",id:268210,p:["Int"],x:[["Mastery", 37], ["Crit", 16]]},
   {n:"Gebbo's Backup Blaster",sl:"Ranged",ty:"Gun",b:"The Lost Explorers",ic:"inv_firearm_2h_ulatek_d_01",id:268200,p:["Agi"],x:[["Haste", 37], ["Mastery", 16]]},
   {n:"Venom-Slashed Scuteward",sl:"Off-hand",ty:"Shield",b:"The Lost Explorers",ic:"inv_shield_1h_ulatek_d_01",id:268196,p:["Str", "Int"],x:[["Haste", 39], ["Crit", 19]]},
   {n:"First Mate's Shellward",sl:"Trinket",ty:"Trinket",b:"The Lost Explorers",ic:"inv_cape_special_turtleshell_c_02",id:270160,p:["Agi", "Str"],ro:["tank"],u:"Deploy the Shellward to absorb up to 40% of incoming damage, up to a large amount, for up to 30 sec. The Shellward hardens while you are below 40% health, reducing damage by 80% instead."},
   {n:"Gebbo's Bottomless Bag",sl:"Trinket",ty:"Trinket",b:"The Lost Explorers",ic:"inv_10_tailoring_bag1_color2",id:270164,p:["Agi", "Str", "Int"],ro:["tank","healer","rdps","mdps"],e:"You have a chance to pull an artifact of questionable value out of the bag when casting spells and abilities, enhancing your secondary stats in various ways. There are probably no fish left in the bag, but it's hard to be sure. (750ms cooldown)"},
   {n:"Venomwoven Remnant",sl:"Shoulder",ty:"Token",tc:"Cloth",b:"The Lost Explorers",ic:"inv_jewelcrafting_azureserpent",id:270922},
   {n:"Venomcured Remnant",sl:"Shoulder",ty:"Token",tc:"Leather",b:"The Lost Explorers",ic:"inv_jewelcrafting_purpleserpent",id:270923},
   {n:"Venomcast Remnant",sl:"Shoulder",ty:"Token",tc:"Mail",b:"The Lost Explorers",ic:"inv_jewelcrafting_goldenserpent",id:270924},
   {n:"Venomforged Remnant",sl:"Shoulder",ty:"Token",tc:"Plate",b:"The Lost Explorers",ic:"inv_jewelcrafting_rubyserpent",id:270925}]},

 /* ── 5 · SSZORAK · Explorer wing ─────────────────────────────────────── */
 {id:"sszorak",o:5,n:"Sszorak",short:"Sszorak",
  pos:"Explorer wing · follows the Explorers",lv:2,
  sub:"Read the winds on pull, or the intermission reads you",
  brief:"An apex predator on the Altar of Six Winds. The fight's homework happens in its first three seconds: the wind motes on the tunnels tell you the intermission's push order, and everything you place before then decides whether the hurricane is a plan or a wipe.",
  reads:[{by:"Tactyks",t:"Shaping up to be the favourite boss of the raid — it barely changed across the whole PTR cycle, which is usually the sign they got it right early.",s:["tk_va","tk_vtk"]}],
  phases:[
   {n:"Main phase",trigger:"Intermission roughly every two minutes",a:[
    {n:"Apex Predator",t:["tankbuster","frontal"],c:["defensive","soak","dodge","poison"],r:["tank","dps"],sev:3,
     e:"A five-attack combo in random order: two Ravages (tank-only, faced away), two Mutilates (raid-split soaks), one Tempest — tornadoes that land a dispellable poison slow.",
     h:"The frontals telegraph mid-cast, so never pre-taunt: see which it is, then act. Mutilate splits fully and needs no defensive — save them for Ravage, and let whoever has fewer amp stacks take the next one. Poison dispels quietly earn a slot here for the tornado slows.",
     hh:"Mutilate soakers take 500% increased damage from the next one — two alternating soak groups, unless you brought that Blood DK.",
     s:["iv_ssz"]},
    {n:"Venomous Surge",t:["debuff","denial"],c:["preposition","position"],r:["dps","healer"],sev:3,
     e:"Drenched players drop a Viscous Cyst where the debuff expires — and those cysts are the survival plan for the hurricane.",
     h:"On pull, read the wind motes and mark the drop spots opposite each tunnel — two carriers per cast, four cysts a phase for three tunnels, so the spare gets detonated deliberately at centre-room early next phase rather than left to surprise someone. Boss tanked well away, and from the pull tank him at the edge: the cyst drop hurts up close and the placement is the fight.",
     hh:"He also rakes Caustic Claws during it, littering 30%-amp residue pools — tank him toward an edge the intermission will sweep clean.",
     s:["iv_ssz"]},
    {n:"Raging Crosswinds",t:["knockback","spread"],c:["position"],r:["dps","healer"],sev:2,
     e:"Most of the raid gets a wind pushing one of two directions.",
     h:"Find a partner blowing the other way and collide — two winds cancel mid-air and drop you where you started. Never burn a knockback immunity on it: the winds come in exactly even pairs, and cancelling yours strands someone else partnerless.",
     s:["iv_ssz"]},
    {n:"Corroding Venom",t:["tankbuster","stacking"],c:["defensive"],r:["tank"],sev:2,
     e:"The stacking swap debuff underneath the combo.",
     h:"Around six stacks, which lines up with the combo's natural swap points.",
     s:["iv_ssz"]}]},
   {n:"Intermission — Howling Maelstrom",trigger:"The altar takes over",a:[
    {n:"Howling Maelstrom",t:["knockback","env"],c:["preposition","position"],r:["dps","healer","tank"],sev:3,
     e:"The wind tunnels fire in mote order and shove the raid across the platform; pools pushed over the edge are deleted.",
     h:"Get thrown into the cyst you placed opposite the active tunnel and it bounces you safely back — then re-centre before the next tunnel fires so the throw is straight. This is why the fight started with reading the room.",
     s:["iv_ssz"]},
    {n:"Dig In",t:["channel"],c:["focus"],r:["dps"],sev:1,
     e:"He hunkers through the storm taking 30% increased damage for 25 seconds.",
     h:"The burn window — plan two-minute cooldowns around it.",
     s:["iv_ssz","wg_va"]}]}],
  loot:[
   {n:"Caustic Chain-Wrapped Sash",sl:"Waist",ty:"Cloth",b:"Sszorak",ic:"inv_belt_cloth_raidwarlockulatek_d_01",id:268257,p:["Int"],x:[["Haste", 54], ["Mastery", 26]]},
   {n:"Ruthless Slaughtergrips",sl:"Hands",ty:"Leather",b:"Sszorak",ic:"inv_glove_leather_raiddemonhunterulatek_d_01",id:268234,p:["Agi", "Int"],x:[["Mastery", 54], ["Crit", 26]]},
   {n:"Ferocious Scaleboots",sl:"Feet",ty:"Mail",b:"Sszorak",ic:"inv_boot_mail_raidhunterulatek_d_01",id:268233,p:["Agi", "Int"],x:[["Mastery", 56], ["Haste", 24]]},
   {n:"Venomous Boneglaive",sl:"One-hand",ty:"Warglaive",b:"Sszorak",ic:"inv_glaive_1h_ulatek_d_01",id:268201,p:["Agi", "Int"],x:[["Mastery", 37], ["Crit", 16]]},
   {n:"Slithering Savage's Gavel",sl:"One-hand",ty:"Mace",b:"Sszorak",ic:"inv_mace_1h_ulatek_d_01",id:268206,p:["Agi"],x:[["Crit", 37], ["Mastery", 16]]},
   {n:"Apex Brute's Claw Ring",sl:"Ring",ty:"Ring",b:"Sszorak",ic:"inv_121_jewelry_ring03_red",id:268252,x:[["Crit", 132], ["Haste", 26]]},
   {n:"Sszorak's Ferocity",sl:"Trinket",ty:"Trinket",b:"Sszorak",ic:"inv_121_trinket_raid_ulatek_ulatekclaw",id:270163,p:["Str"],ro:["tank","mdps"],e:"You have a high chance to follow up your attacks with Ravage, Mutilate, or Tempest based on the number of nearby enemies."},
   {n:"Idol of the Howling Nexus",sl:"Trinket",ty:"Trinket",b:"Sszorak",ic:"inv_jewelcrafting_jadeserpent",id:270174,x:[["Mastery", 75]],e:"Dodging, parrying, or blocking has a high chance to call bolstering winds, granting a large amount of Strength or Agility and of Speed for 12 sec.",ro:["tank"]},
   {n:"Venomwoven Relic",sl:"Legs",ty:"Token",tc:"Cloth",b:"Sszorak",ic:"inv_jewelcrafting_azureserpent",id:270918},
   {n:"Venomcured Relic",sl:"Legs",ty:"Token",tc:"Leather",b:"Sszorak",ic:"inv_jewelcrafting_purpleserpent",id:270919},
   {n:"Venomcast Relic",sl:"Legs",ty:"Token",tc:"Mail",b:"Sszorak",ic:"inv_jewelcrafting_goldenserpent",id:270920},
   {n:"Venomforged Relic",sl:"Legs",ty:"Token",tc:"Plate",b:"Sszorak",ic:"inv_jewelcrafting_rubyserpent",id:270921}]},

 /* ── 6 · THE TWIN FANGS · the wings converge ─────────────────────────── */
 {id:"twin-fangs",o:6,n:"The Twin Fangs",short:"Twin Fangs",
  pos:"Where the wings converge — both wings first",lv:3,
  sub:"Vexhul poisons you; Ithraz is the antidote, and he bites",
  brief:"Two serpents, no shared health, killed together. Everything stacks Eternal Venom on you, and the only cleanse is deliberately standing in Ithraz's Ravenous Feast — the raid managing its own poison budget through a bite. Three phases of shrinking floor, then the room is simply gone.",
  phases:[
   {n:"Both serpents",trigger:"The venom economy runs the whole fight",a:[
    {n:"Eternal Venom",t:["dot","stacking","debuff"],c:["soak","topoff"],r:["healer","dps","tank"],sev:3,
     e:"A permanent stacking poison fed by half the kit, lethal at its cap — eleven stacks on Normal; each Ravenous Feast hit removes exactly one.",
     h:"Track stacks like a resource — who soaks what is decided by who can afford it. And stay inside the serpents' generous hitboxes: leave melee range of either and it spams bolts that hurt more than anything you were dodging.",
     hh:"The cap tightens to ten.",
     s:["iv_twf","wg_va","tk_va","tk_vtk"]}]},
   {n:"Vexhul",trigger:"The poisoner",a:[
    {n:"Caustic Deluge",t:["tankbuster","knockback"],c:["position","soak"],r:["tank","dps"],sev:2,
     e:"A pushback beam on the tank that spawns Caustic Globules along the way.",
     h:"One of the raid's genuinely dangerous tank moments: big defensive AND a movement ability, because the push is aggressive and leaving the hitbox starts the bolts. Low-stack players soak the globules — never collect two by accident.",
     s:["iv_twf","tk_vtk"]},
    {n:"Venomous Emergence",t:["adds","groupdmg"],c:["focus","dodge"],r:["dps"],sev:3,
     e:"Three Spawn of Vexhul surface in the centre, gifting the raid a stack each, then rake beams of Corrosive Spit.",
     h:"Kill priority the moment they land; spit targets take one second to reposition, then plant so the beam is dodgeable for everyone else.",
     s:["iv_twf"]},
    {n:"Stir the Depths",t:["env"],c:["dodge"],r:["dps","healer"],sev:1,
     e:"Waves cross the arena, a stack per hit.",
     h:"Note which side they enter from — the surprise is the damage.",
     s:["iv_twf"]}]},
   {n:"Ithraz",trigger:"The cleanse, at a price",a:[
    {n:"Stone Breaker",t:["tankbuster","knockback","soak"],c:["soak","defensive"],r:["tank","mdps"],sev:3,
     e:"A roar knocks the tank away, then three slam zones land at three fixed points — left, centre, right — detonating in the order they spawned; unsoaked slams hit the whole raid.",
     h:"Watch the spawn order and walk it — there's time — with a short defensive saved for hits two and three, which stack. Swap after the set. Melee: the zones land in your space, and walking into one uninvited is an instant obituary.",
     s:["iv_twf","wg_va","tk_vtk"]},
    {n:"Coiling Ichor",t:["debuff","denial"],c:["position"],r:["dps","healer"],sev:2,
     e:"Marked players drop permanent Congealed Gore pools when it expires.",
     h:"Walk to the edge — the circle shrinks as it ticks and the FINAL tick is the killer, so time a defensive for the end. Patience near the wall saves floor the enrage will want back.",
     s:["iv_twf","tk_va"]},
    {n:"Ravenous Feast",t:["soak","knockback"],c:["soak","preposition"],r:["healer","dps"],sev:3,
     e:"Three consecutive split bites; every player hit sheds one Eternal Venom stack and gets knocked back.",
     h:"The antidote. Position so the knock lands you somewhere legal, send the people who need the cleanse most — and on Normal a mobile tank can charge back between bites and eat all three for a triple cleanse. Get back to your serpent fast afterwards; the bolts are waiting.",
     hh:"Feasted allows each player only one of the three bites — three soak teams, planned in advance.",
     s:["iv_twf","wg_va","tk_vtk"]}]},
   {n:"Intermission — Submerge",trigger:"After two full sequences, both dive",a:[
    {n:"Vile Flood",t:["channel","frontal"],c:["preposition","dodge"],r:["dps","healer","tank"],sev:3,
     e:"Vexhul's beam sweeps the platform in a circle, stacking venom on everyone it catches.",
     h:"The orbs circling him pre-cast show the direction — they can spin either way, so actually read them — and it locks in on his tank as it fires, then sweeps about three-quarters of the platform, not the full circle. The raid pre-stacks opposite the tank, dodges against the spin, then follows behind it; the aiming tank needs mobility home before the bolts stack up.",
     s:["iv_twf","tk_vtk"]},
    {n:"Sanguine Storm",t:["env","groupdmg"],c:["dodge","mobility"],r:["dps","healer"],sev:2,
     e:"Ithraz surfaces at a random one of the other two anchor points and rains blood impacts across the platform through the sweep.",
     h:"Sidestep while rotating — two mechanics, one walking pattern — and don't pre-commit to where Ithraz lands, because it varies.",
     hh:"Congealed Gore slows by 60% here, which is how the beam catches people.",
     s:["iv_twf","wg_va"]}]}],
  loot:[
   {n:"Ornaments of the Eternal Coil",sl:"Shoulder",ty:"Cloth",b:"The Twin Fangs",ic:"inv_shoulder_cloth_raidmageulatek_d_01",id:268241,p:["Int"],x:[["Haste", 57], ["Vers", 23]]},
   {n:"Bespittled Slitherslippers",sl:"Feet",ty:"Leather",b:"The Twin Fangs",ic:"inv_boot_leather_raidmonkulatek_d_01",id:268261,p:["Agi", "Int"],x:[["Crit", 56], ["Haste", 24]]},
   {n:"Ophidian Fangmail",sl:"Chest",ty:"Mail",b:"The Twin Fangs",ic:"inv_chest_mail_raidhunterulatek_d_01",id:268223,p:["Agi", "Int"],x:[["Haste", 72], ["Crit", 34]]},
   {n:"Scaleplate Strangulators",sl:"Hands",ty:"Plate",b:"The Twin Fangs",ic:"inv_glove_plate_raidpaladinulatek_d_01",id:268220,p:["Str", "Int"],x:[["Crit", 53], ["Haste", 27]]},
   {n:"Ravenous Feaster's Fang",sl:"One-hand",ty:"Dagger",b:"The Twin Fangs",ic:"inv_knife_1h_ulatek_d_02",id:268264,p:["Agi"],x:[["Mastery", 34], ["Crit", 18]]},
   {n:"Amulet of the Twin Fangs",sl:"Neck",ty:"Neck",b:"The Twin Fangs",ic:"inv_121_jewelry_neck01_red",id:268251,x:[["Mastery", 134], ["Haste", 23]]},
   {n:"Preternatural Antivenom",sl:"Trinket",ty:"Trinket",b:"The Twin Fangs",ic:"inv_11_0_dungeon_tentaclevial_green",id:270171,x:[["Crit", 75]],e:"Your healing has a high chance to infuse the target with Preternatural Antivenom for 30 sec, healing your ally for 75% of any damage they take until a large amount of health has been restored.",ro:["healer"]},
   {n:"Vexhul's Everflowing Gland",sl:"Trinket",ty:"Trinket",b:"The Twin Fangs",ic:"inv_11_0_misc_organmass_color3",id:270170,p:["Int"],ro:["rdps"],u:"Unleash a deluge of caustic venom, dealing heavy Nature damage to your target. Damage increased by 1% for every 1% health the enemy has remaining."},
   {n:"Venomwoven Effigy",sl:"Head",ty:"Token",tc:"Cloth",b:"The Twin Fangs",ic:"inv_jewelcrafting_azureserpent",id:270914},
   {n:"Venomcured Effigy",sl:"Head",ty:"Token",tc:"Leather",b:"The Twin Fangs",ic:"inv_jewelcrafting_purpleserpent",id:270915},
   {n:"Venomcast Effigy",sl:"Head",ty:"Token",tc:"Mail",b:"The Twin Fangs",ic:"inv_jewelcrafting_goldenserpent",id:270916},
   {n:"Venomforged Effigy",sl:"Head",ty:"Token",tc:"Plate",b:"The Twin Fangs",ic:"inv_jewelcrafting_rubyserpent",id:270917}]},

 /* ── 7 · THE COILED ALTAR ────────────────────────────────────────────── */
 {id:"coiled-altar",o:7,n:"The Coiled Altar",short:"Altar",
  pos:"Seventh — the story fight",lv:3,
  sub:"Zul'jan, then Malacrass, then both at once",
  brief:"The villains of the patch, in sequence and then in chorus: kill Zul'jan while metering venom orbs through Sever, kill Malacrass while herding his Boo-style ghosts, survive the Soulbinding race — and then fight everything at once, knowing that when one falls the other enrages.",
  reads:[{by:"Tactyks",t:"A doozy — genuinely very hard, with enough going on that it may deserve a standalone guide once live tuning shows its hand.",s:["tk_va"]}],
  phases:[
   {n:"Phase 1 — Zul'jan",trigger:"Pull to Zul'jan at 0%",a:[
    {n:"Fangs of the Coiled Altar",t:["groupdmg","denial"],c:["topoff"],r:["healer","tank"],sev:2,
     e:"Rolling raid damage with Twinfang Toxin on the tanks, while Noxious Ground eats the room's edges — and the stacks empower his melee with bonus Nature damage.",
     h:"Stack near him and keep the floor budget in mind — this fight spends space like the Twins do. Tanks: at high stacks he is the hardest-meleeing boss in the raid so far; hold something for it.",
     s:["iv_alt","wg_va","tk_vtk"]},
    {n:"Toxic Deluge",t:["soak","denial"],c:["position","stagger"],r:["dps","healer"],sev:3,
     e:"Green pools leave Coalesced Venom orbs; carriers walk them to the stack point, and every orb destroyed is a Venom Rupture against the raid.",
     h:"Assigned carriers only — the off-tank plus your most mobile ranged — and everyone else stacks AWAY from the parked orbs so the frontal never clips a bystander. Keep the stack clear of roaming axes so the tank can aim through it cleanly.",
     hh:"Rupture stacks as a DoT — meter destructions to what the healers can eat.",
     s:["iv_alt"]},
    {n:"Sever",t:["frontal","tankbuster","amp"],c:["position","defensive"],r:["tank"],sev:3,
     e:"A cone that amps its next victim and destroys every venom orb it touches.",
     h:"Taunt swap per cast and aim each one through the orb stack — the frontal is also the venom-release valve, which is the whole phase in one sentence.",
     s:["iv_alt","wg_va"]},
    {n:"Guillotine",t:["soak","groupdmg"],c:["soak","mobility","topoff"],r:["healer","dps"],sev:3,
     e:"A group soak of five or more, followed by a Widow's Kiss circle everyone must escape.",
     h:"Soak, then sprint — Stampeding Roar earns its slot here, but a Warlock gate is a bait: porting players scoop up loose venom orbs on the way through. Top the soakers before the Kiss lands.",
     hh:"Soakers take 500% more from the next one: two half-raid groups, alternating.",
     s:["iv_alt"]},
    {n:"Venomfang",t:["dot"],c:["poison"],r:["healer"],sev:1,
     e:"A poison DoT on random players.",
     h:"Dispel on sight — a Poison Cleansing Totem automates the entire mechanic.",
     s:["iv_alt"]},
    {n:"Axegrinder",t:["env","denial"],c:["dodge"],r:["dps","healer"],sev:2,
     e:"Spinning axes roam the arena for the whole phase.",
     h:"Track them while carrying orbs or fleeing the Kiss — the deaths here are collisions, not damage checks. Leftover orbs all detonate when he falls, so end the phase clean.",
     s:["iv_alt"]}]},
   {n:"Phase 2 — Hex Lord Malacrass",trigger:"Zul'jan dies; the Hex Lord steps in",a:[
    {n:"Dreadmarch",t:["debuff","adds","shield"],c:["stack","cc","focus"],r:["dps"],sev:3,
     e:"Mind-controlled players shield up and march for the platform edge to jump; breaking the shield frees them and births two Manifestations of Dread apiece.",
     h:"Stay stacked so passive cleave cracks shields fast, and remember CC works on the possessed — Ring of Peace and Death Grip both count as a rescue.",
     s:["iv_alt","wg_va"]},
    {n:"Unnerving Fixation",t:["fixate","adds"],c:["position","los"],r:["dps"],sev:3,
     e:"The Manifestations are immune to everything and move only when their fixated player looks away — Boos, straight out of Mario.",
     h:"Walk yours to the stack point, then face it to freeze it for the frontal — they never fixate tanks, so the tank's whole job is aiming Soul Sever through the parked herd. The only kill button is Soul Sever.",
     hh:"A ghost that reaches its target recasts Dreadmarch — contact is never acceptable.",
     s:["iv_alt"]},
    {n:"Soul Sever",t:["frontal","tankbuster","debuff"],c:["position","mobility"],r:["tank"],sev:3,
     e:"Sever again, but victims are Gravebound: reclaim your three scattered Soul Fragments or die.",
     h:"Taunt per cast, aim through the parked ghosts, and the outgoing tank collects fragments immediately — a triangle of three, roughly fifteen seconds on the skull-marked debuff, and missing one is death, not damage. Getting clipped by an unmoved Gloombomb hands you the same errand.",
     s:["iv_alt"]},
    {n:"Gloombomb",t:["spread","debuff"],c:["spread","position"],r:["rdps","healer"],sev:2,
     e:"Purple circles on the ranged that detonate where they stand.",
     h:"Walk out, never overlap — anyone clipped inherits the Gravebound fragment errand.",
     hh:"The blast itself Gravebounds: lazy movement becomes lethal, not rude.",
     s:["iv_alt"]},
    {n:"Spiritcackle",t:["adds","channel"],c:["interrupt","focus"],r:["dps"],sev:2,df:["h"],
     e:"A cackling add that spams Wail of Terror and pokes random players with Retaliatory Malice.",
     h:"Two or three assigned ranged kicks, held late — it teleports on every interrupt, and if it blinks into melee it dies to cleave on the spot. Don't slow-roll forever: at full energy it becomes interrupt-immune. One spawns roughly every forty seconds.",
     s:["iv_alt","tk_va"]},
    {n:"Eternal Nightfall",t:["channel","groupdmg","shield"],c:["interrupt","focus"],r:["dps"],sev:3,
     e:"He shields with Veil of Twilight and starts the raid-ender.",
     h:"Burn the veil, then kick — as late as you dare, because every second of the delay is free damage. The veil was tuned up late in testing: treat it as a real damage check, and shield-break bonuses matter. End the phase with the ghosts dead and your toes off the edge: his death knocks back.",
     s:["iv_alt","wg_va","tk_va"]}]},
   {n:"Intermission — Soulbinding",trigger:"Malacrass falls, and refuses to stay down",a:[
    {n:"Soulbinding",t:["heal","channel"],c:["focus","unavoidable"],r:["dps"],sev:3,
     e:"He tethers to Zul'jan — untouchable himself — pouring Ghastly Regeneration into a Zul'jan who revives exactly where he fell and takes double damage while the ritual runs.",
     h:"Lust, potions, everything: every point burned here is health Phase 3 never sees. And the revival spot is a Phase 1 decision — kill Zul'jan centre-room, not in a corner.",
     s:["iv_alt","wg_va","tk_va","tk_vtk"]},
    {n:"Fragment of Malacrass",t:["adds","soak"],c:["soak","stagger"],r:["tank","healer"],sev:3,
     e:"Fragments crawl toward Zul'jan; each arrival heals the bosses, each interception detonates against the raid.",
     h:"Ring around Zul'jan and eat them one at a time — staggered, because two Spirit Erasures at once is how this intermission kills. Tanks soak first, damage second.",
     s:["iv_alt"]}]},
   {n:"Phase 3 — both",trigger:"Everything at once",a:[
    {n:"Uncoiled Union",t:["enrage","groupdmg"],c:["focus","stack"],r:["dps","tank"],sev:3,
     e:"Both are active, health uncoupled, and when one dies the other enrages. Only Zul'jan keeps a frontal — it must catch orbs and ghosts alike — while the Hex Lord stops meleeing entirely and shoots Shadow bolts at his tank instead.",
     h:"Stack them for cleave and bring them down evenly; a lopsided kill order volunteers the raid for an enraged Hex Lord. The Hex Lord's tank is soaking spell damage, not swings — plan mitigation accordingly.",
     hh:"Guillotine and Gloombomb keep coming on Heroic. On Normal neither appears — commit to one half of the room and hold it all phase.",
     s:["iv_alt","tk_va","tk_vtk"]}]}],
  loot:[
   {n:"Grasps of the Eternal Shadow",sl:"Hands",ty:"Cloth",b:"The Coiled Altar",ic:"inv_glove_cloth_raidwarlockulatek_d_01",id:268243,p:["Int"],x:[["Haste", 56], ["Crit", 23]]},
   {n:"Cackling Soultreads",sl:"Feet",ty:"Cloth",b:"The Coiled Altar",ic:"inv_boot_cloth_raidmageulatek_d_01",id:268255,p:["Int"],x:[["Haste", 53], ["Mastery", 26]]},
   {n:"Sash of the Forlorn Vessel",sl:"Waist",ty:"Leather",b:"The Coiled Altar",ic:"inv_belt_leather_raiddruidulatek_d_01",id:268256,p:["Agi", "Int"],x:[["Mastery", 54], ["Haste", 24]]},
   {n:"Coiled Hex Legguards",sl:"Legs",ty:"Leather",b:"The Coiled Altar",ic:"inv_pant_leather_raidmonkulatek_d_01",id:268225,p:["Agi", "Int"],x:[["Mastery", 73], ["Haste", 33]]},
   {n:"Cuisses of the Uncoiled Union",sl:"Legs",ty:"Mail",b:"The Coiled Altar",ic:"inv_pant_mail_raidevokerulatek_d_01",id:268237,p:["Agi", "Int"],x:[["Haste", 73], ["Mastery", 33]]},
   {n:"Reckless Spirit Breastplate",sl:"Chest",ty:"Plate",b:"The Coiled Altar",ic:"inv_chest_plate_raidwarriorulatek_d_01",id:268222,p:["Str", "Int"],x:[["Haste", 75], ["Mastery", 31]]},
   {n:"Girdle of Toxic Regret",sl:"Waist",ty:"Plate",b:"The Coiled Altar",ic:"inv_belt_plate_raidpaladinulatek_d_01",id:268259,p:["Str", "Int"],x:[["Crit", 56], ["Mastery", 23]]},
   {n:"Baleful Hexblade",sl:"One-hand",ty:"Sword",b:"The Coiled Altar",ic:"inv_sword_1h_ulatek_d_01",id:268211,p:["Int"],x:[["Haste", 36], ["Mastery", 17]]},
   {n:"Aman'muso, Warlord's Vengeance",sl:"One-hand",ty:"Axe",b:"The Coiled Altar",ic:"inv_axe_1h_ulatek_d_01",id:268209,p:["Agi", "Str"],x:[["Mastery", 37], ["Haste", 16]]},
   {n:"Maze-roa, Warlord's Fury",sl:"Two-hand",ty:"Axe",b:"The Coiled Altar",ic:"inv_axe_2h_ulatek_d_01",id:268213,p:["Agi", "Str"],x:[["Crit", 75], ["Mastery", 31]]},
   {n:"Silken Voodoo Drape",sl:"Back",ty:"Cloak",b:"The Coiled Altar",ic:"inv_cape_leather_raidrogueulatek_d_01",id:268253,p:["Agi", "Str", "Int"],x:[["Mastery", 42], ["Haste", 17]]},
   {n:"Hex Lord's Dooming Idol",sl:"Trinket",ty:"Trinket",b:"The Coiled Altar",ic:"inv_archaeology_orcclans_crackedidol",id:270169,x:[["Haste", 75]],u:"Consume the power of Hex Lord's Doom, returning a large Intellect boost per stack for 30 sec. (30 Sec Cooldown)",e:"Your spells afflict you with Hex Lord's Doom, draining a sliver of your Intellect up to 30 times, once every 6 sec.",ro:["healer","rdps"]},
   {n:"Zul'jin's Guillotine Technique",sl:"Trinket",ty:"Trinket",b:"The Coiled Altar",ic:"inv_121_trinket_raid_ulatek_trolltablet",id:270173,p:["Agi", "Str"],ro:["tank","mdps"],e:"You have a chance to follow up your attacks with Guillotine, hurling a massive axe in an arc at your target for heavy Physical damage."}]},

 /* ── 8 · ULA'TEK ─────────────────────────────────────────────────────── */
 {id:"ulatek",o:8,n:"Ula'tek",short:"Ula'tek",
  pos:"Final boss",lv:3,
  sub:"The serpent the temple was built to hold",
  gap:"Ula'tek was not available for PTR testing, so no tested strategy exists anywhere yet — Icy Veins says so outright and will write theirs when the raid is live. What follows is journal-derived structure via wow.gg (whose descriptions are Mythic-based by their own note), recorded so the shape is known. Treat every line as unconfirmed until live.",
  brief:"Freed after a thousand years, she floods the platform in waves, hatches her own eggs into vipers, and eats the floor as the fight goes on. The burn windows are hers to give: Rage of the Shackled exposes her Venomous Heart, and everything else is about still having a platform left when she does.",
  phases:[
   {n:"The goddess",trigger:"Structure unconfirmed until live",a:[
    {n:"Caustic Waves",t:["env","adds"],c:["dodge","position"],r:["dps","healer"],sev:3,
     e:"Venom waves roll the platform; any wave that washes over her eggs hatches Venomscale Vipers on the spot, whose birth flings Putrid Membrane onto players.",
     h:"Dodge the wave and mind what it is about to touch — the wave is also an incubator.",
     s:["wg_va"]},
    {n:"Spectral Coils",t:["soak","stack"],c:["stack","soak"],r:["healer","dps"],sev:3,
     e:"Her spectral coils rise and crush; the hit splits among everyone near the impact.",
     h:"Stack and share, on assignment.",
     s:["wg_va"]},
    {n:"Mother's Wrath",t:["tankbuster","knockback","dot"],c:["defensive"],r:["tank"],sev:2,
     e:"She flings her target away and focuses her fury on it.",
     h:"A thrown tank is still a focused tank — defensives through the ride.",
     s:["wg_va"]},
    {n:"Rage of the Shackled",t:["groupdmg","env"],c:["topoff","focus"],r:["healer","dps"],sev:3,
     e:"She rages, raining debris — and forgets to guard her Venomous Heart, which becomes attackable.",
     h:"The burn window: cooldowns into the Heart while the healers hold the roof up.",
     s:["wg_va"]},
    {n:"Call of the Serpent",t:["adds","groupdmg"],c:["focus"],r:["dps"],sev:2,
     e:"A roar that shakes the arena and drops more brood from the ceiling.",
     h:"Brood control is the fight's background job — vipers multiply if ignored.",
     s:["wg_va"]},
    {n:"Circling Prey",t:["env","knockback"],c:["position"],r:["dps","healer","tank"],sev:3,
     e:"She destroys a section of the platform outright, punishing both the too-close and the too-far.",
     h:"Hold a middling range and accept the floor is a resource that only shrinks.",
     s:["wg_va"]}]}],
  loot:[
   {n:"Venomkeeper's Horrific Cowl",sl:"Head",ty:"Cloth",b:"Ula'tek",ic:"inv_helm_cloth_raidwarlockulatek_d_01",id:271874,p:["Int"],x:[["Mastery", 107]]},
   {n:"Gaze of the Coiled Watcher",sl:"Head",ty:"Leather",b:"Ula'tek",ic:"inv_helm_leather_raiddruidulatek_d_01",id:271875,p:["Agi", "Int"],x:[["Haste", 107]]},
   {n:"Awoken Dreadfang Cuirass",sl:"Chest",ty:"Mail",b:"Ula'tek",ic:"inv_chest_mail_raidevokerulatek_d_01",id:271876,p:["Agi", "Int"],x:[["Crit", 107]]},
   {n:"Chausses of Unbound Rancor",sl:"Legs",ty:"Plate",b:"Ula'tek",ic:"inv_pant_plate_raiddeathknightulatek_d_01",id:271878,p:["Str", "Int"],x:[["Mastery", 107]]},
   {n:"Jaw of the Shackled Goddess",sl:"One-hand",ty:"Sword",b:"Ula'tek",ic:"inv_sword_1h_ulatek_d_01",id:268202,p:["Str"],x:[["Haste", 53]]},
   {n:"Abyssal Broodfiend's Bardiche",sl:"Two-hand",ty:"Polearm",b:"Ula'tek",ic:"inv_polearm_2h_ulatek_d_01",id:268215,p:["Agi"],x:[["Mastery", 107]]},
   {n:"Caustic Repose Greatbow",sl:"Ranged",ty:"Bow",b:"Ula'tek",ic:"inv_bow_1h_ulatek_d_01",id:268207,p:["Agi"],x:[["Crit", 53]]},
   {n:"Zatha'tek, Breath of Corruption",sl:"One-hand",ty:"Dagger",b:"Ula'tek",ic:"inv_knife_1h_ulatekfang_d_01_poison",id:271093,p:["Agi"],x:[["Crit", 53]]},
   {n:"Jan'thrazet, the Soul Fang",sl:"One-hand",ty:"Dagger",b:"Ula'tek",ic:"inv_knife_1h_ulatekfang_d_01_spirit",id:271092,p:["Int"],x:[["Haste", 53]]},
   {n:"Aqirbane Reliquary",sl:"Neck",ty:"Neck",b:"Ula'tek",ic:"inv_121_jewelry_neck03_green",id:268265,x:[["Crit", 158]]},
   {n:"Font of Venomous Rage",sl:"Trinket",ty:"Trinket",b:"Ula'tek",ic:"inv_10_dungeonjewelry_dragon_trinket_3djardintrophy_green",id:270168,x:[["Mastery", 75]],u:"Channel a torrent of venomous rage over 2 sec, dealing massive Nature damage to your target and splattering all nearby enemies. Damage reduced beyond 8 targets. (4 Min Cooldown)",ro:["mdps","rdps"]},
   {n:"Voracious Heart of Ula'tek",sl:"Trinket",ty:"Trinket",b:"Ula'tek",ic:"inv_121_trinket_raid_ulatek_heart",id:270175,x:[["Crit", 75]],u:"Bite the heart and embrace the ravening hunger, gaining a large amount of Strength or Agility for 20 sec.",ro:["tank","mdps"]},
   {n:"Slumbering Coil Curio",sl:"Token",ty:"Token",tc:"All",b:"Ula'tek",ic:"rogue_paralytic_poison",id:270909}]}]};
const RB=Object.fromEntries(RAID.bosses.map(b=>[b.id,b]));
