/* js/data-shared.js — vocabulary and cross-module data
   Load order: data-shared → data-mplus → data-raid → render → app.
   All five load with `defer`, which preserves this order. */

/* ═══════════════════════════════════════════════════════════════════════
   DATA · SOURCE LEDGER
   tier 1 = Blizzard directly — patch notes, hotfixes, the Encounter Journal
   tier 2 = Wowhead / Icy Veins
   tier 3 = established creators · 4 = SEO and boosting sites
   ═══════════════════════════════════════════════════════════════════════ */
const SOURCES={
 bz_game:{l:"BLIZZARD",t:1,k:"blizzard",a:"Blizzard",b:"Patch 12.1 notes and in-game data",d:"2026-08-16",u:"https://worldofwarcraft.blizzard.com/en-us/news",note:"Season structure, affix bands, reward tracks and drop sources as published by Blizzard or read directly from the live client."},
 wh_ej  :{l:"JOURNAL",t:1,k:"journal",a:"Blizzard Encounter Journal",b:"In-game dungeon journal, mirrored by Wowhead (PTR 12.1.0)",d:"2026-08-16",u:"https://www.wowhead.com/",note:"The text is Blizzard's own. The delivery is a third-party mirror, so transcription error is possible and PTR values can still move — but on names, numbers and mechanics this outranks every guide."},
 bz0813 :{l:"BLIZZARD",t:1,k:"blizzard", a:"Blizzard",b:"Hotfixes: 13 August 2026",d:"2026-08-13",u:"https://news.blizzard.com/en-us/article/24296142/hotfixes-august-14-2026"},
 bz0814 :{l:"BLIZZARD",t:1,k:"blizzard", a:"Blizzard",b:"Hotfixes: 14 August 2026",d:"2026-08-14",u:"https://news.blizzard.com/en-us/article/24296142/hotfixes-august-14-2026"},
 wh_dt  :{l:"WOWHEAD",t:2,k:"wowhead",  a:"Wowhead",b:"Midnight Season 2 Dungeon Tuning for Patch 12.1",d:"2026-07-25",u:"https://www.wowhead.com/news/midnight-season-2-dungeon-tuning-for-patch-12-1-382238"},
 iv_ov  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Gogogadgetkat)",b:"Midnight Mythic+ Season 2 Guide",d:"2026-08-05",u:"https://www.icy-veins.com/wow/midnight-mythic-plus-season-2-guide"},
 iv_aof :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Altar of Fangs Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/altar-of-fangs-dungeon-guide"},
 iv_bv  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"The Blinding Vale Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/the-blinding-vale-dungeon-guide"},
 iv_mr  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Murder Row Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/murder-row-dungeon-guide"},
 iv_don :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Den of Nalorakk Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/den-of-nalorakk-dungeon-guide"},
 iv_vsa :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Voidscar Arena Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/voidscar-arena-dungeon-guide"},
 iv_rlp :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"Ruby Life Pools Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/ruby-life-pools-dungeon-guide"},
 iv_kr  :{l:"ICY VEINS",t:2,k:"icyveins",a:"Icy Veins (Petko)",b:"King's Rest Dungeon Guide",d:"2026-08-11",u:"https://www.icy-veins.com/wow/kings-rest-dungeon-guide"},
 img    :{l:"CAPTURE",t:1,k:"capture",a:"In-game capture",b:"Boss and entrance imagery, patch 12.1 PTR",d:"2026-08-16",u:null,note:"Screenshots of the encounters with in-game nameplates legible. Useful as a check on spelling, since the nameplate is the game's own rendering of the name."},
 wh_dg  :{l:"WOWHEAD",t:2,k:"wowhead",a:"Wowhead (iMX3)",b:"Season 2 Mythic+ dungeon overviews, all eight",d:"2026-08-12",u:"https://www.wowhead.com/guide/mythic-plus-dungeons/midnight-season-2"},
 tk_aof :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Altar of Fangs Mythic+ Dungeon Guide",d:"2026-08-01",u:"https://www.youtube.com/watch?v=cgM-EioPF0g"},
 tk_bv  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Blinding Vale Mythic+ Dungeon Guide",d:"2026-08-02",u:"https://www.youtube.com/watch?v=HcvkIzRTdtY"},
 tk_mr  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Murder Row Mythic+ Dungeon Guide",d:"2026-08-03",u:"https://www.youtube.com/watch?v=jE7g21vi290"},
 tk_don :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Den of Nalorakk Mythic+ Dungeon Guide",d:"2026-08-04",u:"https://www.youtube.com/watch?v=gNJ-3-6k75A"},
 tk_vsa :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Voidscar Arena Mythic+ Dungeon Guide",d:"2026-08-05",u:"https://www.youtube.com/watch?v=Da9hWBW_6JE"},
 tk_rlp :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Ruby Life Pools Mythic+ Dungeon Guide",d:"2026-08-06",u:"https://www.youtube.com/watch?v=u-TVxNPFMZs"},
 tk_kr  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"King's Rest Mythic+ Dungeon Guide",d:"2026-08-07",u:"https://www.youtube.com/watch?v=pT8A8RW9QTc"},
 tk_tos :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Temple of Sethraliss Mythic+ Dungeon Guide",d:"2026-08-08",u:"https://www.youtube.com/watch?v=qBM_N6qBcEc"},
 tk_pool:{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Thoughts on the Season 2 Dungeon Pool, Rewards and Resilient Keystones",d:"2026-07-25",u:"https://www.youtube.com/watch?v=IcBeTr3VTbo"},
 tk_rt  :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Pug-Friendly Mythic+ Routes for All Season 2 Dungeons",d:"2026-08-15",u:"https://www.youtube.com/watch?v=nZJi0Fdgl5Q"},
 tk_trk :{l:"TACTYKS",t:3,k:"creator",  a:"Tactyks",b:"Season 2 Tank Trinket and Cantrip Gear Preview",d:"2026-06-27",u:"https://www.youtube.com/watch?v=2d3ebU0MuE8"}
};

/* ═══ TAG VOCABULARIES ═══ icon + label. Colour is never the only cue. ═══ */
const TAGS={
 frontal:{l:"Frontal",i:"i-frontal"}, line:{l:"Line",i:"i-line"},
 tankbuster:{l:"Tank buster",i:"i-tank"}, soak:{l:"Soak",i:"i-soak"},
 spread:{l:"Spread",i:"i-spread"}, stack:{l:"Stack up",i:"i-stack"},
 dot:{l:"DoT",i:"i-drop"}, groupdmg:{l:"Group damage",i:"i-warn"},
 channel:{l:"Channel",i:"i-channel"}, knockback:{l:"Knockback",i:"i-knock"},
 knockup:{l:"Knock-up",i:"i-knock"}, fixate:{l:"Fixate",i:"i-dps"},
 adds:{l:"Adds",i:"i-add"}, totem:{l:"Totem",i:"i-add"},
 shield:{l:"Shield",i:"i-shield"}, enrage:{l:"Enrage",i:"i-enrage"},
 absorb:{l:"Heal absorb",i:"i-heal"}, healred:{l:"Healing reduced",i:"i-heal"},
 amp:{l:"Damage amp",i:"i-warn"}, debuff:{l:"Party debuff",i:"i-warn"},
 root:{l:"Root",i:"i-move"}, stun:{l:"Stun",i:"i-warn"}, fear:{l:"Fear",i:"i-warn"},
 silence:{l:"Silence",i:"i-kick"}, pacify:{l:"Pacify",i:"i-kick"},
 denial:{l:"Area denial",i:"i-drop"}, env:{l:"Environmental",i:"i-warn"},
 death:{l:"On death",i:"i-warn"}, heal:{l:"Enemy healing",i:"i-heal"},
 stacking:{l:"Stacking",i:"i-stack"}, mobility:{l:"Movement",i:"i-move"},
 myth:{l:"Mythic only",i:"i-warn"}, noarmor:{l:"Ignores armour",i:"i-tank"}
};
const CTRS={
 interrupt:{l:"Interrupt",i:"i-kick"}, cc:{l:"CC the channel",i:"i-kick"},
 drop:{l:"Combat drop",i:"i-kick"}, purge:{l:"Purge",i:"i-dispel"},
 soothe:{l:"Soothe",i:"i-dispel"}, magic:{l:"Magic dispel",i:"i-dispel"},
 poison:{l:"Poison dispel",i:"i-dispel"}, curse:{l:"Curse dispel",i:"i-dispel"},
 disease:{l:"Disease dispel",i:"i-dispel"}, bleedcl:{l:"Bleed cleanse",i:"i-dispel"},
 freedom:{l:"Freedom",i:"i-move"}, immune:{l:"Immunity",i:"i-shield"},
 topoff:{l:"Heal to full",i:"i-heal"}, defensive:{l:"Defensive",i:"i-tank"},
 kite:{l:"Kite",i:"i-move"}, position:{l:"Positioning",i:"i-move"},
 stagger:{l:"Stagger kills",i:"i-dps"}, focus:{l:"Focus target",i:"i-dps"},
 preposition:{l:"Pre-position",i:"i-move"}, dodge:{l:"Dodge",i:"i-move"},
 unavoidable:{l:"Unavoidable",i:"i-warn"}, los:{l:"Line of sight",i:"i-shield"},
 spread:{l:"Spread out",i:"i-spread"}, stack:{l:"Stack up",i:"i-stack"},
 soak:{l:"Soak it",i:"i-soak"}, mobility:{l:"Movement ability",i:"i-move"}
};
const KINDS={boss:"Boss",mini:"Mini-boss",lt:"Lieutenant",trash:"Trash",caster:"Caster",fodder:"Fodder"};

/* ═══ SEASON FACTS ═══ Blizzard-sourced: patch notes and live client ═══ */
const SEASON={
 opens:"2026-08-18", opensLocal:"Tue 18 Aug, 08:00 PDT in the Americas · Wed 19 Aug in Europe · Wed 19 Aug, ~01:00 AEST on Oceanic realms, which run the Americas reset",
 patch:'12.1 "The Curse of Ula\'tek"', patchLive:"2026-08-11",
 affixes:[
  {k:"+2 to +4",  a:"Lindormi's Guidance",  d:"New onboarding affix. Softens deaths, teaches routes and enemy-forces counts.",s:["bz_game","iv_ov"]},
  {k:"+5 to +11", a:"Xal'atath's Bargain",  d:"One of four, rotating weekly: Ascendant, Voidbound, Pulsar, Devour. Only one Bargain is live per week.",s:["bz_game","iv_ov"]},
  {k:"+7 to +10", a:"Fortified / Tyrannical",d:"The two rotate weekly in this band.",s:["bz_game","iv_ov"]},
  {k:"+10 and up",a:"Fortified and Tyrannical",d:"Both, every week.",s:["bz_game","iv_ov"]},
  {k:"+12 and up",a:"Xal'atath's Guile",     d:"Replaces all Bargains. Deaths substantially more punishing, rewarding safer play and coordinated defensives.",s:["bz_game","iv_ov"]}
 ],
 rewards:[
  {k:"+2 / +3",   e:"295",v:"305"},{k:"+4",e:"298",v:"308"},{k:"+5",e:"302",v:"308"},
  {k:"+6",        e:"305",v:"311"},{k:"+7",e:"305",v:"315"},{k:"+8 / +9",e:"308",v:"315"},
  {k:"+10 and up",e:"311",v:"318"}
 ],
 rewardVerified:true,
 rewardNote:"Rewards flatten at +10 — a +10 and a +20 award identical gear. Breath of Blight at 2,000 rating (Keystone Master); Breath of Ruin at 3,000 (Keystone Legend). Dungeon teleports at a timed +10 each. Keystone Master also grants Serpent Scion, which unlocks additional tier-set visual effects and is otherwise obtainable from Heroic or Mythic Ula'tek.",
 mounts:"The Writhing Brood drops from Zul'jan in Altar of Fangs on Mythic or Mythic+.",
 where:[{n:"Mythic+ portal room",d:"Through the golden Timeways portal at 53.3, 66.1 in Silvermoon City. Lindormi and Agmera stand beside it. Holds portals to the Season 2 dungeons that are not current Midnight content.",s:["iv_ov"]},
        {n:"Gear upgrades",d:"Cuzolth, the item upgrade vendor, at 48.3, 61.7 in Silvermoon City, with Vaskarn the crest exchange alongside.",s:["iv_ov"]},
        {n:"Season length",d:"Runs to the end of the 12.1 patch cycle, expected to be roughly six months.",s:["iv_ov"]}]
};

/* ═══ CONTESTED — rendered wherever the claim appears ═══ */
const DISPUTES=[
 {id:"kr-count",q:"Does King's Rest still require 100% trash count?",
  a:{p:"Yes — every mob in the instance, believed to be a first for the format.",s:["bz_game"]},
  b:{p:"Relaxed late in the PTR. A 15 Aug routing video says the requirement changed and demonstrates a route leaving two packs unpulled that still makes count; Wowhead separately reported PTR dungeon tuning that removed some King's Rest trash. Note these are not the same claim — removing trash does not by itself relax a 100% requirement.",s:["tk_rt","wh_dt"]},
  extra:"A written dungeon overview dated 11-12 Aug states flatly that you must pull every mob. That is a steadier kind of source than a video and it strengthens Position A — but it PREDATES the routing video by three or four days, so it cannot rebut a claim about a later change. Date order matters more than pedigree here.",
  r:"Open the key and check whether count completes with a pack skipped. This is now the oldest open question in the compendium and the cheapest to answer.",dg:"kings-rest"},
 {id:"vsa-buff",q:"How much Versatility does the Voidscar left path grant?",
  a:{p:"5% Versatility, from Proof of Endurance.",s:["tk_vsa"]},
  b:{p:"3% Versatility.",s:["tk_rt"]},
  r:"Read the buff tooltip after killing the left mini-boss. Same author, two weeks apart, unexplained.",dg:"voidscar-arena"},
 {id:"bv-freedom",q:"Is the Blinding Vale tank dot removable by Freedom effects?",
  a:{p:"Yes — the Four-Spined magic dot can be cleared by magic dispel or by freedom effects.",s:["tk_bv"]},
  b:{p:"No — a magic dot and slow on the tank in Blinding Vale is not removed by freedoms, possibly a missing ability flag.",s:["tk_pool"]},
  r:"May be two different abilities rather than a contradiction. Test on the lasher packs.",dg:"blinding-vale"},
 {id:"bv-pulverize",q:"Can you dodge Lightwarden Ruia's Pulverizing Strikes?",
  a:{p:"Yes — move the moment you are marked, and leave room for untargeted players to get out.",s:["tk_bv"]},
  b:{p:"No — the cones lock onto the player, so there is no dodging them. Stand still when it is on you and rely on being spread.",s:["wh_dg"]},
  r:"The Encounter Journal says he marks targets and launches a wave toward each, which reads closer to a lock-on. If the written guide's reading is right, the creator advice actively hurts you — running drags the cone across allies. Watch one cast before deciding.",dg:"blinding-vale"},
 {id:"vsa-path",q:"Which Voidscar Arena path should you take?",
  a:{p:"Left, for Proof of Endurance. The Versatility buff is generally more beneficial, and the harder left-side mini-boss is worth it for most groups.",s:["tk_vsa"]},
  b:{p:"Right, for Proof of Mastery — described as a powerful dungeon buff that speeds the run up, against Proof of Endurance being called not-so-great. Explicitly framed as a call about current tuning.",s:["iv_vsa"]},
  r:"The written guide's position is six days later and post-patch, which usually settles it. But the two are arguing about buff value, not a fact, and Proof of Mastery scales with your spec's mastery modifier — so the right answer may genuinely differ by group composition. Read the tooltips and decide for your comp.",dg:"voidscar-arena"},
 {id:"bv-side",q:"Which side of Blinding Vale should a pug take?",
  a:{p:"Left. The Light-Starved Blossom buff is the better of the two and the trash composition looks slightly easier.",s:["tk_bv"]},
  b:{p:"Right. The left side has considerably more interrupts and an extra Sporeblight Belcher; the right side's bolt-casters can be safely ignored once packs are grouped.",s:["tk_rt"]},
  r:"Same author reversed between 2 Aug and 15 Aug. The later position is the routing-specific one.",dg:"blinding-vale"}
];

/* ═══ RESOLVED — kept for the record, never left in the live list above ═══ */
const RESOLVED=[
 {id:"rlp-phase",q:"At what health does Kyrakka join Erkhart Stormvein?",
  won:"40%",by:["wh_ej"],
  p:"The creator guide said 40%, the written guide said 50%. The Encounter Journal says Kyrakka lands when EITHER of them reaches 40% — so the creator was right, and both guides missed that the threshold applies to whichever boss hits it first.",d:"2026-08-16"},
 {id:"aof-axes",q:"Can Axegrinder be used to clear Ritual Venom stacks?",
  won:"Yes",by:["wh_ej"],
  p:"The creator guide treated the axes purely as something to dodge; the written guide offered them as a second way to clear stacks. The journal settles it: Bloodletting triggers on Zul'jan's Physical abilities, and Axegrinder is Physical. It is a real second option — and useful, because Boneslicer only targets one player at a time.",d:"2026-08-16"}
];
/* ═══ IMAGERY ═══ optimised WebP, embedded so the file stays self-contained.
   Boss portraits carry the in-game nameplate, which makes them evidence as well as decoration. */
const IMG={
/* Keyed by banner/capture name; values are paths under assets/img/.
   These were inline base64 until 2026-08-17 — 703 KB, 68% of the payload,
   all blocking first paint. Loose files are cached per-file, fetched in
   parallel, and lazy-loaded, so a page pulls only what it shows — the same
   reasoning assets/icons already documents. The bytes are the originals,
   decoded not recompressed. */
"altar-of-fangs":"assets/img/altar-of-fangs.webp",
"aof-ravi":"assets/img/aof-ravi.webp",
"aof-the-writhing-coil":"assets/img/aof-the-writhing-coil.webp",
"aof-zuljan":"assets/img/aof-zuljan.webp",
"den-of-nalorakk":"assets/img/den-of-nalorakk.webp",
"don-nalorakk":"assets/img/don-nalorakk.webp",
"don-sentinel-of-winter":"assets/img/don-sentinel-of-winter.webp",
"don-the-hoardmonger":"assets/img/don-the-hoardmonger.webp",
"kings-rest":"assets/img/kings-rest.webp",
"kr-king-dazar":"assets/img/kr-king-dazar.webp",
"kr-mchimba-the-embalmer":"assets/img/kr-mchimba-the-embalmer.webp",
"kr-the-council-of-tribes":"assets/img/kr-the-council-of-tribes.webp",
"kr-the-golden-serpent":"assets/img/kr-the-golden-serpent.webp",
"mr-kystia-manaheart":"assets/img/mr-kystia-manaheart.webp",
"mr-lithiel-cinderfury":"assets/img/mr-lithiel-cinderfury.webp",
"mr-xathuux-the-annihilator":"assets/img/mr-xathuux-the-annihilator.webp",
"mr-zaen-bladesorrow":"assets/img/mr-zaen-bladesorrow.webp",
"murder-row":"assets/img/murder-row.webp",
"rlp-kokia-blazehoof":"assets/img/rlp-kokia-blazehoof.webp",
"rlp-kyrakka-and-erkhart":"assets/img/rlp-kyrakka-and-erkhart.webp",
"rlp-melidrussa":"assets/img/rlp-melidrussa.webp",
"ruby-life-pools":"assets/img/ruby-life-pools.webp",
"tbv-ikuzz":"assets/img/tbv-ikuzz.webp",
"tbv-lightblossom-trinity":"assets/img/tbv-lightblossom-trinity.webp",
"tbv-lightwarden-ruia":"assets/img/tbv-lightwarden-ruia.webp",
"tbv-ziekket":"assets/img/tbv-ziekket.webp",
"temple-of-sethraliss":"assets/img/temple-of-sethraliss.webp",
"the-blinding-vale":"assets/img/the-blinding-vale.webp",
"va-atroxus":"assets/img/va-atroxus.webp",
"va-charonus":"assets/img/va-charonus.webp",
"va-tazrah":"assets/img/va-tazrah.webp",
"voidscar-arena":"assets/img/voidscar-arena.webp"
};

/* ═══════════════════════════════════════════════════════════════════════
   DATA · DUNGEONS
   Ability shape: n name · t tags · c counters · r roles · sev 1–3
                  e effect (FACT) · h handling (READ, opinion) · s sources
   ═══════════════════════════════════════════════════════════════════════ */

/* ═══ ABILITY ICONS ══════════════════════════════════════════════════════
   Ability name → Blizzard icon slug, resolved against Wowhead's spell
   database. Files live in assets/icons/<slug>.jpg. 287 of the 329 ability
   names in DUNGEONS resolved to a spell of exactly that name; the other 42
   were each queried and none is a spell — three are adds filed into ability
   arrays, the rest structural notes or content Wowhead has no entry for. A name that
   is absent here simply renders without an icon — never a broken image.
   ═══════════════════════════════════════════════════════════════════════ */
const ICONS={
"Accumulate Charge":"spell_chargepositive",
"Addle Mind":"spell_shadow_mindflay",
"Ancestral Fury":"spell_totem_wardofdraining",
"Arc Lightning":"spell_nature_chainlightning",
"Arrow Barrage":"inv_misc_ammo_arrow_05",
"Awaken the Lightbloom":"inv_desertlasherorchid_yellow",
"Awakening Slam":"spell_necro_deathsdoor",
"Axe Toss":"ability_warrior_titansgrip",
"Axegrinder":"ability_warrior_bladestorm",
"Back to Work":"inv_hammer_09",
"Barrel Through":"ability_monk_clashingoxcharge",
"Bedrock Slam":"spell_nature_earthquake",
"Belch Spores":"spell_nature_corrosivebreath",
"Bestial Wrath":"ability_druid_ferociousbite",
"Blade Combo":"ability_ironmaidens_bladerush",
"Blade Dance":"ability_demonhunter_bladedance",
"Blaze of Glory":"inv_ember",
"Blazing Rush":"spell_deathknight_butcher2",
"Blood Sacrifice":"ability_warrior_bloodfrenzy",
"Bloodletting":"ability_skeer_bloodletting",
"Bloodthirsty Axe":"spell_druid_bloodythrash",
"Bloodthirsty Gaze":"ability_fixated_state_red",
"Bloodthorn Roots":"inv_-misc_herb_marrowroot_leaf",
"Boneslicer":"ability_hunter_swiftstrike",
"Bound by Shadow":"spell_shadow_summonvoidwalker",
"Brutal Slams":"ability_warrior_decisivestrike",
"Brutalize":"ability_warrior_devastate",
"Bullet Seeds":"spell_shaman_convection",
"Burning Corruption":"spell_fire_blueflamebreath",
"Burnout":"spell_fire_soulburn",
"Call of the Elements":"ability_shaman_echooftheelements",
"Caustic Stomp":"inv_ability_poison_nova",
"Champion Spear":"inv_ability_warrior_championsspear",
"Chaos Barrage":"spell_fire_felrainoffire",
"Chaos Bolt":"ability_warlock_chaosbolt",
"Chillstorm":"spell_shadow_soulleech_2",
"Chop Down":"ability_criticalstrike",
"Cold Claws":"ability_mage_wintersgrasp",
"Concussive Slam":"ability_warrior_decisivestrike",
"Corroding Spittle":"inv_fabric_felcloth_ebon",
"Corrosive Essence":"inv_ability_poison_orb",
"Corrosive Fangs":"spell_nature_nullifypoison",
"Cosmic Crash":"inv_cosmicvoid_groundsate",
"Crushing Smash":"spell_shaman_earthquake",
"Curse of Doom":"spell_shadow_auraofdarkness",
"Cytotoxin":"ability_hunter_cobrastrikes",
"Dark Bloom":"inv_ability_voidweaverpriest_entropicrift",
"Dark Pact":"spell_shadow_deathpact",
"Dark Revelation":"ability_priest_clarityofpower",
"Dark Waves":"inv_cosmicvoid_wave",
"Death Rattle":"inv_sonic_debuff",
"Deathly Roar":"ability_hunter_beastmastery",
"Debilitating Backhand":"inv_relics_totemofrage",
"Deep Corruption":"priest_icon_chakra_red",
"Defiled Slam":"spell_fire_felimmolation",
"Defiling Taint":"ability_creature_disease_05",
"Demonic Frenzy":"spell_fel_incinerate",
"Demonic Rage":"ability_warlock_demonicempowerment",
"Demoralizing Shout":"ability_warrior_warcry",
"Devour":"inv_12_dh_void_ability_devourerbite",
"Dimensional Shred":"ability_rogue_masterofsubtlety",
"Dismember":"ability_criticalstrike",
"Disorienting Screech":"inv_111_hunter_ability_harrierscall",
"Drain Fluids":"inv_misc_volatilewater",
"Drain Life":"spell_shadow_lifedrain02",
"Earthbound's Imprint":"inv_ore_blackrock_ore",
"Earthquake":"spell_shaman_earthquake",
"Earthshatter Slam":"spell_shaman_earthquake",
"Echoing Maul":"inv_ability_druidoftheclawdruid_ravage",
"Empowerment":"spell_nature_elementalprecision_1",
"Entomb":"achievement_bg_xkills_avgraveyard",
"Envenom":"ability_rogue_disembowel",
"Essence Disruption":"inv_elemental_mote_shadow01",
"Evolve":"inv_121_trinket_raid_ulatek_heart",
"Excavating Blast":"spell_nature_earthquake",
"Eye Beam":"ability_demonhunter_eyebeam",
"Feast of Misery":"spell_shadow_lifedrain02_purple",
"Fel Beam":"spell_fire_felflamestrike",
"Fel Missiles":"spell_fire_felrainoffire",
"Fel Nova":"spell_fire_felflamering",
"Fel Rage":"ability_creature_felfrenzy",
"Fel Shield":"trade_engineering",
"Fel Spray":"spell_fire_felflamebreath",
"Fel Steps":"ability_bossfellord_felfissure",
"Felfire Burst":"spell_fire_felflamebolt",
"Feral Rage":"artifactability_feraldruid_ashamanesbite",
"Ferocious Leap":"ability_heroicleap",
"Fingers of Gul'dan":"ability_warlock_handofguldan",
"Fire Bomb":"inv_eng_bombfire",
"Fire Maw":"ability_warrior_dragonroar",
"Fixate":"ability_fixated_state_blue",
"Flame Dance":"trade_engineering",
"Flame Shock":"spell_fire_flameshock",
"Flay":"inv_archaeology_70_demon_flayedskinchronicle",
"Forceful Slam":"inv_misc_bearpaw_red",
"Forked Lightning":"spell_lightning_lightningbolt01",
"Frantic Blooming":"inv_desertlasherorchid_yellow",
"Frigid Roar":"inv_amanibearmount_witherbark",
"Frigid Shard":"spell_frost_iceshard",
"Frost Bite":"ability_mage_coldasice",
"Frost Overload":"spell_fire_blueflamering",
"Frost Shock":"spell_frost_frostshock",
"Frozen Tempest":"spell_frost_ring-of-frost",
"Fury of the War God":"spell_nature_shamanrage",
"Gale Force":"ability_skyreach_four_wind",
"Galvanized":"spell_shaman_staticshock",
"Gilded Destruction":"inv_sword_2h_zandalarquest_b_01",
"Glacial Tomb":"ability_mage_coldasice",
"Glacial Torment":"inv12_apextalent_mage_handoffrost",
"Glaive Toss":"ability_upgrademoonglaive",
"Gravitic Orbs":"inv_enchant_voidsphere",
"Grievous Gash":"inv_ability_druidoftheclawdruid_ravage",
"Grievous Thrash":"spell_druid_bloodythrash",
"Ground Pound":"ability_smash",
"Hailburst":"spell_frost_frostshock",
"Harsh Winds":"spell_nature_earthbind",
"Head Bash":"inv_fellessergronnmount",
"Healing Breeze":"spell_frost_windwalkon",
"Healing Tide Totem":"ability_shaman_healingtide",
"Health Funnel":"spell_shadow_lifedrain",
"Heartstop Poison":"ability_boss_kilrogg_heartseeker",
"Heavy Slams":"inv_11_arenaboss_conductionslam",
"Hex":"spell_shaman_hex",
"Hex Volley":"warlock_curse_shadow",
"Hulking Claw":"ability_creature_poison_03",
"Hunting Leap":"ability_druid_ravage",
"Ice Shield":"ability_mage_coldasice",
"Icebolt":"spell_frost_frostbolt02",
"Imbued Conduction":"spell_nature_stormreach",
"Induction":"ability_thunderking_overcharge",
"Infernal Crash":"spell_shadow_summoninfernal",
"Inferno":"ability_warlock_inferno",
"Inferno Spit":"spell_fire_firebolt",
"Infest":"ability_hunter_snaketrap",
"Insidious Aura":"ability_warlock_burningembersgreen",
"Killing Spree":"inv_112_rogue_betweentheeyes",
"Laced Edge":"inv_sword_2h_ulatek_d_01",
"Latent Hex":"inv_shoulder_armor_hextroll_d_01",
"Legion Strike":"inv_axe_09",
"Light Bolt":"spell_holy_holybolt",
"Light Bolt Volley":"ability_priest_flashoflight",
"Light Fire":"trade_engineering",
"Lightbloom Pollination":"spell_holy_surgeoflight",
"Lightbloom's Essence":"inv_ability_holyfire_orb",
"Lightblossom Beam":"ability_paladin_infusionoflight",
"Lightfall":"inv_ability_holyfire_missile",
"Lightning Bite":"ability_thunderking_balllightning",
"Lightning Bolt":"spell_nature_lightning",
"Lightning Rod":"inv_rod_enchantedcobalt",
"Lightning Torrent":"spell_shaman_thunderstorm",
"Living Bomb":"ability_mage_livingbomb",
"Lucre's Call":"spell_holy_purifyingpower",
"Mad Shriek":"spell_shadow_psychicscream",
"Maelstrom":"spell_nature_unrelentingstorm",
"Magma Totem":"spell_fire_selfdestruct",
"Malefic Wave":"ability_felarakkoa_feldetonation_green",
"Mass Envenom":"inv_ability_poison_missile",
"Melt Armor":"spell_fire_firebolt02",
"Mending Void":"inv_cosmicvoid_buff",
"Mirror Images":"spell_magic_lesserinvisibilty",
"Molten Blood":"spell_shaman_spewlava",
"Molten Boulder":"spell_mage_flameorb",
"Monstrous Roar":"ability_racial_darkflight",
"Mother's Wrath":"inv_misc_monsterfang_02",
"Nether Dash":"ability_mount_voidelfstridermount",
"Noxious Breath":"ability_creature_poison_05",
"Noxious Spray":"inv_ability_poison_beam",
"Null Eruption":"inv_cosmicvoid_orb",
"Oozing Xylem":"inv_ability_holyfire_nova",
"Over-infused":"inv_ore_feliron",
"Overload":"spell_nature_callstorm",
"Overwhelming Onslaught":"spell_druid_thrash",
"Paralyzing Shot":"ability_poisonsting",
"Piercing Hiss":"inv_sonic_wave",
"Poison Nova":"ability_creature_disease_02",
"Poison Spear Volley":"inv_spear_02",
"Poison Splash":"spell_nature_corrosivebreath",
"Poisoned Cheap Shot":"ability_cheapshot",
"Pool of Darkness":"inv_misc_food_legion_gooamberpink_pool",
"Primal Echo":"spell_druid_stamedingroar",
"Pulverize":"ability_smash",
"Pulverizing Strikes":"ability_druid_swipe",
"Punishing Might":"inv_sword_1h_artifactfelomelorn_d_03dual",
"Purification Strike":"spell_shaman_lavasurge",
"Quaking Leap":"ability_heroicleap",
"Raging Squall":"ability_deathknight_frozencenter",
"Rattle":"inv_sonic_wave",
"Ravenous":"ability_evoker_dragonrage2",
"Ravenous Bellow":"ability_druid_challangingroar",
"Ravenous Stomp":"ability_earthen_pillar",
"Ravenous Swarm":"inv_ability_druid_adaptiveswarm",
"Razor Dive":"inv_10_specialreagentfoozles_tuskclaw_fire",
"Regurgitate":"inv_ability_poison_wave",
"Release Charge":"spell_chargenegative",
"Rip and Slice":"inv_10_specialreagentfoozles_tuskclaw-black",
"Ritual Venom":"inv_ability_poison_beam",
"Ritual of Blazebinding":"spell_fire_totemofwrath",
"Ritual of the Fang":"inv_achievement_dungeon_altaroffangs",
"Roaring Flame Breath":"inv_summerfest_firespirit",
"Rolling Thunder":"spell_nature_lightningoverload",
"Rotten Supplies":"inv_misc_food_91",
"Same-Day Delivery":"achievement_brewery_2",
"Savage Leap":"ability_druid_tigersroar",
"Scavenge":"inv_vulturemount_black",
"Scavenging":"inv_misc_potionbag_special",
"Searing Blows":"ability_shaman_lavalash",
"Searing Fel Flame":"spell_fire_felfirenova",
"Seduction":"spell_shadow_seduction",
"Seismic Upheaval":"ability_rogue_kidneyshot",
"Septic Spatter":"ability_deathknight_roilingblood",
"Serpentine Gust":"ability_skyreach_four_wind",
"Serrated Charge":"inv_artifact_bloodoftheassassinated",
"Shadow Barrage":"spell_priest_mindspike",
"Shadow Bite":"spell_shadow_soulleech_3",
"Shadow Bolt Volley":"spell_shadow_shadowbolt",
"Shadow Lash":"inv_misc_volatileshadow",
"Shadow Whirlwind":"spell_necro_deathsknell",
"Shattering Frostspike":"ability_deathknight_pillaroffrost",
"Shell Guard":"inv_cape_special_turtleshell_c_01",
"Shield Bash":"ability_warrior_shieldbash",
"Shred Armor":"ability_druid_rake",
"Shred Defense":"ability_druid_ravage",
"Shredding Claws":"inv_misc_monsterclaw_03",
"Sickening Bite":"ability_creature_poison_01",
"Siphon the Weak":"spell_holy_consumemagic",
"Sky Strike":"ability_racial_wingbuffet",
"Smashing Charge":"inv_fellessergronnmount",
"Solar Breath":"ability_skyreach_solar_burst",
"Soul Crush":"inv_ability_warlock_soulrot",
"Spark Step":"spell_shaman_crashlightning",
"Spectral Slash":"ability_druid_supriseattack",
"Spit Gold":"ability_creature_amber_01",
"Spoiled Supplies":"ability_creature_disease_01",
"Spouting Floret":"inv_enchant_essenceastrallarge",
"Starvation Effigy":"inv_archaeology_80_zandalari_sanguinetotem",
"Static Shock":"spell_nature_chainlightning",
"Steel Barrage":"inv_axe_1h_deathwingraiddw_d_01",
"Storm Blessed":"spell_nature_lightningshield",
"Stormslam":"ability_shaman_stormstrike",
"Sunder Slam":"ability_warrior_shieldbreak",
"Suppression Slam":"ability_golemthunderclap",
"Synchronized Venom":"inv_ability_poison_missile",
"Tail Scythe":"inv_knife_1h_felfireraid_d_04",
"Tail Thrash":"ability_hunter_pet_windserpent",
"Tectonic Strike":"inv_axe_2h_earthendungeon_c_01",
"Tempest Barrier":"inv_shield_1h_artifactstormfist_d_04",
"Tempest Winds":"achievement_raidprimalist_windelemental",
"Thicket's Trinity":"inv_herbalism_70_dreamleaf",
"Thornblade":"spell_nature_thorns",
"Thorncaller Roar":"inv_misc_herb_nightmarevine",
"Thunder Blast":"warrior_talent_icon_bloodandthunder",
"Thunder Jaw":"inv_misc_stormdragonpale",
"Thunder Stomper":"ability_thunderclap",
"Thunder and Lightning":"warrior_talent_icon_thunderstruck",
"Thundering Storm":"spell_shaman_thunderstorm",
"Thunderstorm":"spell_shaman_thunderstorm",
"Toadspawn":"inv_egg_08",
"Tongue Toss":"ability_vehicle_launchplayer",
"Toxic Atrophy":"spell_shadow_requiem",
"Toxic Breath":"spell_fire_felflamebreath",
"Toxic Spew":"spell_nature_corrosivebreath",
"Toxic Surge":"inv_ability_poison_wave",
"Triple Shot":"spell_nature_corrosivebreath",
"Umbral Rupture":"inv_cosmicvoid_groundstate",
"Uncoil":"ability_hunter_snaketrap",
"Undermining":"spell_shaman_earthquake",
"Unstable Corruption":"spell_mage_supernova_nightborne",
"Unstable Singularity":"inv_ability_voidweaverpriest_entropicrift",
"Unstable Totem":"ability_shaman_stoneskintotem",
"Uproot":"inv_herb_earthroot",
"Venom Burst":"inv_ability_poison_groundstate",
"Venom Spit":"ability_creature_poison_02",
"Venomous Slash":"ability_rogue_disembowel",
"Venomous Spit":"spell_nature_corrosivebreath",
"Verdant Stomp":"inv_raptortravelform",
"Vigilant Defense":"creatureportrait_blackrockv2_shieldgong_02",
"Vile Fiend":"inv_argusfelstalkermount",
"Vindictive Onslaught":"spell_nature_earthquake",
"Virulent Whirl":"inv_ability_poison_groundstate",
"Void Beam":"inv_cosmicvoid_beam",
"Void Blast":"inv_cosmicvoid_missile",
"Void Cascade":"inv_cosmicvoid_missile",
"Volatile Totem":"spell_fire_totemofwrath",
"Warden's Wrath":"spell_nature_wispsplodegreen",
"Whirling Axes":"ability_butcher_whirl",
"Winds of Change":"spell_shaman_unleashweapon_wind",
"Wretched Discharge":"spell_festergutgas"
};

const CORRECTIONS=[
 ["Axegrinder","Axe Grinder","Altar of Fangs","ability",0],
 ["Boneslicer","Bone Slicer","Altar of Fangs","ability",0],
 ["Twinfang Harrower","Twin Fang Harrower","Altar of Fangs","lt",0],
 ["Uncoil","Uncoiled Writhe","Altar of Fangs","ability",0],
 ["Undermining","Undermining Shockwave","Altar of Fangs","ability",0],
 ["Bonded Beasttamer","Bonded Beast Tamer","Den of Nalorakk","trash",0],
 ["Earthshatter Slam","Earth Shatter Slam","Den of Nalorakk","ability",0],
 ["Earthwhisper Tender","Earth Whisper Tender","Den of Nalorakk","caster",0],
 ["Echoing Maul","Echoing Maw","Den of Nalorakk","ability",0],
 ["Loa Speaker Nanea","Loa Speaker Nanaea","Den of Nalorakk","mini",0],
 ["Ruthless Totemcaller","Ruthless Totem Caller","Den of Nalorakk","trash",0],
 ["Shattering Frostspike","Shattering Frost Spikes","Den of Nalorakk","ability",0],
 ["Shredding Claws","Shredding Claw","Den of Nalorakk","ability",0],
 ["Stormbound Mystic","Storm-Bound Mystic","Den of Nalorakk","caster",0],
 ["Thornclaw Gatherer","Thorn Claw Gatherer","Den of Nalorakk","trash",0],
 ["Deathly Roar","Rabond","King's Rest","ability",0],
 ["Shadow of Zul","Shade of Zul","King's Rest","mini",0],
 ["Shadow-Borne Champion","Shadowborne Champion","King's Rest","lt",0],
 ["Tazala","T'zala","King's Rest","ability",1],
 ["Felmaster Lucsei","Fel Master Luxay","Murder Row","mini",0],
 ["Heartstop Poison","Heart Stop Poison","Murder Row","ability",0],
 ["Massive Felwyrm","Massive Fel Worm","Murder Row","mini",0],
 ["Same-Day Delivery","Fel Freight","Murder Row","ability",0],
 ["Seductive Sayaad","Seductive Succubus","Murder Row","trash",0],
 ["Blazebound Destroyer","Blaze-Bound Destroyer","Ruby Life Pools","lt",0],
 ["Chillstorm","Chill Storm","Ruby Life Pools","ability",0],
 ["Defier Draghar","Defiler Draghar","Ruby Life Pools","mini",0],
 ["Flame Dance","Flame Dancer","Ruby Life Pools","ability",0],
 ["Flamegullet","Flame Gullet","Ruby Life Pools","mini",0],
 ["High Channeler Ryvati","High Channeler Riveti","Ruby Life Pools","mini",0],
 ["Primalist Flamedancer","Ash Seer Flame Dancer","Ruby Life Pools","trash",0],
 ["Ritual of Blazebinding","Ritual of Blaze Binding","Ruby Life Pools","ability",0],
 ["Stormslam","Storm Slam","Ruby Life Pools","ability",0],
 ["Tempest Barrier","Storm Cloud Detonation","Ruby Life Pools","ability",0],
 ["Adderis and Aspix","Adarrah and Aspix","Temple of Sethraliss","boss",1],
 ["Defiling Taint","Essence Defiler","Temple of Sethraliss","ability",0],
 ["Galvanized","Charged Vulnerability","Temple of Sethraliss","ability",0],
 ["Siphon the Weak","Faceless Tormentor waves","Temple of Sethraliss","ability",0],
 ["Unstable Corruption","Corrupted Guardian","Temple of Sethraliss","ability",0],
 ["Awaken the Lightbloom","Awaken the Light Bloom","The Blinding Vale","ability",0],
 ["Frantic Blooming","Rouse","The Blinding Vale","ability",0],
 ["Lightbloom's Essence","Light Bloom's Essence","The Blinding Vale","ability",0],
 ["Lightblossom Beam","Light Blossom Beam","The Blinding Vale","ability",0],
 ["Lightblossom Trinity","The Light Blossom Trinity","The Blinding Vale","boss",1],
 ["Lightgorged Lasher","Light Gorged Lasher","The Blinding Vale","trash",0],
 ["Potatoad Matriarch","Toad Matriarch","The Blinding Vale","mini",0],
 ["Radiant Spellsower","Radiant Spell Sower","The Blinding Vale","caster",0],
 ["Spouting Floret","Spouting Florid","The Blinding Vale","ability",0],
 ["Thornblade","Thorn Blade","The Blinding Vale","ability",0],
 ["Thorny Saptor","Thorny Scepter","The Blinding Vale","trash",0],
 ["Toadspawn","Toad Spawn","The Blinding Vale","ability",0],
 ["Virid Grovekeeper","Virid Grove Keeper","The Blinding Vale","lt",0],
 ["Agitated Voidscythe","Agitated Void Side","Voidscar Arena","lt",0],
 ["Chitigoth","Chiltara","Voidscar Arena","mini",0],
 ["Kilivore Screamer","Kil'vore Screamer","Voidscar Arena","trash",0],
 ["Mad Shriek","Mass Shriek","Voidscar Arena","ability",0],
 ["Raj'kess the Spellstorm","Rajh'Cath the Spellstorm","Voidscar Arena","mini",0],
 ["Savage Shredclaw","Savage Shred Claw","Voidscar Arena","trash",0],
 ["Unstable Singularity","Unstable Singularities","Voidscar Arena","ability",0],
 ["Voidtouched Magi","Void-Touched Magus","Voidscar Arena","lt",0]
];
